import { Vector3 } from '../../math/Vector3';
import { Quaternion } from '../../math/Quaternion';
import { Logger } from '../../core/Logger';

/**
 * State of a 3D turtle.
 */
export interface TurtleState {
  /** Current position */
  position: Vector3;
  /** Current orientation (as quaternion) */
  orientation: Quaternion;
  /** Current forward direction */
  direction: Vector3;
  /** Current up vector */
  up: Vector3;
  /** Current width/thickness */
  width: number;
  /** Current color index */
  color: number;
}

/**
 * Line segment generated by turtle.
 */
export interface TurtleSegment {
  /** Start position */
  start: Vector3;
  /** End position */
  end: Vector3;
  /** Line width */
  width: number;
  /** Color index */
  color: number;
}

/**
 * Configuration for turtle interpreter.
 */
export interface TurtleInterpreterConfig {
  /** Default step length for forward movement */
  stepLength?: number;
  /** Default rotation angle in degrees */
  angle?: number;
  /** Default line width */
  width?: number;
  /** Width decrease factor for branches */
  widthDecreaseFactor?: number;
  /** Initial position */
  startPosition?: Vector3;
  /** Initial direction */
  startDirection?: Vector3;
  /** Initial up vector */
  startUp?: Vector3;
}

/**
 * 3D Turtle Graphics Interpreter.
 *
 * Interprets L-system strings using turtle graphics commands.
 * The turtle maintains a position, orientation, width, and color state.
 * It generates line segments that can be used to create meshes.
 *
 * Standard commands:
 * - F: Move forward and draw
 * - f: Move forward without drawing
 * - +: Turn left (yaw)
 * - -: Turn right (yaw)
 * - &: Pitch down
 * - ^: Pitch up
 * - \: Roll left
 * - /: Roll right
 * - |: Turn around (180 degrees)
 * - [: Push state onto stack
 * - ]: Pop state from stack
 * - !: Decrease width
 * - ': Increment color index
 *
 * @example
 * ```typescript
 * const turtle = new TurtleInterpreter({
 *   stepLength: 10,
 *   angle: 25
 * });
 * const segments = turtle.interpret('F[+F]F[-F]F');
 * ```
 */
export class TurtleInterpreter {
  private stepLength: number;
  private angle: number;
  private defaultWidth: number;
  private widthDecreaseFactor: number;
  private startPosition: Vector3;
  private startDirection: Vector3;
  private startUp: Vector3;
  private logger: Logger;

  /**
   * Creates a new turtle interpreter.
   * @param config - Configuration options
   */
  constructor(config: TurtleInterpreterConfig = {}) {
    this.logger = new Logger('TurtleInterpreter');
    this.stepLength = config.stepLength ?? 1.0;
    this.angle = config.angle ?? 25.0;
    this.defaultWidth = config.width ?? 0.1;
    this.widthDecreaseFactor = config.widthDecreaseFactor ?? 0.707;
    this.startPosition = config.startPosition ?? new Vector3(0, 0, 0);
    this.startDirection = config.startDirection ?? new Vector3(0, 1, 0);
    this.startUp = config.startUp ?? new Vector3(0, 0, 1);

    this.logger.info('Turtle interpreter initialized');
  }

  /**
   * Interprets an L-system string and generates line segments.
   * @param lstring - The L-system string to interpret
   * @returns Array of line segments
   */
  public interpret(lstring: string): TurtleSegment[] {
    const segments: TurtleSegment[] = [];
    const stack: TurtleState[] = [];

    // Initialize turtle state
    let state: TurtleState = {
      position: this.startPosition.clone(),
      orientation: this.computeOrientation(this.startDirection, this.startUp),
      direction: this.startDirection.clone(),
      up: this.startUp.clone(),
      width: this.defaultWidth,
      color: 0
    };

    for (let i = 0; i < lstring.length; i++) {
      const command = lstring[i];

      switch (command) {
        case 'F':
        case 'G':
          // Move forward and draw
          segments.push(this.moveForward(state, true));
          break;

        case 'f':
          // Move forward without drawing
          this.moveForward(state, false);
          break;

        case '+':
          // Turn left (yaw)
          this.rotate(state, this.angle, state.up);
          break;

        case '-':
          // Turn right (yaw)
          this.rotate(state, -this.angle, state.up);
          break;

        case '&':
          // Pitch down
          {
            const left = state.up.clone().cross(state.direction).normalize();
            this.rotate(state, this.angle, left);
          }
          break;

        case '^':
          // Pitch up
          {
            const left = state.up.clone().cross(state.direction).normalize();
            this.rotate(state, -this.angle, left);
          }
          break;

        case '\\':
          // Roll left
          this.rotate(state, this.angle, state.direction);
          break;

        case '/':
          // Roll right
          this.rotate(state, -this.angle, state.direction);
          break;

        case '|':
          // Turn around
          this.rotate(state, 180, state.up);
          break;

        case '[':
          // Push state
          stack.push(this.cloneState(state));
          break;

        case ']':
          // Pop state
          if (stack.length > 0) {
            state = stack.pop()!;
          } else {
            this.logger.warn('Stack underflow: ] without matching [');
          }
          break;

        case '!':
          // Decrease width
          state.width *= this.widthDecreaseFactor;
          break;

        case '\'':
          // Increment color
          state.color++;
          break;

        default:
          // Ignore unknown commands
          break;
      }
    }

    if (stack.length > 0) {
      this.logger.warn(`${stack.length} unmatched [ in L-string`);
    }

    this.logger.debug(`Generated ${segments.length} segments`);
    return segments;
  }

  /**
   * Moves the turtle forward.
   * @param state - Current turtle state
   * @param draw - Whether to draw a line segment
   * @returns The line segment if drawing, undefined otherwise
   */
  private moveForward(state: TurtleState, draw: boolean): TurtleSegment {
    const start = state.position.clone();
    const offset = state.direction.clone().multiplyScalar(this.stepLength);
    state.position.add(offset);

    if (draw) {
      return {
        start,
        end: state.position.clone(),
        width: state.width,
        color: state.color
      };
    }

    return {
      start,
      end: state.position.clone(),
      width: 0,
      color: state.color
    };
  }

  /**
   * Rotates the turtle around an axis.
   * @param state - Current turtle state
   * @param degrees - Rotation angle in degrees
   * @param axis - Rotation axis (should be normalized)
   */
  private rotate(state: TurtleState, degrees: number, axis: Vector3): void {
    const radians = (degrees * Math.PI) / 180;
    const rotation = Quaternion.fromAxisAngle(axis, radians);

    state.orientation = rotation.multiply(state.orientation);
    state.direction = rotation.rotateVector(state.direction);
    state.up = rotation.rotateVector(state.up);
  }

  /**
   * Computes orientation quaternion from direction and up vectors.
   * @param direction - Forward direction
   * @param up - Up vector
   * @returns Orientation quaternion
   */
  private computeOrientation(direction: Vector3, up: Vector3): Quaternion {
    // Build orthonormal basis
    const forward = direction.clone().normalize();
    const right = up.clone().cross(forward).normalize();
    const realUp = forward.clone().cross(right).normalize();

    // Convert to quaternion
    return Quaternion.fromRotationMatrix(right, realUp, forward);
  }

  /**
   * Clones a turtle state.
   * @param state - State to clone
   * @returns Cloned state
   */
  private cloneState(state: TurtleState): TurtleState {
    return {
      position: state.position.clone(),
      orientation: state.orientation.clone(),
      direction: state.direction.clone(),
      up: state.up.clone(),
      width: state.width,
      color: state.color
    };
  }

  /**
   * Gets the current step length.
   * @returns Step length
   */
  public getStepLength(): number {
    return this.stepLength;
  }

  /**
   * Sets the step length.
   * @param length - New step length
   */
  public setStepLength(length: number): void {
    this.stepLength = Math.max(0, length);
  }

  /**
   * Gets the current rotation angle.
   * @returns Angle in degrees
   */
  public getAngle(): number {
    return this.angle;
  }

  /**
   * Sets the rotation angle.
   * @param degrees - New angle in degrees
   */
  public setAngle(degrees: number): void {
    this.angle = degrees;
  }

  /**
   * Gets the default line width.
   * @returns Default width
   */
  public getDefaultWidth(): number {
    return this.defaultWidth;
  }

  /**
   * Sets the default line width.
   * @param width - New default width
   */
  public setDefaultWidth(width: number): void {
    this.defaultWidth = Math.max(0, width);
  }
}
