import { existsSync, readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";

const reportPath = "tests/reports/foundation-engine-comparison.json";
const expectedScenes = [
  "product-configurator",
  "architecture-viewer",
  "asset-render",
  "pbr-materials",
  "large-scene",
  "instancing",
  "skinned-characters",
  "particles",
  "editor-authored-startup",
] as const;

test.describe("v3 engine comparison report", () => {
  test("records same-scene Aura3D, Three.js, and Babylon.js measurements with honest outcomes", async () => {
    expect(existsSync(reportPath), `${reportPath} must be generated by tools/compare-engines/index.ts --write-reports`).toBe(true);
    const report = JSON.parse(readFileSync(reportPath, "utf8")) as Record<string, any>;

    expect(report.suite).toBe("v3-engine-comparison");
    expect(report.ok).toBe(true);
    expect(report.claimUsable).toBe(false);
    expect(report.claimCaveat).toContain("Broad competitive claims remain unsupported");
    expect(report.scenes.map((scene: any) => scene.id)).toEqual(expectedScenes);
    expect(report.artifacts.screenshotDiffs.status).toBe("computed-rendered-benchmark-scene-diffs");
    expect(report.artifacts.renderedBenchmarkVisuals.status).toBe("captured-descriptor-driven-rendered-benchmark-scenes");
    expect(report.artifacts.screenshotDiffs.paths).toHaveLength(expectedScenes.length * 2);
    expect(report.screenshotDiffs).toHaveLength(expectedScenes.length * 2);
    for (const diff of report.screenshotDiffs) {
      expect(diff.baselineEngine).toBe("aura3d");
      expect(["threejs", "babylon"]).toContain(diff.comparedEngine);
      expect(expectedScenes).toContain(diff.sceneId);
      expect(diff.width).toBeGreaterThan(0);
      expect(diff.height).toBeGreaterThan(0);
      expect(diff.comparedPixels).toBe(diff.width * diff.height);
      expect(diff.changedPixels).toBeGreaterThanOrEqual(0);
      expect(diff.changedPixelRatio).toBeGreaterThanOrEqual(0);
      expect(diff.changedPixelRatio).toBeLessThanOrEqual(1);
      expect(diff.meanAbsoluteError).toBeGreaterThanOrEqual(0);
      expect(diff.maxChannelDelta).toBeGreaterThanOrEqual(0);
      expect(diff.pass).toBe(true);
      expect(existsSync(diff.baselinePath), `${diff.baselinePath} should exist`).toBe(true);
      expect(existsSync(diff.comparedPath), `${diff.comparedPath} should exist`).toBe(true);
      expect(existsSync(diff.diffPath), `${diff.diffPath} should exist`).toBe(true);
    }

    for (const scene of report.scenes) {
      expect(scene.equivalent, `${scene.id} should use the same descriptor shape in every engine`).toBe(true);
      if (scene.id === "editor-authored-startup") {
        expect(scene.workflow).toMatchObject({
          kind: "editor-authored-exported-app-startup",
          exportedProjectPath: "examples/foundation-editor-authored-app/project.json",
          exportedRuntimePath: "examples/foundation-editor-authored-app/runtime.js",
          editorEvidenceReportPath: "tests/reports/foundation-editor-authoring.json"
        });
        expect(scene.workflow.authoredOperations).toContain("static-export");
        expect(scene.workflow.authoredOperations).toContain("static-export-runtime");
      }
      for (const engine of ["aura3d", "threejs", "babylon"] as const) {
        const estimate = scene.estimates[engine];
        expect(estimate.measurementMode).toBe("browser-webgl2-microbenchmark");
        expect(estimate.bundleBytes).toBeGreaterThan(0);
        expect(estimate.startupMs.median).toBeGreaterThanOrEqual(0);
        expect(estimate.assetLoadMs.median).toBeGreaterThanOrEqual(0);
        expect(estimate.firstFrameMs.median).toBeGreaterThanOrEqual(0);
        expect(estimate.frameTimeMs.median).toBeGreaterThanOrEqual(0);
        expect(estimate.frameTimeMs.p95).toBeGreaterThanOrEqual(estimate.frameTimeMs.median);
        expect(estimate.drawCalls).toBeGreaterThan(0);
        expect(estimate.shaderCount).toBeGreaterThan(0);
        expect(estimate.textureCount).toBeGreaterThanOrEqual(0);
        expect(estimate.textureBytes).toBeGreaterThanOrEqual(0);
        expect(estimate.geometryBytesEstimate).toBeGreaterThan(0);
        expect(estimate.jsHeapEstimateMb.median).toBeGreaterThanOrEqual(0);
        expect(existsSync(estimate.screenshotPath), `${estimate.screenshotPath} should exist`).toBe(true);
        expect(Array.isArray(estimate.unsupportedFeatures)).toBe(true);
        if (scene.id === "editor-authored-startup") {
          expect(estimate.editorWorkflow).toMatchObject({
            kind: "editor-authored-exported-app-startup",
            operationCount: scene.workflow.authoredOperations.length
          });
          expect(estimate.editorWorkflow.projectBytes).toBeGreaterThan(0);
          expect(estimate.editorWorkflow.runtimeBytes).toBeGreaterThan(0);
          expect(estimate.editorWorkflow.comparisonMode).toContain("workflow startup evidence");
        }
      }
    }

    for (const competitor of ["threejs", "babylon"] as const) {
      const outcomes = report.comparisonOutcomes.byCompetitor[competitor];
      expect(outcomes.summary.wins + outcomes.summary.ties + outcomes.summary.losses + outcomes.summary.unavailable).toBeGreaterThan(0);
      expect(outcomes.scenes).toHaveLength(expectedScenes.length);
      for (const scene of outcomes.scenes) {
        expect(scene.unsupportedFeatures.length).toBeGreaterThan(0);
        expect(["win", "tie", "loss", "unavailable"]).toContain(scene.frameTimeMedian.result);
        expect(["win", "tie", "loss", "unavailable"]).toContain(scene.bundleBytes.result);
        expect(scene.screenshotDiff.pass).toBe(true);
        expect(existsSync(scene.screenshotDiff.diffPath), `${scene.screenshotDiff.diffPath} should exist`).toBe(true);
      }
    }
  });
});
