import { createHash } from "node:crypto";
import { createServer, type Server } from "node:http";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { extname, join, resolve } from "node:path";
import { build } from "vite";
import { expect, test, type Page } from "@playwright/test";
import { createA3DProject } from "../../packages/create-aura3d/src/index";
import rootViteConfig from "../../vite.config";

const SOURCE = resolve("benchmark/current-head-to-head/scaffold-to-deploy"); const REPORT_DIRECTORY = resolve("tests/reports/current-head-to-head/scaffold-to-deploy"); let cleanRoot = ""; let auraServer: StaticServer; let threeServer: StaticServer; let scaffoldFiles: readonly string[] = [];
test.describe("current head-to-head scaffold to deploy", () => {
  test.beforeAll(async () => { test.setTimeout(300_000); mkdirSync(REPORT_DIRECTORY, { recursive: true }); cleanRoot = mkdtempSync(resolve(".head-to-head-clean-")); const auraDir = join(cleanRoot, "aura"); const threeDir = join(cleanRoot, "three"); const generated = createA3DProject({ targetDir: auraDir, template: "product-viewer", packageVersion: "1.6.0", rootDir: resolve("packages/create-aura3d") }); scaffoldFiles = generated.files; cpSync(resolve(SOURCE, "aura-main.ts"), join(auraDir, "src/main.ts")); cpSync(resolve(SOURCE, "aura-index.html"), join(auraDir, "index.html")); rmSync(join(auraDir, "public/aura-assets"), { recursive: true, force: true }); mkdirSync(join(auraDir, "public/aura-assets"), { recursive: true }); cpSync(resolve("public/aura-assets/showcaseHeadphones.40b1fdf7.glb"), join(auraDir, "public/aura-assets/showcaseHeadphones.40b1fdf7.glb")); mkdirSync(join(threeDir, "src"), { recursive: true }); mkdirSync(join(threeDir, "public/aura-assets"), { recursive: true }); cpSync(resolve(SOURCE, "three-main.tsx"), join(threeDir, "src/main.tsx")); cpSync(resolve(SOURCE, "three-index.html"), join(threeDir, "index.html")); cpSync(resolve("public/aura-assets/showcaseHeadphones.40b1fdf7.glb"), join(threeDir, "public/aura-assets/showcaseHeadphones.40b1fdf7.glb")); writeFileSync(join(threeDir, "package.json"), `${JSON.stringify({ name: "clean-three-r3f", private: true, type: "module", dependencies: { react: "19.2.8", "react-dom": "19.2.8", three: "0.185.1", "@react-three/fiber": "9.7.0", "@react-three/drei": "10.7.8" } }, null, 2)}\n`); await build({ root: auraDir, base: "/", logLevel: "error", resolve: rootViteConfig.resolve, build: { outDir: "dist", emptyOutDir: true } }); await build({ root: threeDir, base: "/", logLevel: "error", build: { outDir: "dist", emptyOutDir: true } }); auraServer = await serve(join(auraDir, "dist")); threeServer = await serve(join(threeDir, "dist")); });
  test.afterAll(async () => { await auraServer?.close(); await threeServer?.close(); if (cleanRoot.includes(".head-to-head-clean-")) rmSync(cleanRoot, { recursive: true, force: true }); });
  test("scaffolds, builds, serves, interacts with, and retains both deploy outputs", async ({ browser }) => { test.setTimeout(300_000); const assetHash = createHash("sha256").update(readFileSync(resolve("public/aura-assets/showcaseHeadphones.40b1fdf7.glb"))).digest("hex"); const aura = await inspect(browser, auraServer.origin, "aura", "#app canvas", "__CLEAN_AURA__", "__CLEAN_AURA_ERROR__"); const three = await inspect(browser, threeServer.origin, "three", "#root canvas", "__CLEAN_THREE__", "__CLEAN_THREE_ERROR__"); expect(aura.before).toMatchObject({ ready: true, package: "@aura3d/engine", publicApiOnly: true, backend: "webgl2" }); expect(three.before).toMatchObject({ ready: true, package: "three-react-r3f", actualR3F: true, actualDrei: true, revision: "185", backend: "webgl2" }); expect(aura.beforeHash).not.toBe(aura.afterHash); expect(three.beforeHash).not.toBe(three.afterHash); expect(scaffoldFiles).toEqual(expect.arrayContaining(["index.html", "package.json", "src/main.ts", "src/aura-assets.ts"])); expect(statSync(join(cleanRoot, "aura/dist/index.html")).size).toBeGreaterThan(100); expect(statSync(join(cleanRoot, "three/dist/index.html")).size).toBeGreaterThan(100); expect(assetHash).toBe("40b1fdf7e0afdf0e5f950040f42608d3655561e61f32b9ad59690476abb15833"); writeFileSync(resolve(REPORT_DIRECTORY, "report.json"), `${JSON.stringify({ schema: "aura3d.current-head-to-head-workload/1.0", generatedAt: new Date().toISOString(), pass: true, assetSha256: assetHash, scaffoldFiles, build: { aura: listDist(join(cleanRoot, "aura/dist")), three: listDist(join(cleanRoot, "three/dist")) }, aura, three }, null, 2)}\n`); });
  test("keeps the clean Aura source public-only and the control on current React/R3F/Drei/Three", () => { const aura = readFileSync(resolve(SOURCE, "aura-main.ts"), "utf8"); const three = readFileSync(resolve(SOURCE, "three-main.tsx"), "utf8"); expect(aura).toContain('from "@aura3d/engine/lean-product"'); expect(aura).not.toContain("packages/"); expect(three).toContain('from "@react-three/fiber"'); expect(three).toContain('from "@react-three/drei"'); expect(three).toContain('from "three"'); });
});
async function inspect(browser: import("@playwright/test").Browser, origin: string, engine: "aura" | "three", canvasSelector: string, stateKey: string, errorKey: string) { const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 }); const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message)); await page.goto(origin, { waitUntil: "networkidle" }); await page.waitForFunction(([state, failure]) => Boolean((window as any)[state]?.ready || (window as any)[failure]), [stateKey, errorKey], { timeout: 180_000 }); const failure = await page.evaluate((key) => (window as any)[key], errorKey); expect(failure ?? errors.join(" | ")).toBeFalsy(); const before = await page.evaluate((key) => (window as any)[key], stateKey); const beforeHash = await capture(page, canvasSelector, `${engine}-before.png`); await page.locator("#interact").click(); if (engine === "aura") await page.waitForFunction((key) => (window as any)[key]?.interacted === true, stateKey); else await page.waitForFunction((key) => (window as any)[key]?.interacted === true, stateKey); await page.waitForTimeout(100); const after = await page.evaluate((key) => (window as any)[key], stateKey); const afterHash = await capture(page, canvasSelector, `${engine}-after.png`); await page.close(); return { before, after, beforeHash, afterHash }; }
async function capture(page: Page, selector: string, name: string) { const data = await page.$eval(selector, (canvas) => (canvas as HTMLCanvasElement).toDataURL("image/png")); const bytes = Buffer.from(data.replace(/^data:image\/png;base64,/, ""), "base64"); writeFileSync(resolve(REPORT_DIRECTORY, name), bytes); return createHash("sha256").update(bytes).digest("hex"); }
async function serve(root: string): Promise<StaticServer> { const server = createServer((request, response) => { const pathname = new URL(request.url ?? "/", "http://localhost").pathname; const candidate = resolve(root, pathname === "/" ? "index.html" : `.${pathname}`); if (!candidate.startsWith(resolve(root))) { response.writeHead(403).end(); return; } try { const bytes = readFileSync(candidate); response.writeHead(200, { "content-type": mime(candidate) }); response.end(bytes); } catch { response.writeHead(404).end(); } }); await new Promise<void>((done) => server.listen(0, "127.0.0.1", done)); const address = server.address(); if (!address || typeof address === "string") throw new Error("Static deploy server failed"); return { origin: `http://127.0.0.1:${address.port}/`, close: () => new Promise<void>((done, reject) => server.close((error) => error ? reject(error) : done())) }; }
interface StaticServer { origin: string; close(): Promise<void> }
function mime(path: string) { return ({ ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".glb": "model/gltf-binary" } as Record<string, string>)[extname(path)] ?? "application/octet-stream"; }
function listDist(root: string) { const files: Array<{ path: string; bytes: number }> = []; const walk = (directory: string) => { for (const entry of readdirSync(directory, { withFileTypes: true })) { const path = join(directory, entry.name); if (entry.isDirectory()) walk(path); else files.push({ path: path.slice(root.length + 1), bytes: statSync(path).size }); } }; walk(root); return files.sort((left, right) => left.path.localeCompare(right.path)); }
