import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, test, type Page } from "@playwright/test";
import { startExampleDevServer, type ExampleDevServer } from "./example-dev-server";

const REPORT_DIRECTORY = resolve("tests/reports/current-head-to-head/xr-interaction");
test.describe("current head-to-head injected XR interaction", () => {
  let server: ExampleDevServer;
  test.beforeAll(async () => { server = await startExampleDevServer(); mkdirSync(REPORT_DIRECTORY, { recursive: true }); });
  test.afterAll(async () => { await server.close(); });
  test("runs the public Aura controller and Three WebXRManager/XRButton at injected-session evidence level", async ({ page }) => {
    test.setTimeout(300_000); const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message)); page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
    await page.goto(`${server.origin}/benchmark/current-head-to-head/xr-interaction/`, { waitUntil: "domcontentloaded" }); await page.waitForFunction(() => Boolean(window.__AURA_THREE_HEAD_TO_HEAD_XR__?.ready || window.__AURA_THREE_HEAD_TO_HEAD_XR_ERROR__), undefined, { timeout: 240_000 }).catch(async (error) => { const probe = await page.evaluate(() => ({ state: window.__AURA_THREE_HEAD_TO_HEAD_XR__, error: window.__AURA_THREE_HEAD_TO_HEAD_XR_ERROR__ })); throw new Error(`${String(error)}\n${JSON.stringify(probe)}\n${errors.join(" | ")}`); });
    expect(await page.evaluate(() => window.__AURA_THREE_HEAD_TO_HEAD_XR_ERROR__) ?? errors.join(" | ")).toBeFalsy(); const before = await page.evaluate(() => window.__AURA_THREE_HEAD_TO_HEAD_XR__); expect(before).toMatchObject({ ready: true, workload: "xr-interaction", contract: { evidenceMode: "injected-xr-session", realHeadsetClaimed: false }, before: { aura: { publicPackageOnly: true, actualWebXRSessionController: true }, three: { revision: "185", actualRenderer: true, actualWebXRManager: true, actualXRButton: true, isPresenting: false } } });
    const assetHash = createHash("sha256").update(readFileSync(resolve("public/aura-assets/showcaseHeadphones.40b1fdf7.glb"))).digest("hex"); expect(assetHash).toBe(before.asset.sha256); expect(maxDelta(before.before.aura.backgroundPixel, before.before.three.backgroundPixel)).toBeLessThanOrEqual(3); await capturePair(page, "before");
    await page.locator("#advance").click(); await page.waitForFunction(() => Boolean(window.__AURA_THREE_HEAD_TO_HEAD_XR__?.after || window.__AURA_THREE_HEAD_TO_HEAD_XR_ERROR__), undefined, { timeout: 120_000 }); expect(await page.evaluate(() => window.__AURA_THREE_HEAD_TO_HEAD_XR_ERROR__)).toBeFalsy(); const after = await page.evaluate(() => window.__AURA_THREE_HEAD_TO_HEAD_XR__); expect(after.after.aura.session.started).toMatchObject({ supported: true, started: true, mode: "immersive-vr", referenceSpace: "local-floor" }); expect(after.after.aura.session.sample).toMatchObject({ active: true, controllerCount: 1, controllers: [{ handedness: "right", triggerPressed: true, primaryValue: 1, hapticActuatorCount: 1 }] }); expect(after.after.aura.session.hapticPulses).toBe(1); expect(after.after.three).toMatchObject({ actualInjectedXRSession: true, isPresenting: true }); expect(after.after.aura.hash).not.toBe(after.before.aura.hash); expect(after.after.three.hash).not.toBe(after.before.three.hash); expect(maxDelta(after.after.aura.backgroundPixel, after.after.three.backgroundPixel)).toBeLessThanOrEqual(3); await capturePair(page, "after");
    const lifecycle = await page.evaluate(() => (window as any).__AURA_THREE_HEAD_TO_HEAD_XR_DISPOSE__()); expect(Object.values(lifecycle).every(Boolean), JSON.stringify(lifecycle)).toBe(true); expect(errors).toEqual([]); writeFileSync(resolve(REPORT_DIRECTORY, "report.json"), `${JSON.stringify({ schema: "aura3d.current-head-to-head-workload/1.0", generatedAt: new Date().toISOString(), pass: true, assetSha256: assetHash, before: after.before, after: after.after, lifecycle }, null, 2)}\n`);
  });
  test("uses public Aura input and official current Three XR entries", () => { const source = readFileSync(resolve("benchmark/current-head-to-head/xr-interaction/main.ts"), "utf8"); expect(source).toContain('from "@aura3d/input"'); expect(source).toContain('from "three/addons/webxr/XRButton.js"'); expect(source).not.toContain("packages/"); });
});
async function capturePair(page: Page, suffix: "before" | "after"): Promise<void> { const captures = await page.evaluate(() => ({ aura: document.querySelector<HTMLCanvasElement>("#aura")!.toDataURL("image/png"), three: document.querySelector<HTMLCanvasElement>("#three")!.toDataURL("image/png") })); for (const [engine, dataUrl] of Object.entries(captures)) writeFileSync(resolve(REPORT_DIRECTORY, `${engine}-${suffix}.png`), Buffer.from(dataUrl.replace(/^data:image\/png;base64,/, ""), "base64")); }
function maxDelta(left: readonly number[], right: readonly number[]): number { return Math.max(...left.map((value, index) => Math.abs(value - (right[index] ?? 0)))); }
