import { camera, createAuraApp, createGameAppRuntime, distanceLod, lights, material, primitives, scene, type AuraPerformanceQuality } from '@aura3d/engine';
import { attachRootRenderSource, createRootParticleWorkload } from '@aura3d/engine/production-runtime';

// Only createAuraApp owns a renderer. Particles explicitly use production-runtime
// geometry with CPU simulation and native root draws; this is not GPU compute proof.
const W=960,H=540,PARTICLES=10000;
const budget={maxFrameTimeMs:16.7,minFps:55,maxDrawCalls:160,enabledFeatures:['shadow-map','ambient-particles'] as const};
const initial:AuraPerformanceQuality={resolutionScale:1,particleScale:1,lodBias:1,shadowSize:1024};
interface NativeDraw {count:number;instances:number;indexed:boolean;shadow:boolean;viewport:number[];}
interface Sample {gpuCompleted:true;frameMs:number;rafPacingMs:number;draws:NativeDraw[];pixels:number;width:number;height:number;particles:number;}
export interface RootGovernorReport {schema:string;complete:boolean;entryPoint:string;particleScope:string;hardware:string;budget:typeof budget;rungs:Array<{before:AuraPerformanceQuality;after:AuraPerformanceQuality;instances:number;overload:Sample[];adapted:Sample[];changed:string[]}>;restored?:Sample;error?:string;}
declare global {interface Window {__AURA301_ROOT_GOVERNOR__?:{run():Promise<RootGovernorReport>};}}
function disc(segments:number){const positions:Array<readonly[number,number,number]>=[[0,0,0]],indices:number[]=[];for(let i=0;i<segments;i++)positions.push([Math.cos(i/segments*Math.PI*2),Math.sin(i/segments*Math.PI*2),0]);for(let i=0;i<segments;i++)indices.push(0,i+1,(i+1)%segments+1);return{kind:"aura-custom-geometry" as const,positions,indices};}
function workload(count:number){return scene().background('#000000').camera(camera.perspective({position:[0,0,5],target:[0,0,0],fov:45})).add(lights.directional({position:[3,5,4],intensity:2})).add(primitives.box({name:'shadow receiving wall',position:[0,0,-.6],scale:[4,3,.1],material:material.pbr({color:'#888888',roughness:1})})).add(distanceLod({name:'abstract radial workload with geometric LOD',material:material.pbr({color:'#5599ee',roughness:1}),instances:Array.from({length:count},(_,i)=>({position:[(i%64-31.5)*.045,(Math.floor(i/64)%40-19.5)*.045,(i%7)*.005] as const,scale:.075})),levels:[{name:'256-sided',maxDistance:5.5,geometry:disc(256)},{name:'128-sided',maxDistance:7,geometry:disc(128)},{name:'64-sided',maxDistance:9,geometry:disc(64)},{name:'8-sided',geometry:disc(8)}]}));}
function observe(gl:WebGL2RenderingContext){let draws:NativeDraw[]=[];const original=new Map<string,(...args:any[])=>any>(),depthFbos=new Set<WebGLFramebuffer>();let fbo:WebGLFramebuffer|null=null;let viewport=[0,0,W,H];const patch=(name:string,hook:(args:any[])=>void)=>{const o=gl as any,fn=o[name].bind(gl);original.set(name,fn);o[name]=(...args:any[])=>{hook(args);return fn(...args);};};patch('bindFramebuffer',a=>{if(a[0]===gl.FRAMEBUFFER||a[0]===gl.DRAW_FRAMEBUFFER)fbo=a[1];});patch('framebufferTexture2D',a=>{if(fbo&&(a[1]===gl.DEPTH_ATTACHMENT||a[1]===gl.DEPTH_STENCIL_ATTACHMENT))depthFbos.add(fbo);});patch('deleteFramebuffer',a=>depthFbos.delete(a[0]));patch('viewport',a=>{viewport=a.slice();});for(const name of ['drawArrays','drawElements','drawArraysInstanced','drawElementsInstanced'])patch(name,a=>{if(a[0]===gl.TRIANGLES)draws.push({count:name.startsWith('drawArrays')?a[2]:a[1],instances:name.endsWith('Instanced')?a[name==='drawArraysInstanced'?3:4]:1,indexed:name.startsWith('drawElements'),shadow:fbo!==null&&depthFbos.has(fbo),viewport:[...viewport]});});return{reset(){draws=[];},snapshot(){return draws;},restore(){for(const[k,v]of original)(gl as any)[k]=v;}};}
async function completion(gl:WebGL2RenderingContext){const start=performance.now(),fence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);if(!fence)throw new Error('GPU fence unavailable');gl.flush();try{for(;;){const s=gl.clientWaitSync(fence,0,0);if(s===gl.ALREADY_SIGNALED||s===gl.CONDITION_SATISFIED)break;if(s===gl.WAIT_FAILED||performance.now()-start>30000)throw new Error('GPU completion failed');await new Promise(r=>setTimeout(r,0));}}finally{gl.deleteSync(fence);}if(gl.getError()!==gl.NO_ERROR)throw new Error('Native draw generated GL errors');}
window.__AURA301_ROOT_GOVERNOR__={async run(){
 const canvas=document.querySelector<HTMLCanvasElement>('#engine')!,gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false});if(!gl)throw new Error('WebGL2 unavailable');const observer=observe(gl);const dbg=gl.getExtension('WEBGL_debug_renderer_info');const report:RootGovernorReport={schema:'aura3d.root-governor-301/v1',complete:false,entryPoint:'@aura3d/engine:createAuraApp.stepAsync + createGameAppRuntime.pollPerformance',particleScope:'production-runtime borrowed particle geometry; CPU simulation; sole root native renderer',hardware:String(gl.getParameter(dbg?.UNMASKED_RENDERER_WEBGL??gl.RENDERER)),budget,rungs:[]};
 const particles=await createRootParticleWorkload(canvas,{count:PARTICLES,simulation:'cpu'});const detach=attachRootRenderSource(canvas,{source:{collectRenderItems:()=>particles.collectRenderItems()}});
 let count=512;const app=createAuraApp(canvas,{scene:workload(count),autoStart:false,resize:false,pixelRatio:1,renderer:{mode:'production',qualityProfile:'production',fallback:'safe-basic'}});let quality={...initial};const runtime=createGameAppRuntime(app,{autoStart:false,performanceBudget:{mode:'conservative',budget,apply:q=>{app.setPerformanceQuality(q);quality={...q};}}});
 const measure=async(frames:number):Promise<Sample[]>=>{const samples:Sample[]=[];let previous=await new Promise<number>(r=>requestAnimationFrame(r));for(let i=0;i<frames;i++){const tick=await new Promise<number>(r=>requestAnimationFrame(r));observer.reset();const start=performance.now();await particles.update(1/60);await app.stepAsync(1/60);await completion(gl);const frameMs=performance.now()-start;const bytes=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,bytes);let pixels=0;for(let p=0;p<bytes.length;p+=4)if(bytes[p]!+bytes[p+1]!+bytes[p+2]!>24)pixels++;if(app.diagnostics().errors.length)throw new Error(JSON.stringify(app.diagnostics().errors));samples.push({gpuCompleted:true,frameMs,rafPacingMs:tick-previous,draws:observer.snapshot(),pixels,width:canvas.width,height:canvas.height,particles:particles.diagnostics().activeCount});previous=tick;}return samples;};
 try{await app.ready();app.setPerformanceQuality(initial);for(let rung=0;rung<11;rung++){
  let overload=await measure(8);while(overload.reduce((s,f)=>s+f.frameMs,0)/overload.length<=budget.maxFrameTimeMs){count*=2;if(count>131072)throw new Error('Workload cap reached without actual overload; cannot prove this governor rung');app.setScene(workload(count));await app.ready();app.setPerformanceQuality(quality);overload=await measure(8);}
  const before={...quality},frameTimeMs=overload.reduce((s,f)=>s+f.frameMs,0)/overload.length,last=overload.at(-1)!;runtime.pollPerformance({fps:1000/frameTimeMs,frameTimeMs,draws:last.draws.length,tris:last.draws.reduce((s,d)=>s+d.count*d.instances/3,0),particles:last.particles,shadowBytes:quality.shadowSize**2*4});const changed=Object.keys(initial).filter(k=>before[k as keyof AuraPerformanceQuality]!==quality[k as keyof AuraPerformanceQuality]);const adapted=await measure(3);report.rungs.push({before,after:{...quality},instances:count,overload,adapted,changed});}
 app.setPerformanceQuality(initial);report.restored=(await measure(1))[0];return report;
 }catch(error){report.error=error instanceof Error?error.stack??error.message:String(error);return report;}finally{await app.disposeAsync();runtime.dispose();detach();particles.dispose();observer.restore();}
}};
