// Auto-generated by @aura3d/cli. Do not edit by hand.
export const assets = {
  "arenaNeonDowntown": {"type":"model","format":"glb","url":"/aura-assets/arenaNeonDowntown.56a42b19.glb","hash":"sha256-56a42b193bbce0dc13fc632ac771a17eadbbdbdde0c3267c982fdbefc2318333","bounds":[20.644,28.2,25.322],"sizeBytes":16459256},
  "auraClashDuelStage": {"type":"model","format":"glb","url":"/aura-assets/auraClashDuelStage.09735d3b.glb","hash":"sha256-09735d3bb00092a6134152b9fcad57b82fa7d20c1e493442344de7a2d278617d","bounds":[20.644,29.125,18.628],"sizeBytes":11157588},
  "auraClashPlayableScene": {"type":"model","format":"glb","url":"/aura-assets/auraClashPlayableScene.15296b6b.glb","hash":"sha256-15296b6b736f88546c6bd95e1581762dbb96f7b2533c57e26ed93202f8d24583","bounds":[20.644,29.7,25.322],"sizeBytes":14270384},
  "fighterJinFlux": {"type":"model","format":"glb","url":"/aura-assets/fighterJinFlux.6404abf6.glb","hash":"sha256-6404abf6c480d98918c64b686d625cc8904309589cfa261c154d78753ca30f86","bounds":[1.64,1.339,0.882],"sizeBytes":677320},
  "fighterKadeEmber": {"type":"model","format":"glb","url":"/aura-assets/fighterKadeEmber.5e387f1c.glb","hash":"sha256-5e387f1cb248208121e2017a60d940297ad4ef01bbe6f5f2c4bd6298f999a6d8","bounds":[0.766,1.819,1.237],"sizeBytes":677228},
  "fighterMaraVolt": {"type":"model","format":"glb","url":"/aura-assets/fighterMaraVolt.18af93d3.glb","hash":"sha256-18af93d37c11336dcdab43ce5f16d37ce25a403bf583d51ec36caaf3f2df4fd2","bounds":[0.796,1.78,1.184],"sizeBytes":1047560},
  "fighterNyxVale": {"type":"model","format":"glb","url":"/aura-assets/fighterNyxVale.13e7bfa8.glb","hash":"sha256-13e7bfa8343faf9b445abc73d9f954f4b1ced8c73c346cb5a00a84328159d57e","bounds":[1.459,1.293,0.869],"sizeBytes":1031856},
  "fighterRookAtlas": {"type":"model","format":"glb","url":"/aura-assets/fighterRookAtlas.09571256.glb","hash":"sha256-09571256b92d921a2c96499403ff48c3a8e1a40996ebbd6cc98b35866942bba6","bounds":[1.131,1.804,1.202],"sizeBytes":665164},
  "fighterSableIron": {"type":"model","format":"glb","url":"/aura-assets/fighterSableIron.3d88a3a7.glb","hash":"sha256-3d88a3a73922fb5fa23cf8d2a1eda1da4f50f070c270aa910c9d7660e38f0829","bounds":[0.827,1.757,0.81],"sizeBytes":935824},
  "auraClashTrainingMannequin": {"type":"model","format":"glb","url":"/aura-assets/auraClashTrainingMannequin.d8672924.glb","hash":"sha256-d867292451e432b735e2a910c2db6640fbea97b205d85a2e8ffed26da87972cf","bounds":[1.944,1.829,0.37],"sizeBytes":8114364}
} as const;

export type AuraAssetName = keyof typeof assets;
