/**
 * PRD-03 §6.2 — single-reference tone-mapping operators, ported verbatim from
 * three@0.185.1 `src/renderers/shaders/ShaderChunk/tonemapping_pars_fragment.glsl.js`.
 *
 * The v2 post chain (Phase 2+) runs exactly one of these per pixel, after the
 * exposure multiply, before the sRGB encode. Constants are GLSL->TS literals;
 * `mat3 * vec3` is expanded as `col0*v.x + col1*v.y + col2*v.z` (GLSL column-major
 * construction), matching the transposed matrices in the source chunk.
 *
 * Golden vectors: tests/qr/prd03/goldens/tone-operators.json (generated by
 * tests/qr/prd03/goldens/generate-tone-goldens.mjs).
 */

export type AuraToneOperator = "none" | "linear" | "reinhard" | "aces" | "agx" | "neutral";

export type Vec3 = readonly [number, number, number];

const saturate = (v: number): number => Math.min(1, Math.max(0, v));
const sat3 = (c: Vec3): Vec3 => [saturate(c[0]), saturate(c[1]), saturate(c[2])];

type Mat3Cols = readonly [Vec3, Vec3, Vec3];
const mulMat3 = (m: Mat3Cols, v: Vec3): Vec3 => [
  m[0][0] * v[0] + m[1][0] * v[1] + m[2][0] * v[2],
  m[0][1] * v[0] + m[1][1] * v[1] + m[2][1] * v[2],
  m[0][2] * v[0] + m[1][2] * v[1] + m[2][2] * v[2]
];

export function linearToneMapping(color: Vec3, exposure: number): Vec3 {
  return sat3([exposure * color[0], exposure * color[1], exposure * color[2]]);
}

/** source: https://www.cs.utah.edu/docs/techreports/2002/pdf/UUCS-02-001.pdf */
export function reinhardToneMapping(color: Vec3, exposure: number): Vec3 {
  const c: Vec3 = [exposure * color[0], exposure * color[1], exposure * color[2]];
  return sat3([c[0] / (1 + c[0]), c[1] / (1 + c[1]), c[2] / (1 + c[2])]);
}

/** source: http://filmicworlds.com/blog/filmic-tonemapping-operators/ */
export function cineonToneMapping(color: Vec3, exposure: number): Vec3 {
  const out = [0, 0, 0] as [number, number, number];
  for (let i = 0; i < 3; i += 1) {
    const c = Math.max(0, exposure * color[i]! - 0.004);
    out[i] = Math.pow((c * (6.2 * c + 0.5)) / (c * (6.2 * c + 1.7) + 0.06), 2.2);
  }
  return out;
}

/** source: https://github.com/selfshadow/ltc_code/blob/master/webgl/shaders/ltc/ltc_blit.fs */
function RRTAndODTFit(v: Vec3): Vec3 {
  const out = [0, 0, 0] as [number, number, number];
  for (let i = 0; i < 3; i += 1) {
    const x = v[i]!;
    const a = x * (x + 0.0245786) - 0.000090537;
    const b = x * (0.983729 * x + 0.4329510) + 0.238081;
    out[i] = a / b;
  }
  return out;
}

// sRGB => XYZ => D65_2_D60 => AP1 => RRT_SAT (transposed from source, column-major)
const ACES_INPUT_MAT: Mat3Cols = [
  [0.59719, 0.07600, 0.02840],
  [0.35458, 0.90834, 0.13383],
  [0.04823, 0.01566, 0.83777]
];

// ODT_SAT => XYZ => D60_2_D65 => sRGB (transposed from source, column-major)
const ACES_OUTPUT_MAT: Mat3Cols = [
  [1.60475, -0.10208, -0.00327],
  [-0.53108, 1.10813, -0.07276],
  [-0.07367, -0.00605, 1.07602]
];

/**
 * Brighter-viewing-environment ACES fit (scale 1/0.6, three.js #19621).
 * This is the r185 ACESFilmicToneMapping — the operator three's
 * `renderer.toneMapping = ACESFilmicToneMapping` applies in the OutputPass.
 */
export function acesFilmicToneMapping(color: Vec3, exposure: number): Vec3 {
  let c: Vec3 = [color[0] * exposure / 0.6, color[1] * exposure / 0.6, color[2] * exposure / 0.6];
  c = mulMat3(ACES_INPUT_MAT, c);
  c = RRTAndODTFit(c);
  c = mulMat3(ACES_OUTPUT_MAT, c);
  return sat3(c);
}

// rec2020 <> rec709 conversion (BT.2407, transposed, column-major)
const LINEAR_REC2020_TO_LINEAR_SRGB: Mat3Cols = [
  [1.6605, -0.1246, -0.0182],
  [-0.5876, 1.1329, -0.1006],
  [-0.0728, -0.0083, 1.1187]
];
const LINEAR_SRGB_TO_LINEAR_REC2020: Mat3Cols = [
  [0.6274, 0.0691, 0.0164],
  [0.3293, 0.9195, 0.0880],
  [0.0433, 0.0113, 0.8956]
];

const AGX_INSET_MAT: Mat3Cols = [
  [0.856627153315983, 0.137318972929847, 0.11189821299995],
  [0.0951212405381588, 0.761241990602591, 0.0767994186031903],
  [0.0482516061458583, 0.101439036467562, 0.811302368396859]
];
const AGX_OUTSET_MAT: Mat3Cols = [
  [1.1271005818144368, -0.1413297634984383, -0.14132976349843826],
  [-0.11060664309660323, 1.157823702216272, -0.11060664309660294],
  [-0.016493938717834573, -0.016493938717834257, 1.2519364065950405]
];

// LOG2_MIN = -10.0, LOG2_MAX = +6.5, MIDDLE_GRAY = 0.18
const AGX_MIN_EV = -12.47393;
const AGX_MAX_EV = 4.026069;

/** https://iolite-engine.com/blog_posts/minimal_agx_implementation (mean err^2 3.6705141e-06) */
function agxDefaultContrastApprox(x: Vec3): Vec3 {
  const out = [0, 0, 0] as [number, number, number];
  for (let i = 0; i < 3; i += 1) {
    const v = x[i]!;
    const x2 = v * v;
    const x4 = x2 * x2;
    out[i] = 15.5 * x4 * x2
      - 40.14 * x4 * v
      + 31.96 * x4
      - 6.868 * x2 * v
      + 0.4298 * x2
      + 0.1191 * v
      - 0.00232;
  }
  return out;
}

/**
 * AgX (Filament/Blender rec-2020 fit; inputs/outputs linear-sRGB), r185.
 * three r185 has no fake AgX equivalent — Aura3D's legacy "agx" label is a
 * Reinhard approximation; this is the real operator.
 */
export function agxToneMapping(color: Vec3, exposure: number): Vec3 {
  let c: Vec3 = [color[0] * exposure, color[1] * exposure, color[2] * exposure];
  c = mulMat3(LINEAR_SRGB_TO_LINEAR_REC2020, c);
  c = mulMat3(AGX_INSET_MAT, c);
  c = [Math.max(c[0], 1e-10), Math.max(c[1], 1e-10), Math.max(c[2], 1e-10)];
  c = [Math.log2(c[0]), Math.log2(c[1]), Math.log2(c[2])];
  c = [
    (c[0] - AGX_MIN_EV) / (AGX_MAX_EV - AGX_MIN_EV),
    (c[1] - AGX_MIN_EV) / (AGX_MAX_EV - AGX_MIN_EV),
    (c[2] - AGX_MIN_EV) / (AGX_MAX_EV - AGX_MIN_EV)
  ];
  c = [saturate(c[0]), saturate(c[1]), saturate(c[2])];
  c = agxDefaultContrastApprox(c);
  c = mulMat3(AGX_OUTSET_MAT, c);
  c = [Math.pow(Math.max(0, c[0]), 2.2), Math.pow(Math.max(0, c[1]), 2.2), Math.pow(Math.max(0, c[2]), 2.2)];
  c = mulMat3(LINEAR_REC2020_TO_LINEAR_SRGB, c);
  return sat3(c);
}

const NEUTRAL_START_COMPRESSION = 0.8 - 0.04;
const NEUTRAL_DESATURATION = 0.15;

/** Khronos PBR Neutral (modelviewer.dev), r185. */
export function neutralToneMapping(color: Vec3, exposure: number): Vec3 {
  let c: Vec3 = [color[0] * exposure, color[1] * exposure, color[2] * exposure];
  const x = Math.min(c[0], Math.min(c[1], c[2]));
  const offset = x < 0.08 ? x - 6.25 * x * x : 0.04;
  c = [c[0] - offset, c[1] - offset, c[2] - offset];
  const peak = Math.max(c[0], Math.max(c[1], c[2]));
  if (peak < NEUTRAL_START_COMPRESSION) return c;
  const d = 1 - NEUTRAL_START_COMPRESSION;
  const newPeak = 1 - d * d / (peak + d - NEUTRAL_START_COMPRESSION);
  const scale = newPeak / peak;
  c = [c[0] * scale, c[1] * scale, c[2] * scale];
  const g = 1 - 1 / (NEUTRAL_DESATURATION * (peak - newPeak) + 1);
  return [
    c[0] + (newPeak - c[0]) * g,
    c[1] + (newPeak - c[1]) * g,
    c[2] + (newPeak - c[2]) * g
  ];
}

/**
 * The v2 chain's single dispatch: exposure multiply happens inside each
 * operator (three folds `toneMappingExposure` into the operator body), so the
 * caller passes linear-HDR input and the operator + exposure used for it.
 */
export function applyToneOperator(operator: AuraToneOperator, color: Vec3, exposure = 1): Vec3 {
  switch (operator) {
    case "none": return sat3([exposure * color[0], exposure * color[1], exposure * color[2]]);
    case "linear": return linearToneMapping(color, exposure);
    case "reinhard": return reinhardToneMapping(color, exposure);
    case "aces": return acesFilmicToneMapping(color, exposure);
    case "agx": return agxToneMapping(color, exposure);
    case "neutral": return neutralToneMapping(color, exposure);
    default: {
      const exhaustive: never = operator;
      throw new Error(`POST_TONE_OPERATOR_UNKNOWN:${String(exhaustive)}`);
    }
  }
}

/** Operators shipped by the v2 OutputPass; `none` is only reachable via compat paths. */
export const POST_TONE_OPERATORS: readonly Exclude<AuraToneOperator, "none">[] = ["linear", "reinhard", "aces", "agx", "neutral"];
