import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1100, height: 700 } });
await page.goto('http://127.0.0.1:7782/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(4500);
await page.screenshot({ path: 'marketing/screenshots/v8-hero.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 2.2 }));
await page.waitForTimeout(8000);
await page.screenshot({ path: 'marketing/screenshots/v8-workflows.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 3.5 }));
await page.waitForTimeout(8000);
await page.screenshot({ path: 'marketing/screenshots/v8-diagnostics.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 4.8 }));
await page.waitForTimeout(8000);
await page.screenshot({ path: 'marketing/screenshots/v8-backends.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 6.0 }));
await page.waitForTimeout(8000);
await page.screenshot({ path: 'marketing/screenshots/v8-gltf.png' });
await page.evaluate(() => document.querySelector('#gallery')?.scrollIntoView({block:'start'}));
await page.waitForTimeout(8000);
await page.screenshot({ path: 'marketing/screenshots/v8-gallery.png' });
await browser.close();
