import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto('http://127.0.0.1:7782/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(3000);
await page.screenshot({ path: 'marketing/screenshots/v7-hero.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 2.2 }));
await page.waitForTimeout(7000);
await page.screenshot({ path: 'marketing/screenshots/v7-workflows.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 3.5 }));
await page.waitForTimeout(7000);
await page.screenshot({ path: 'marketing/screenshots/v7-diagnostics.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 4.8 }));
await page.waitForTimeout(7000);
await page.screenshot({ path: 'marketing/screenshots/v7-backends.png' });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 6.0 }));
await page.waitForTimeout(7000);
await page.screenshot({ path: 'marketing/screenshots/v7-gltf.png' });
await page.evaluate(() => document.querySelector('#gallery')?.scrollIntoView({block:'start'}));
await page.waitForTimeout(7000);
await page.screenshot({ path: 'marketing/screenshots/v7-gallery.png' });
await browser.close();
