// Generates every resolution map for @aura3d/engine from /aura.exports.json
// (PRD-15 §6.9, T1.2):
//   1. /package.json#exports                        (byte-exact via JSON.stringify(pkg, null, 2))
//   2. /tsconfig.paths.generated.json               (all in-repo specifiers)
//   3. /vite.aliases.generated.ts                   (rows where flags.vite !== false)
//   4. /tools/finalize-dist/manifest.generated.json (merged spec view)
// Deprecated entries additionally emit a re-export stub source at the mapped
// path so the published dist target keeps resolving until removeIn.
// Usage: pnpm exec tsx --tsconfig tsconfig.base.json tools/generate-resolution-maps/index.ts --write|--check [--root <dir>]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

export interface AuraEntry {
  readonly source?: string;
  readonly conditions?: boolean;
  readonly browser?: string;
  readonly devOnly?: boolean;
}

export interface AuraDeprecatedEntry {
  readonly source?: string;
  readonly target: string;
  readonly removeIn?: string;
}

export interface AuraPathRowFlags {
  readonly vite?: boolean;
  readonly browser301?: boolean;
  readonly browser?: string;
}

export type AuraPathRow = readonly [specifier: string, file: string] | readonly [specifier: string, file: string, flags: AuraPathRowFlags];

export interface AuraExportsFile {
  readonly package: string;
  readonly entries: Record<string, AuraEntry>;
  readonly deprecated?: Record<string, AuraDeprecatedEntry>;
  readonly paths: readonly AuraPathRow[];
}

/** packages/<pkg>/src/<rest>.ts -> ./dist/<pkg>/<rest>.<ext> */
export function distTarget(source: string, ext: "js" | "d.ts"): string {
  const match = /^packages\/([^/]+)\/src\/(.+)\.ts$/.exec(source);
  if (!match) throw new Error(`entry source outside packages/*/src: ${source}`);
  return `./dist/${match[1]}/${match[2]}.${ext}`;
}

export function buildPackageExports(aura: AuraExportsFile): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [subpath, entry] of Object.entries(aura.entries)) {
    if (!entry.source) throw new Error(`entry ${subpath} is missing source`);
    const dist = distTarget(entry.source, "js");
    const dts = distTarget(entry.source, "d.ts");
    if (entry.conditions || entry.browser) {
      out[subpath] = {
        types: dts,
        browser: entry.browser ? distTarget(entry.browser, "js") : dist,
        import: dist,
        default: dist
      };
    } else {
      out[subpath] = dist;
    }
  }
  for (const [subpath, entry] of Object.entries(aura.deprecated ?? {})) {
    if (!entry.source) throw new Error(`deprecated entry ${subpath} is missing source`);
    out[subpath] = distTarget(entry.source, "js");
  }
  return out;
}

function rowFlags(row: AuraPathRow): AuraPathRowFlags {
  return row.length > 2 ? row[2]! : {};
}

export function buildTsconfigPaths(aura: AuraExportsFile): Record<string, unknown> {
  const paths: Record<string, string[]> = {};
  for (const row of aura.paths) paths[row[0]] = [row[1]];
  return { compilerOptions: { paths } };
}

/** Vite replacement for a specifier row: row browser override, else the entry
 * whose source is this file and which declares a browser variant. */
function viteReplacement(aura: AuraExportsFile, row: AuraPathRow): string {
  const flags = rowFlags(row);
  if (flags.browser) return flags.browser;
  for (const entry of Object.values(aura.entries)) {
    if (entry.browser && entry.source === row[1]) return entry.browser;
  }
  return row[1];
}

export function buildViteAliases(aura: AuraExportsFile): string {
  const lines: string[] = [
    "// Generated by tools/generate-resolution-maps — edit aura.exports.json instead.",
    "// Ordering matters: a string `find` matches by PREFIX, so deeper subpaths",
    "// must precede the bare package or the prefix rewrite targets a file path",
    "// as a directory and the bundle dies with ENOTDIR.",
    "export const aliasEntries = ["
  ];
  for (const row of aura.paths) {
    if (rowFlags(row).vite === false) continue;
    lines.push(`  ["${row[0]}", "./${viteReplacement(aura, row)}"],`);
  }
  lines.push("] as const;", "");
  return lines.join("\n");
}

export function buildManifest(aura: AuraExportsFile): Record<string, unknown> {
  const specifiers = aura.paths.map((row) => ({
    name: row[0],
    file: row[1],
    ...(rowFlags(row).browser ? { browserFile: rowFlags(row).browser } : {}),
    ...(rowFlags(row).vite === false ? { devOnly: true } : {}),
    ...(rowFlags(row).browser301 === false ? { browser301: false } : {})
  }));
  const subpaths = Object.entries(aura.entries).map(([name, entry]) => ({
    name,
    source: entry.source,
    dist: entry.source ? distTarget(entry.source, "js") : undefined,
    ...(entry.conditions ? { conditions: true } : {}),
    ...(entry.browser ? { browser: entry.browser, browserDist: distTarget(entry.browser, "js") } : {}),
    ...(entry.devOnly ? { devOnly: true } : {})
  }));
  const deprecated = Object.entries(aura.deprecated ?? {}).map(([name, entry]) => ({
    name,
    target: entry.target,
    removeIn: entry.removeIn ?? null,
    stub: entry.source ?? null
  }));
  return { package: aura.package, specifiers, subpaths, deprecated };
}

/** Re-export stub emitted for a deprecated subpath (T1.2 test b). */
export function deprecatedStubContent(aura: AuraExportsFile, subpath: string, entry: AuraDeprecatedEntry): string {
  if (!entry.source) throw new Error(`deprecated entry ${subpath} is missing source`);
  const targetEntry = aura.entries[entry.target];
  if (!targetEntry?.source) throw new Error(`deprecated ${subpath} targets unknown entry ${entry.target}`);
  const fromDir = dirname(entry.source);
  const to = relative(fromDir, targetEntry.source).replace(/\.ts$/, ".js");
  const specifier = to.startsWith(".") ? to : `./${to}`;
  return [
    `// Deprecated subpath: resolves to ${entry.target} until removeIn ${entry.removeIn ?? "the next major"}.`,
    `// Generated by tools/generate-resolution-maps — edit aura.exports.json instead.`,
    `export * from "${specifier}";`,
    `export { default } from "${specifier}";`,
    ""
  ].join("\n");
}

export interface WrittenArtifacts {
  readonly files: readonly string[];
}

function writeIfChanged(path: string, content: string, changed: string[]): void {
  if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    changed.push(path);
  }
}

export function generateResolutionMaps(root: string, mode: "write" | "check"): { ok: boolean; changed: string[]; diffs: string[] } {
  const aura = JSON.parse(readFileSync(join(root, "aura.exports.json"), "utf8")) as AuraExportsFile;
  const exportsObject = buildPackageExports(aura);
  const pkgPath = join(root, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { exports?: unknown };
  const diffs: string[] = [];
  const changed: string[] = [];
  if (JSON.stringify(pkg.exports) !== JSON.stringify(exportsObject)) {
    if (mode === "write") {
      pkg.exports = exportsObject;
      writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
      changed.push(pkgPath);
    } else {
      diffs.push("package.json#exports differs from generated output");
    }
  }
  const artifacts: Array<[string, string]> = [
    [join(root, "tsconfig.paths.generated.json"), `${JSON.stringify(buildTsconfigPaths(aura), null, 2)}\n`],
    [join(root, "vite.aliases.generated.ts"), buildViteAliases(aura)],
    [join(root, "tools/finalize-dist/manifest.generated.json"), `${JSON.stringify(buildManifest(aura), null, 2)}\n`]
  ];
  for (const [path, content] of artifacts) {
    if (mode === "write") writeIfChanged(path, content, changed);
    else if (!existsSync(path) || readFileSync(path, "utf8") !== content) diffs.push(`${path} differs from generated output`);
  }
  for (const [subpath, entry] of Object.entries(aura.deprecated ?? {})) {
    const stubPath = join(root, entry.source!);
    const stub = deprecatedStubContent(aura, subpath, entry);
    if (mode === "write") writeIfChanged(stubPath, stub, changed);
    else if (!existsSync(stubPath) || readFileSync(stubPath, "utf8") !== stub) diffs.push(`${stubPath} differs from generated stub`);
  }
  return { ok: mode === "write" || diffs.length === 0, changed, diffs };
}

if (process.argv[1] && /generate-resolution-maps[\\/]index\.ts$/.test(process.argv[1])) {
  const args = process.argv.slice(2);
  const mode = args.includes("--check") ? "check" : args.includes("--write") ? "write" : null;
  const rootIdx = args.indexOf("--root");
  const root = rootIdx >= 0 ? args[rootIdx + 1]! : process.cwd();
  if (!mode) {
    console.error("usage: index.ts --write|--check [--root <dir>]");
    process.exit(2);
  }
  const result = generateResolutionMaps(root, mode);
  for (const diff of result.diffs) console.error(`DIFF ${diff}`);
  for (const file of result.changed) console.log(`wrote ${file}`);
  process.exit(result.ok ? 0 : 1);
}
