// Generates every resolution map for @aura3d/engine from /aura.exports.json
// (PRD-15 §6.9, T1.2):
//   1. /package.json#exports                        (byte-exact via JSON.stringify(pkg, null, 2))
//   2. /tsconfig.paths.generated.json               (all in-repo specifiers)
//   3. /vite.aliases.generated.ts                   (rows where flags.vite !== false)
//   4. /tools/finalize-dist/manifest.generated.json (merged spec view)
// Deprecated entries additionally emit a re-export stub source at the mapped
// path so the published dist target keeps resolving until removeIn.
// Usage: pnpm exec tsx --tsconfig tsconfig.base.json tools/generate-resolution-maps/index.ts --write|--check [--root <dir>]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

export interface AuraEntry {
  readonly source?: string;
  readonly conditions?: boolean;
  readonly browser?: string;
  readonly devOnly?: boolean;
}

export interface AuraDeprecatedEntry {
  readonly source?: string;
  /** Old implementation source the deprecated stub keeps re-exporting until removeIn. */
  readonly of?: string;
  readonly target: string;
  readonly removeIn?: string;
}

export interface AuraPathRowFlags {
  readonly vite?: boolean;
  readonly browser301?: boolean;
  readonly browser?: string;
}

export type AuraPathRow = readonly [specifier: string, file: string] | readonly [specifier: string, file: string, flags: AuraPathRowFlags];

export interface AuraExportsFile {
  readonly package: string;
  readonly entries: Record<string, AuraEntry>;
  readonly deprecated?: Record<string, AuraDeprecatedEntry>;
  readonly paths: readonly AuraPathRow[];
}

/** packages/<pkg>/src/<rest>.ts -> ./dist/<pkg>/<rest>.<ext> */
export function distTarget(source: string, ext: "js" | "d.ts"): string {
  const match = /^packages\/([^/]+)\/src\/(.+)\.ts$/.exec(source);
  if (!match) throw new Error(`entry source outside packages/*/src: ${source}`);
  return `./dist/${match[1]}/${match[2]}.${ext}`;
}

/** Asset-like entry sources (css/binary) ship under the same dist mirror path
 * verbatim — no .js emit exists for them. */
const ASSET_SOURCE = /^packages\/([^/]+)\/src\/(.+\.(?:css|glb|gltf|hdr|jpg|jpeg|ktx2|png|svg|webp|bin))$/i;

export function buildPackageExports(aura: AuraExportsFile): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [subpath, entry] of Object.entries(aura.entries)) {
    if (!entry.source) throw new Error(`entry ${subpath} is missing source`);
    const asset = ASSET_SOURCE.exec(entry.source);
    if (asset) {
      out[subpath] = `./dist/${asset[1]}/${asset[2]}`;
      continue;
    }
    const dist = distTarget(entry.source, "js");
    const dts = distTarget(entry.source, "d.ts");
    if (entry.conditions || entry.browser) {
      out[subpath] = {
        types: dts,
        browser: entry.browser ? distTarget(entry.browser, "js") : dist,
        import: dist,
        default: dist
      };
    } else {
      out[subpath] = dist;
    }
  }
  for (const [subpath, entry] of Object.entries(aura.deprecated ?? {})) {
    if (!entry.source) throw new Error(`deprecated entry ${subpath} is missing source`);
    out[subpath] = distTarget(entry.source, "js");
  }
  return out;
}

function rowFlags(row: AuraPathRow): AuraPathRowFlags {
  return row.length > 2 ? row[2]! : {};
}

export function buildTsconfigPaths(aura: AuraExportsFile): Record<string, unknown> {
  const paths: Record<string, string[]> = {};
  for (const row of aura.paths) paths[row[0]] = [row[1]];
  return { compilerOptions: { paths } };
}

/** Vite replacement for a specifier row: row browser override, else the entry
 * whose source is this file and which declares a browser variant. */
function viteReplacement(aura: AuraExportsFile, row: AuraPathRow): string {
  const flags = rowFlags(row);
  if (flags.browser) return flags.browser;
  for (const entry of Object.values(aura.entries)) {
    if (entry.browser && entry.source === row[1]) return entry.browser;
  }
  return row[1];
}

export function buildViteAliases(aura: AuraExportsFile): string {
  const lines: string[] = [
    "// Generated by tools/generate-resolution-maps — edit aura.exports.json instead.",
    "// Ordering matters: a string `find` matches by PREFIX, so deeper subpaths",
    "// must precede the bare package or the prefix rewrite targets a file path",
    "// as a directory and the bundle dies with ENOTDIR.",
    "export const aliasEntries = ["
  ];
  for (const row of aura.paths) {
    if (rowFlags(row).vite === false) continue;
    lines.push(`  ["${row[0]}", "./${viteReplacement(aura, row)}"],`);
  }
  lines.push("] as const;", "");
  return lines.join("\n");
}

export function buildManifest(aura: AuraExportsFile): Record<string, unknown> {
  const specifiers = aura.paths.map((row) => ({
    name: row[0],
    file: row[1],
    ...(rowFlags(row).browser ? { browserFile: rowFlags(row).browser } : {}),
    ...(rowFlags(row).vite === false ? { devOnly: true } : {}),
    ...(rowFlags(row).browser301 === false ? { browser301: false } : {})
  }));
  const subpaths = Object.entries(aura.entries).map(([name, entry]) => ({
    name,
    source: entry.source,
    dist: entry.source
      ? ASSET_SOURCE.exec(entry.source)
        ? `./dist/${ASSET_SOURCE.exec(entry.source)![1]}/${ASSET_SOURCE.exec(entry.source)![2]}`
        : distTarget(entry.source, "js")
      : undefined,
    ...(entry.conditions ? { conditions: true } : {}),
    ...(entry.browser ? { browser: entry.browser, browserDist: distTarget(entry.browser, "js") } : {}),
    ...(entry.devOnly ? { devOnly: true } : {})
  }));
  const deprecated = Object.entries(aura.deprecated ?? {}).map(([name, entry]) => ({
    name,
    target: entry.target,
    removeIn: entry.removeIn ?? null,
    stub: entry.source ?? null
  }));
  return { package: aura.package, specifiers, subpaths, deprecated };
}

/**
 * Re-export stub emitted for a deprecated subpath (T1.2 test b, T5.6).
 * The stub re-exports the OLD implementation source (`of`), not the target
 * entry: names only reachable through the deprecated subpath have no §6.6
 * destination and must keep resolving until removeIn. A module-eval
 * `console.warn` fires once per realm per subpath.
 */
export function deprecatedStubContent(aura: AuraExportsFile, subpath: string, entry: AuraDeprecatedEntry, root = "."): string {
  if (!entry.source) throw new Error(`deprecated entry ${subpath} is missing source`);
  if (!aura.entries[entry.target]?.source) throw new Error(`deprecated ${subpath} targets unknown entry ${entry.target}`);
  const ofSource = entry.of ?? aura.entries[entry.target]!.source!;
  const specifier = deprecatedOfSpecifier(aura, entry.source, ofSource);
  const ofAbs = join(root, ofSource);
  const hasDefault = existsSync(ofAbs) && /export\s+default\b/.test(readFileSync(ofAbs, "utf8"));
  const lines = [
    `// Deprecated subpath: keeps its pre-collapse surface until removeIn ${entry.removeIn ?? "the next major"}; new imports belong on ${entry.target}.`,
    `// Generated by tools/generate-resolution-maps — edit aura.exports.json instead.`,
    `const key = "@aura3d/engine${subpath === "." ? "" : `/${subpath.replace(/^\.\//, "")}`}";`,
    `const warned = ((globalThis as { __a3dDeprecatedSubpaths?: Set<string> }).__a3dDeprecatedSubpaths ??= new Set<string>());`,
    `if (!warned.has(key)) {`,
    `  warned.add(key);`,
    `  // eslint-disable-next-line no-console`,
    `  console.warn(\`[aura3d] \${key} is deprecated and resolves to ${entry.target}; it will be removed in ${entry.removeIn ?? "the next major"}.\`);`,
    `}`,
    `export * from "${specifier}";`
  ];
  if (hasDefault) lines.push(`export { default } from "${specifier}";`);
  lines.push("");
  return lines.join("\n");
}

/** Resolve a deprecated stub's `of` source to an import specifier. */
function deprecatedOfSpecifier(aura: AuraExportsFile, stubSource: string, ofSource: string): string {
  if (ofSource.startsWith("packages/engine/src/")) {
    const to = relative(dirname(stubSource), ofSource).replace(/\.ts$/, ".js");
    return to.startsWith(".") ? to : `./${to}`;
  }
  for (const row of aura.paths) {
    if (row[1] === ofSource) return row[0];
  }
  throw new Error(`deprecated stub ${stubSource}: no specifier maps to ${ofSource}; add an aura.exports.json paths row`);
}

export interface WrittenArtifacts {
  readonly files: readonly string[];
}

function writeIfChanged(path: string, content: string, changed: string[]): void {
  if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    changed.push(path);
  }
}

/** Splice a generated `paths` block into tsconfig.base.json#compilerOptions.
 * Several repo tools raw-JSON.parse tsconfig.base.json for its paths map
 * (tools/agent-docs/simulation.ts, tools/eslint-plugin-aura3d-boundaries,
 * tools/foundation-code) and cannot follow `extends`; the block therefore
 * stays present but is machine-generated here — never hand-maintained. */
export function spliceTsconfigPaths(baseText: string, pathsObject: Record<string, string[]>): string {
  const serialized = JSON.stringify(pathsObject, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : `    ${line}`))
    .join("\n");
  const block = `"paths": ${serialized.replace(/\n$/, "")}`;
  const start = baseText.indexOf('"paths": {');
  if (start >= 0) {
    const braceStart = start + '"paths": '.length;
    let depth = 0;
    let end = braceStart;
    for (; end < baseText.length; end += 1) {
      if (baseText[end] === "{") depth += 1;
      else if (baseText[end] === "}") {
        depth -= 1;
        if (depth === 0) { end += 1; break; }
      }
    }
    return `${baseText.slice(0, start)}${block}${baseText.slice(end)}`;
  }
  const marker = '"compilerOptions": {';
  const insertAt = baseText.indexOf(marker);
  if (insertAt < 0) throw new Error("tsconfig.base.json has no compilerOptions");
  const at = insertAt + marker.length;
  return `${baseText.slice(0, at)}\n    ${block},${baseText.slice(at)}`;
}

export function generateResolutionMaps(root: string, mode: "write" | "check"): { ok: boolean; changed: string[]; diffs: string[] } {
  const aura = JSON.parse(readFileSync(join(root, "aura.exports.json"), "utf8")) as AuraExportsFile;
  const exportsObject = buildPackageExports(aura);
  const pkgPath = join(root, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { exports?: unknown };
  const diffs: string[] = [];
  const changed: string[] = [];
  if (JSON.stringify(pkg.exports) !== JSON.stringify(exportsObject)) {
    if (mode === "write") {
      pkg.exports = exportsObject;
      writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
      changed.push(pkgPath);
    } else {
      diffs.push("package.json#exports differs from generated output");
    }
  }
  const tsconfigPaths = buildTsconfigPaths(aura) as { compilerOptions: { paths: Record<string, string[]> } };
  const artifacts: Array<[string, string]> = [
    [join(root, "tsconfig.paths.generated.json"), `${JSON.stringify(tsconfigPaths, null, 2)}\n`],
    [join(root, "vite.aliases.generated.ts"), buildViteAliases(aura)],
    [join(root, "tools/finalize-dist/manifest.generated.json"), `${JSON.stringify(buildManifest(aura), null, 2)}\n`]
  ];
  for (const [path, content] of artifacts) {
    if (mode === "write") writeIfChanged(path, content, changed);
    else if (!existsSync(path) || readFileSync(path, "utf8") !== content) diffs.push(`${path} differs from generated output`);
  }
  // tsconfig.base.json keeps the same generated block inline (see spliceTsconfigPaths).
  const basePath = join(root, "tsconfig.base.json");
  if (existsSync(basePath)) {
    const baseNext = spliceTsconfigPaths(readFileSync(basePath, "utf8"), tsconfigPaths.compilerOptions.paths);
    if (mode === "write") writeIfChanged(basePath, baseNext, changed);
    else if (readFileSync(basePath, "utf8") !== baseNext) diffs.push("tsconfig.base.json#compilerOptions.paths differs from generated output");
  }
  for (const [subpath, entry] of Object.entries(aura.deprecated ?? {})) {
    const stubPath = join(root, entry.source!);
    const stub = deprecatedStubContent(aura, subpath, entry, root);
    if (mode === "write") writeIfChanged(stubPath, stub, changed);
    else if (!existsSync(stubPath) || readFileSync(stubPath, "utf8") !== stub) diffs.push(`${stubPath} differs from generated stub`);
  }
  return { ok: mode === "write" || diffs.length === 0, changed, diffs };
}

if (process.argv[1] && /generate-resolution-maps[\\/]index\.ts$/.test(process.argv[1])) {
  const args = process.argv.slice(2);
  const mode = args.includes("--check") ? "check" : args.includes("--write") ? "write" : null;
  const rootIdx = args.indexOf("--root");
  const root = rootIdx >= 0 ? args[rootIdx + 1]! : process.cwd();
  if (!mode) {
    console.error("usage: index.ts --write|--check [--root <dir>]");
    process.exit(2);
  }
  const result = generateResolutionMaps(root, mode);
  for (const diff of result.diffs) console.error(`DIFF ${diff}`);
  for (const file of result.changed) console.log(`wrote ${file}`);
  process.exit(result.ok ? 0 : 1);
}
