import { readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const json = (path: string): any => JSON.parse(readFileSync(resolve(path), "utf8")); const text = (path: string): string => readFileSync(resolve(path), "utf8");
const baseline = json("tests/reports/current-threejs-baseline.json"); const context = json("benchmark/context/threejs-r185.1-20260808.json"); const browser = json("tests/reports/current-head-to-head/physical-character/report.json"); const source = text("benchmark/current-head-to-head/physical-character/main.ts"); const captures = ["aura-before.png", "three-before.png", "aura-after.png", "three-after.png"];
const checks = [
  { id: "current-three-and-selected-rapier", pass: baseline.three?.version === "0.185.1" && browser.before?.three?.revision === "185" && source.includes('from "@aura3d/physics-rapier"') && source.includes('from "@dimforge/rapier3d-compat"') },
  { id: "exact-frozen-character-and-native-captures", pass: browser.assetSha256 === context.assets.skinnedCharacter.sha256 && captures.every((name) => statSync(resolve(`tests/reports/current-head-to-head/physical-character/${name}`)).size > 10_000) },
  { id: "public-adapter-versus-direct-native-controller", pass: browser.before?.aura?.publicPackageOnly === true && browser.before?.aura?.actualSelectedRapierAdapter === true && browser.before?.aura?.nativeCharacterController === true && browser.before?.three?.actualDirectRapier === true && browser.before?.three?.nativeCharacterController === true && !source.includes("packages/") },
  { id: "identical-start-and-end-poses", pass: maxDelta(browser.before?.aura?.position, browser.before?.three?.position) < 1e-6 && maxDelta(browser.after?.aura?.position, browser.after?.three?.position) < 1e-5 },
  { id: "collision-constrained-grounded-traversal", pass: browser.after?.aura?.position?.[0] > browser.before?.aura?.position?.[0] + 2 && browser.after?.three?.position?.[0] > browser.before?.three?.position?.[0] + 2 && browser.after?.aura?.movement?.totalCollisions > 0 && browser.after?.three?.movement?.totalCollisions > 0 && browser.after?.aura?.movement?.groundedFrames > 0 && browser.after?.three?.movement?.groundedFrames > 0 },
  { id: "paired-visible-state-change", pass: browser.before?.aura?.hash !== browser.after?.aura?.hash && browser.before?.three?.hash !== browser.after?.three?.hash },
  { id: "matched-background-output", pass: maxDelta(browser.before?.aura?.backgroundPixel, browser.before?.three?.backgroundPixel) <= 3 && maxDelta(browser.after?.aura?.backgroundPixel, browser.after?.three?.backgroundPixel) <= 3 },
  { id: "caller-owned-lifecycle", pass: Object.values(browser.lifecycle ?? {}).every(Boolean) && Object.keys(browser.lifecycle ?? {}).length === 5 }
];
const failures = checks.filter((entry) => !entry.pass); const report = { schema: "aura3d.current-head-to-head-physical-character/1.0", generatedAt: new Date().toISOString(), pass: failures.length === 0, workload: "physical-character", verdict: "selected-adapter-matches-direct-rapier-controller-trace", checks, failures, comparison: { auraPosition: browser.after?.aura?.position, threePosition: browser.after?.three?.position, auraCollisions: browser.after?.aura?.movement?.totalCollisions, threeCollisions: browser.after?.three?.movement?.totalCollisions, observedLosses: ["Personal inspection of all four retained frames confirms aligned framing, exact backgrounds, closely matched character/material output, and a visibly meaningful final pose on top of the autostep obstacle. Small pose/highlight raster differences remain.", "This deterministic kinematic-controller trace proves selected-adapter equivalence for the chosen ground/autostep traversal only; it does not establish universal physical-character, animation-state-machine, networking, or performance parity."], claimBoundary: "Optional @aura3d/physics-rapier adapter workload; not root createAuraApp physical simulation." }, browser }; const output = resolve("tests/reports/current-head-to-head/physical-character/aggregate.json"); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); if (failures.length) { console.error(`Physical-character head-to-head UNPROVEN: ${failures.map((entry) => entry.id).join(", ")}`); process.exitCode = 1; } else console.log(`Physical-character head-to-head PASS: ${checks.length}/${checks.length}; ${output}`);
function maxDelta(left: readonly number[] | undefined, right: readonly number[] | undefined): number { if (!left || !right) return Number.POSITIVE_INFINITY; return Math.max(...left.map((value, index) => Math.abs(value - (right[index] ?? 0)))); }
