import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { describe, expect, test } from "vitest";
import { createProductionPrimitiveTextureIntent, defineAuraAssets, material } from "@aura3d/engine";
import type { AuraMaterialSpec } from "@aura3d/engine";

const textures = defineAuraAssets({
  sample: { type: "texture", format: "png", url: "/tests/browser/fixtures/c1-checker.png", hash: "99496e5e0a5e216a" }
});
const slots = ["clearcoat", "clearcoatRoughness", "clearcoatNormal", "sheenColor", "sheenRoughness", "iridescence", "iridescenceThickness", "anisotropy"] as const;

describe("root physical extension texture intent", () => {
  test.each(slots)("preserves %s independently with its color space and UV transform", (slot) => {
    const transform = { offset: [0.2, -0.3] as const, scale: [2, 0.5] as const, rotation: 0.7 };
    const spec: AuraMaterialSpec = {
      [`${slot}Map`]: textures.sample,
      texCoords: { [slot]: 1 }, texTransforms: { [slot]: transform }
    };
    const intent = createProductionPrimitiveTextureIntent(material.pbr(spec));
    expect(Object.keys(intent.extensionMaps ?? {})).toEqual([slot]);
    expect(intent.extensionMaps?.[slot]).toEqual({
      url: textures.sample.url, colorSpace: slot === "sheenColor" ? "srgb" : "linear", texCoord: 1, transform
    });
    expect(intent.baseColorUrl).toBeUndefined();
  });

  test("maps remain distinct from extension scalars", () => {
    expect(createProductionPrimitiveTextureIntent({ clearcoat: 1, sheen: 1, iridescence: 1, anisotropy: 1 }).extensionMaps).toBeUndefined();
  });

  test.each(slots)("rejects untyped %s map inputs instead of silently ignoring them", (slot) => {
    expect(() => createProductionPrimitiveTextureIntent({ [`${slot}Map`]: "/untracked.png" } as unknown as AuraMaterialSpec)).toThrow(/typed texture/);
    expect(() => createProductionPrimitiveTextureIntent({ [`${slot}Map`]: { kind: "aura-procedural-texture", texture: "fabric-normal" } } as unknown as AuraMaterialSpec)).toThrow(/typed texture/);
  });

  test("rejects unsupported UV sets and nonfinite transforms", () => {
    expect(() => createProductionPrimitiveTextureIntent({ clearcoatMap: textures.sample, texCoords: { clearcoat: 2 } } as unknown as AuraMaterialSpec)).toThrow(/texCoord/);
    expect(() => createProductionPrimitiveTextureIntent({ clearcoatMap: textures.sample, texTransforms: { clearcoat: { rotation: Number.NaN } } })).toThrow(/finite/);
  });
});


describe("extension analytical fixture provenance and channel isolation", () => {
  const directory = "tests/browser/fixtures/c1-extension";
  function pixels(name: string): Buffer {
    const png = readFileSync(`${directory}/source/${name}.png`);
    const compressed: Buffer[] = [];
    for (let offset = 8; offset < png.length;) {
      const length = png.readUInt32BE(offset);
      if (png.toString("ascii", offset + 4, offset + 8) === "IDAT") compressed.push(png.subarray(offset + 8, offset + 8 + length));
      offset += length + 12;
    }
    const raw = inflateSync(Buffer.concat(compressed));
    return Buffer.concat(Array.from({ length: 32 }, (_, row) => raw.subarray(row * 129 + 1, row * 129 + 129)));
  }
  test("all four channels vary independently and channel decoys preserve only their designated input", () => {
    const source = pixels("rgba");
    for (let channel = 0; channel < 4; channel++) {
      const values = Array.from({ length: 1024 }, (_, index) => source[index * 4 + channel]);
      expect(new Set(values).size).toBeGreaterThan(100);
      const decoy = pixels(`decoy${"RGBA"[channel]}`);
      for (let index = 0; index < source.length; index++) expect(decoy[index]).toBe(index % 4 === channel ? source[index] : 255 - source[index]!);
    }
    expect(pixels("swapped")).not.toEqual(source);
    const rotated = pixels("direction");
    for (let index = 0; index < source.length; index += 4) {
      const x = source[index]! * 2 - 255, y = source[index + 1]! * 2 - 255;
      expect((rotated[index]! * 2 - 255) * x + (rotated[index + 1]! * 2 - 255) * y).toBe(0);
      expect(rotated[index + 2]).toBe(source[index + 2]);
      expect(rotated[index + 3]).toBe(source[index + 3]);
    }
  });
  test("the CLI manifest binds every fixture to actual generated bytes and durable provenance", () => {
    const manifest = JSON.parse(readFileSync(`${directory}/aura.assets.json`, "utf8"));
    expect(manifest.assets.length).toBe(13);
    for (const asset of manifest.assets) {
      expect(asset.hash).toBe(`sha256-${createHash("sha256").update(readFileSync(`${directory}/${asset.outputPath}`)).digest("hex")}`);
      expect(asset.provenance).toBeDefined();
    }
  });
});
