/**
 * Typed ids for the game-sfx-core pack (PRD-09 §6.9 / C-25).
 * Generated from assets/packs/game-sfx-core/manifest.json by the sfx-pack
 * pipeline — do not hand-edit; re-run the generator after re-admitting files.
 * Leaves are variant-id tuples; the engine picks a variant per trigger.
 */
export const sfx = {
  ambience: {
    cityDay: ["ambience.city-day"],
    cityNight: ["ambience.city-night"],
    crowdArena: ["ambience.crowd-arena"],
    crowdSports: ["ambience.crowd-sports"],
    hangar: ["ambience.hangar"],
    interiorHum: ["ambience.interior-hum"],
    spaceHum: ["ambience.space-hum"],
    underwater: ["ambience.underwater"],
    windHigh: ["ambience.wind-high"],
    windOpen: ["ambience.wind-open"],
  },
  creature: {
    announcer: {
      fight: ["creature.announcer.fight.00", "creature.announcer.fight.01"],
      ko: ["creature.announcer.ko.00", "creature.announcer.ko.01"],
      perfect: ["creature.announcer.perfect.00", "creature.announcer.perfect.01"],
      round: ["creature.announcer.round.00", "creature.announcer.round.01"],
    },
    gruntHeavy: ["creature.grunt-heavy.00", "creature.grunt-heavy.01"],
    gruntLight: ["creature.grunt-light.00", "creature.grunt-light.01"],
    ko: ["creature.ko.00", "creature.ko.01"],
  },
  explosion: {
    chargeUp: ["explosion.charge-up.00", "explosion.charge-up.01", "explosion.charge-up.02"],
    large: ["explosion.large.00", "explosion.large.01", "explosion.large.02"],
    laser: ["explosion.laser.00", "explosion.laser.01", "explosion.laser.02"],
    medium: ["explosion.medium.00", "explosion.medium.01", "explosion.medium.02"],
    shieldHit: ["explosion.shield-hit.00", "explosion.shield-hit.01", "explosion.shield-hit.02"],
    small: ["explosion.small.00", "explosion.small.01", "explosion.small.02"],
    zap: ["explosion.zap.00", "explosion.zap.01", "explosion.zap.02"],
  },
  footsteps: {
    concrete: ["footsteps.concrete.00", "footsteps.concrete.01", "footsteps.concrete.02", "footsteps.concrete.03"],
    grass: ["footsteps.grass.00", "footsteps.grass.01", "footsteps.grass.02", "footsteps.grass.03"],
    gravel: ["footsteps.gravel.00", "footsteps.gravel.01", "footsteps.gravel.02", "footsteps.gravel.03"],
    metal: ["footsteps.metal.00", "footsteps.metal.01", "footsteps.metal.02", "footsteps.metal.03"],
    water: ["footsteps.water.00", "footsteps.water.01", "footsteps.water.02", "footsteps.water.03"],
    wood: ["footsteps.wood.00", "footsteps.wood.01", "footsteps.wood.02", "footsteps.wood.03"],
  },
  impact: {
    energy: {
      heavy: ["impact.energy.heavy.00", "impact.energy.heavy.01", "impact.energy.heavy.02"],
      light: ["impact.energy.light.00", "impact.energy.light.01", "impact.energy.light.02"],
      medium: ["impact.energy.medium.00", "impact.energy.medium.01", "impact.energy.medium.02"],
    },
    flesh: {
      heavy: ["impact.flesh.heavy.00", "impact.flesh.heavy.01", "impact.flesh.heavy.02"],
      light: ["impact.flesh.light.00", "impact.flesh.light.01", "impact.flesh.light.02"],
      medium: ["impact.flesh.medium.00", "impact.flesh.medium.01", "impact.flesh.medium.02"],
    },
    glass: {
      heavy: ["impact.glass.heavy.00", "impact.glass.heavy.01", "impact.glass.heavy.02"],
      light: ["impact.glass.light.00", "impact.glass.light.01", "impact.glass.light.02"],
      medium: ["impact.glass.medium.00", "impact.glass.medium.01", "impact.glass.medium.02"],
    },
    metal: {
      heavy: ["impact.metal.heavy.00", "impact.metal.heavy.01", "impact.metal.heavy.02"],
      light: ["impact.metal.light.00", "impact.metal.light.01", "impact.metal.light.02"],
      medium: ["impact.metal.medium.00", "impact.metal.medium.01", "impact.metal.medium.02"],
    },
    plastic: {
      heavy: ["impact.plastic.heavy.00", "impact.plastic.heavy.01", "impact.plastic.heavy.02"],
      light: ["impact.plastic.light.00", "impact.plastic.light.01", "impact.plastic.light.02"],
      medium: ["impact.plastic.medium.00", "impact.plastic.medium.01", "impact.plastic.medium.02"],
    },
    rubberBall: {
      heavy: ["impact.rubber-ball.heavy.00", "impact.rubber-ball.heavy.01", "impact.rubber-ball.heavy.02"],
      light: ["impact.rubber-ball.light.00", "impact.rubber-ball.light.01", "impact.rubber-ball.light.02"],
      medium: ["impact.rubber-ball.medium.00", "impact.rubber-ball.medium.01", "impact.rubber-ball.medium.02"],
    },
    stone: {
      heavy: ["impact.stone.heavy.00", "impact.stone.heavy.01", "impact.stone.heavy.02"],
      light: ["impact.stone.light.00", "impact.stone.light.01", "impact.stone.light.02"],
      medium: ["impact.stone.medium.00", "impact.stone.medium.01", "impact.stone.medium.02"],
    },
    wood: {
      heavy: ["impact.wood.heavy.00", "impact.wood.heavy.01", "impact.wood.heavy.02"],
      light: ["impact.wood.light.00", "impact.wood.light.01", "impact.wood.light.02"],
      medium: ["impact.wood.medium.00", "impact.wood.medium.01", "impact.wood.medium.02"],
    },
  },
  pickup: {
    coin: ["pickup.coin.00", "pickup.coin.01"],
    comboUp: ["pickup.combo-up.00", "pickup.combo-up.01"],
    extraLife: ["pickup.extra-life.00", "pickup.extra-life.01"],
    gem: ["pickup.gem.00", "pickup.gem.01"],
    powerDown: ["pickup.power-down.00", "pickup.power-down.01"],
    powerUp: ["pickup.power-up.00", "pickup.power-up.01"],
  },
  sports: {
    ballBounceCourt: ["sports.ball-bounce-court.00", "sports.ball-bounce-court.01", "sports.ball-bounce-court.02"],
    ballBounceHard: ["sports.ball-bounce-hard.00", "sports.ball-bounce-hard.01", "sports.ball-bounce-hard.02"],
    billiardClack: ["sports.billiard-clack.00", "sports.billiard-clack.01", "sports.billiard-clack.02"],
    bumper: ["sports.bumper.00", "sports.bumper.01", "sports.bumper.02"],
    cushion: ["sports.cushion.00", "sports.cushion.01", "sports.cushion.02"],
    flipper: ["sports.flipper.00", "sports.flipper.01", "sports.flipper.02"],
    netSwish: ["sports.net-swish.00", "sports.net-swish.01", "sports.net-swish.02"],
    plunger: ["sports.plunger.00", "sports.plunger.01", "sports.plunger.02"],
    pocket: ["sports.pocket.00", "sports.pocket.01", "sports.pocket.02"],
    rim: ["sports.rim.00", "sports.rim.01", "sports.rim.02"],
  },
  stinger: {
    alarm: ["stinger.alarm.00", "stinger.alarm.01"],
    checkpoint: ["stinger.checkpoint.00", "stinger.checkpoint.01"],
    levelStart: ["stinger.level-start.00", "stinger.level-start.01"],
    lose: ["stinger.lose.00", "stinger.lose.01"],
    win: ["stinger.win.00", "stinger.win.01"],
  },
  ui: {
    back: ["ui.back.00", "ui.back.01"],
    click: ["ui.click.00", "ui.click.01"],
    confirm: ["ui.confirm.00", "ui.confirm.01"],
    countdownGo: ["ui.countdown-go.00", "ui.countdown-go.01"],
    countdownTick: ["ui.countdown-tick.00", "ui.countdown-tick.01"],
    error: ["ui.error.00", "ui.error.01"],
    hover: ["ui.hover.00", "ui.hover.01"],
    reward: ["ui.reward.00", "ui.reward.01"],
    scoreTick: ["ui.score-tick.00", "ui.score-tick.01"],
    sliderTick: ["ui.slider-tick.00", "ui.slider-tick.01"],
    toggle: ["ui.toggle.00", "ui.toggle.01"],
    unlock: ["ui.unlock.00", "ui.unlock.01"],
  },
  vehicle: {
    boost: ["vehicle.boost"],
    carSmall: {
      layer0: {
        off: ["vehicle.car-small.layer0.off"],
        on: ["vehicle.car-small.layer0.on"],
      },
      layer1: {
        off: ["vehicle.car-small.layer1.off"],
        on: ["vehicle.car-small.layer1.on"],
      },
      layer2: {
        off: ["vehicle.car-small.layer2.off"],
        on: ["vehicle.car-small.layer2.on"],
      },
    },
    carSport: {
      layer0: {
        off: ["vehicle.car-sport.layer0.off"],
        on: ["vehicle.car-sport.layer0.on"],
      },
      layer1: {
        off: ["vehicle.car-sport.layer1.off"],
        on: ["vehicle.car-sport.layer1.on"],
      },
      layer2: {
        off: ["vehicle.car-sport.layer2.off"],
        on: ["vehicle.car-sport.layer2.on"],
      },
    },
    carSportReal: ["vehicle.car-sport-real"],
    gearShift: ["vehicle.gear-shift", "vehicle.gear-shift.01"],
    jet: {
      layer0: {
        off: ["vehicle.jet.layer0.off"],
        on: ["vehicle.jet.layer0.on"],
      },
      layer1: {
        off: ["vehicle.jet.layer1.off"],
        on: ["vehicle.jet.layer1.on"],
      },
      layer2: {
        off: ["vehicle.jet.layer2.off"],
        on: ["vehicle.jet.layer2.on"],
      },
    },
    propPlane: {
      layer0: {
        off: ["vehicle.prop-plane.layer0.off"],
        on: ["vehicle.prop-plane.layer0.on"],
      },
      layer1: {
        off: ["vehicle.prop-plane.layer1.off"],
        on: ["vehicle.prop-plane.layer1.on"],
      },
      layer2: {
        off: ["vehicle.prop-plane.layer2.off"],
        on: ["vehicle.prop-plane.layer2.on"],
      },
    },
    thruster: {
      layer0: {
        off: ["vehicle.thruster.layer0.off"],
        on: ["vehicle.thruster.layer0.on"],
      },
      layer1: {
        off: ["vehicle.thruster.layer1.off"],
        on: ["vehicle.thruster.layer1.on"],
      },
      layer2: {
        off: ["vehicle.thruster.layer2.off"],
        on: ["vehicle.thruster.layer2.on"],
      },
      layer3: {
        off: ["vehicle.thruster.layer3.off"],
        on: ["vehicle.thruster.layer3.on"],
      },
    },
    tyreSkid: ["vehicle.tyre-skid"],
    van: {
      layer0: {
        off: ["vehicle.van.layer0.off"],
        on: ["vehicle.van.layer0.on"],
      },
      layer1: {
        off: ["vehicle.van.layer1.off"],
        on: ["vehicle.van.layer1.on"],
      },
      layer2: {
        off: ["vehicle.van.layer2.off"],
        on: ["vehicle.van.layer2.on"],
      },
    },
    vanReal: ["vehicle.van-real"],
  },
  whoosh: {
    dash: ["whoosh.dash.00", "whoosh.dash.01", "whoosh.dash.02"],
    passByLarge: ["whoosh.pass-by-large.00", "whoosh.pass-by-large.01", "whoosh.pass-by-large.02"],
    passBySmall: ["whoosh.pass-by-small.00", "whoosh.pass-by-small.01", "whoosh.pass-by-small.02"],
    swingHeavy: ["whoosh.swing-heavy.00", "whoosh.swing-heavy.01", "whoosh.swing-heavy.02"],
    swingLight: ["whoosh.swing-light.00", "whoosh.swing-light.01", "whoosh.swing-light.02"],
  },
} as const;

export const SFX_IDS = [
  "ambience.city-day",
  "ambience.city-night",
  "ambience.crowd-arena",
  "ambience.crowd-sports",
  "ambience.hangar",
  "ambience.interior-hum",
  "ambience.space-hum",
  "ambience.underwater",
  "ambience.wind-high",
  "ambience.wind-open",
  "creature.announcer.fight.00",
  "creature.announcer.fight.01",
  "creature.announcer.ko.00",
  "creature.announcer.ko.01",
  "creature.announcer.perfect.00",
  "creature.announcer.perfect.01",
  "creature.announcer.round.00",
  "creature.announcer.round.01",
  "creature.grunt-heavy.00",
  "creature.grunt-heavy.01",
  "creature.grunt-light.00",
  "creature.grunt-light.01",
  "creature.ko.00",
  "creature.ko.01",
  "explosion.charge-up.00",
  "explosion.charge-up.01",
  "explosion.charge-up.02",
  "explosion.large.00",
  "explosion.large.01",
  "explosion.large.02",
  "explosion.laser.00",
  "explosion.laser.01",
  "explosion.laser.02",
  "explosion.medium.00",
  "explosion.medium.01",
  "explosion.medium.02",
  "explosion.shield-hit.00",
  "explosion.shield-hit.01",
  "explosion.shield-hit.02",
  "explosion.small.00",
  "explosion.small.01",
  "explosion.small.02",
  "explosion.zap.00",
  "explosion.zap.01",
  "explosion.zap.02",
  "footsteps.concrete.00",
  "footsteps.concrete.01",
  "footsteps.concrete.02",
  "footsteps.concrete.03",
  "footsteps.grass.00",
  "footsteps.grass.01",
  "footsteps.grass.02",
  "footsteps.grass.03",
  "footsteps.gravel.00",
  "footsteps.gravel.01",
  "footsteps.gravel.02",
  "footsteps.gravel.03",
  "footsteps.metal.00",
  "footsteps.metal.01",
  "footsteps.metal.02",
  "footsteps.metal.03",
  "footsteps.water.00",
  "footsteps.water.01",
  "footsteps.water.02",
  "footsteps.water.03",
  "footsteps.wood.00",
  "footsteps.wood.01",
  "footsteps.wood.02",
  "footsteps.wood.03",
  "impact.energy.heavy.00",
  "impact.energy.heavy.01",
  "impact.energy.heavy.02",
  "impact.energy.light.00",
  "impact.energy.light.01",
  "impact.energy.light.02",
  "impact.energy.medium.00",
  "impact.energy.medium.01",
  "impact.energy.medium.02",
  "impact.flesh.heavy.00",
  "impact.flesh.heavy.01",
  "impact.flesh.heavy.02",
  "impact.flesh.light.00",
  "impact.flesh.light.01",
  "impact.flesh.light.02",
  "impact.flesh.medium.00",
  "impact.flesh.medium.01",
  "impact.flesh.medium.02",
  "impact.glass.heavy.00",
  "impact.glass.heavy.01",
  "impact.glass.heavy.02",
  "impact.glass.light.00",
  "impact.glass.light.01",
  "impact.glass.light.02",
  "impact.glass.medium.00",
  "impact.glass.medium.01",
  "impact.glass.medium.02",
  "impact.metal.heavy.00",
  "impact.metal.heavy.01",
  "impact.metal.heavy.02",
  "impact.metal.light.00",
  "impact.metal.light.01",
  "impact.metal.light.02",
  "impact.metal.medium.00",
  "impact.metal.medium.01",
  "impact.metal.medium.02",
  "impact.plastic.heavy.00",
  "impact.plastic.heavy.01",
  "impact.plastic.heavy.02",
  "impact.plastic.light.00",
  "impact.plastic.light.01",
  "impact.plastic.light.02",
  "impact.plastic.medium.00",
  "impact.plastic.medium.01",
  "impact.plastic.medium.02",
  "impact.rubber-ball.heavy.00",
  "impact.rubber-ball.heavy.01",
  "impact.rubber-ball.heavy.02",
  "impact.rubber-ball.light.00",
  "impact.rubber-ball.light.01",
  "impact.rubber-ball.light.02",
  "impact.rubber-ball.medium.00",
  "impact.rubber-ball.medium.01",
  "impact.rubber-ball.medium.02",
  "impact.stone.heavy.00",
  "impact.stone.heavy.01",
  "impact.stone.heavy.02",
  "impact.stone.light.00",
  "impact.stone.light.01",
  "impact.stone.light.02",
  "impact.stone.medium.00",
  "impact.stone.medium.01",
  "impact.stone.medium.02",
  "impact.wood.heavy.00",
  "impact.wood.heavy.01",
  "impact.wood.heavy.02",
  "impact.wood.light.00",
  "impact.wood.light.01",
  "impact.wood.light.02",
  "impact.wood.medium.00",
  "impact.wood.medium.01",
  "impact.wood.medium.02",
  "pickup.coin.00",
  "pickup.coin.01",
  "pickup.combo-up.00",
  "pickup.combo-up.01",
  "pickup.extra-life.00",
  "pickup.extra-life.01",
  "pickup.gem.00",
  "pickup.gem.01",
  "pickup.power-down.00",
  "pickup.power-down.01",
  "pickup.power-up.00",
  "pickup.power-up.01",
  "sports.ball-bounce-court.00",
  "sports.ball-bounce-court.01",
  "sports.ball-bounce-court.02",
  "sports.ball-bounce-hard.00",
  "sports.ball-bounce-hard.01",
  "sports.ball-bounce-hard.02",
  "sports.billiard-clack.00",
  "sports.billiard-clack.01",
  "sports.billiard-clack.02",
  "sports.bumper.00",
  "sports.bumper.01",
  "sports.bumper.02",
  "sports.cushion.00",
  "sports.cushion.01",
  "sports.cushion.02",
  "sports.flipper.00",
  "sports.flipper.01",
  "sports.flipper.02",
  "sports.net-swish.00",
  "sports.net-swish.01",
  "sports.net-swish.02",
  "sports.plunger.00",
  "sports.plunger.01",
  "sports.plunger.02",
  "sports.pocket.00",
  "sports.pocket.01",
  "sports.pocket.02",
  "sports.rim.00",
  "sports.rim.01",
  "sports.rim.02",
  "stinger.alarm.00",
  "stinger.alarm.01",
  "stinger.checkpoint.00",
  "stinger.checkpoint.01",
  "stinger.level-start.00",
  "stinger.level-start.01",
  "stinger.lose.00",
  "stinger.lose.01",
  "stinger.win.00",
  "stinger.win.01",
  "ui.back.00",
  "ui.back.01",
  "ui.click.00",
  "ui.click.01",
  "ui.confirm.00",
  "ui.confirm.01",
  "ui.countdown-go.00",
  "ui.countdown-go.01",
  "ui.countdown-tick.00",
  "ui.countdown-tick.01",
  "ui.error.00",
  "ui.error.01",
  "ui.hover.00",
  "ui.hover.01",
  "ui.reward.00",
  "ui.reward.01",
  "ui.score-tick.00",
  "ui.score-tick.01",
  "ui.slider-tick.00",
  "ui.slider-tick.01",
  "ui.toggle.00",
  "ui.toggle.01",
  "ui.unlock.00",
  "ui.unlock.01",
  "vehicle.boost",
  "vehicle.car-small.layer0.off",
  "vehicle.car-small.layer0.on",
  "vehicle.car-small.layer1.off",
  "vehicle.car-small.layer1.on",
  "vehicle.car-small.layer2.off",
  "vehicle.car-small.layer2.on",
  "vehicle.car-sport-real",
  "vehicle.car-sport.layer0.off",
  "vehicle.car-sport.layer0.on",
  "vehicle.car-sport.layer1.off",
  "vehicle.car-sport.layer1.on",
  "vehicle.car-sport.layer2.off",
  "vehicle.car-sport.layer2.on",
  "vehicle.gear-shift",
  "vehicle.gear-shift.01",
  "vehicle.jet.layer0.off",
  "vehicle.jet.layer0.on",
  "vehicle.jet.layer1.off",
  "vehicle.jet.layer1.on",
  "vehicle.jet.layer2.off",
  "vehicle.jet.layer2.on",
  "vehicle.prop-plane.layer0.off",
  "vehicle.prop-plane.layer0.on",
  "vehicle.prop-plane.layer1.off",
  "vehicle.prop-plane.layer1.on",
  "vehicle.prop-plane.layer2.off",
  "vehicle.prop-plane.layer2.on",
  "vehicle.thruster.layer0.off",
  "vehicle.thruster.layer0.on",
  "vehicle.thruster.layer1.off",
  "vehicle.thruster.layer1.on",
  "vehicle.thruster.layer2.off",
  "vehicle.thruster.layer2.on",
  "vehicle.thruster.layer3.off",
  "vehicle.thruster.layer3.on",
  "vehicle.tyre-skid",
  "vehicle.van-real",
  "vehicle.van.layer0.off",
  "vehicle.van.layer0.on",
  "vehicle.van.layer1.off",
  "vehicle.van.layer1.on",
  "vehicle.van.layer2.off",
  "vehicle.van.layer2.on",
  "whoosh.dash.00",
  "whoosh.dash.01",
  "whoosh.dash.02",
  "whoosh.pass-by-large.00",
  "whoosh.pass-by-large.01",
  "whoosh.pass-by-large.02",
  "whoosh.pass-by-small.00",
  "whoosh.pass-by-small.01",
  "whoosh.pass-by-small.02",
  "whoosh.swing-heavy.00",
  "whoosh.swing-heavy.01",
  "whoosh.swing-heavy.02",
  "whoosh.swing-light.00",
  "whoosh.swing-light.01",
  "whoosh.swing-light.02"
] as const;
export type SfxId = (typeof SFX_IDS)[number];
export type SfxPack = typeof sfx;

/** Base route for the shared pack, served by the public/packs symlink. */
export const SFX_PACK_BASE = "/packs/game-sfx-core";

/** URL for a pack id in a given encoding (`opus.webm` | `m4a`), or with the
 * `{format}` placeholder the GameSoundEngine resolves via its format probe. */
export const sfxUrl = (id: SfxId | string, ext: "opus.webm" | "m4a" | "{format}" = "{format}"): string =>
  `${SFX_PACK_BASE}/${id}.${ext}`;

/** AudioAssetRef-compatible object for a pack id (probed-encoding url + sample provenance). */
export const sfxAsset = (id: SfxId | string) => ({
  url: sfxUrl(id),
  provenance: "sample" as const
});
