import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/**
 * End-to-end coverage for the two vehicle-admission fixture cases the brief names that had none.
 *
 * ## Why these two needed real GLB files
 *
 * `asset-role-admission.test.ts` covers seven of the brief's nine admission cases by handing
 * `admitAssetForRole` injected facts. That is the right level for reasoning: "does a wheelless shell get
 * rejected for hero use and admitted as background". It cannot cover these two, because they are not about
 * how admission reasons over facts -- they are about whether the **auditor derives the right facts from a
 * real file**:
 *
 *  1. **transformed child wheel nodes.** `turboRaceCar` carries a four-level Sketchfab hierarchy. An
 *     auditor reading local translations instead of composed world transforms would stack all four wheels
 *     at the origin, count one corner, and reject a valid hero vehicle. Injected facts would hide that
 *     entirely, since the bug is in producing the numbers.
 *  2. **multi-material wheel meshes.** Real wheels are authored as a tyre plus a rim on separate
 *     materials. An auditor counting primitives rather than mesh nodes would see eight half-wheels
 *     spread across eight "corners" and reject the asset.
 *
 * Fixtures are generated by `tools/asset-geometry-audit/make-admission-fixtures.mjs` and committed, so
 * this suite reads real bytes rather than a mock of them.
 */
const AUDITOR = "tools/asset-geometry-audit/wheel-detect.mjs";
const TRANSFORMED = "tests/fixtures/gltf-multipart/transformed-child-wheels.glb";
const MULTI_MATERIAL = "tests/fixtures/gltf-multipart/multi-material-wheels.glb";

/**
 * Run the auditor and return stdout.
 *
 * The auditor **exits non-zero when it rejects an asset**, which is correct for a gate invoked from a
 * shell but makes `execFileSync` throw. These fixtures are deliberately rejected for hero use (60 and 108
 * triangles), so a non-zero exit is the expected path and its stdout is the evidence under test.
 */
function audit(fixture: string): string {
  try {
    return execFileSync("node", [AUDITOR, fixture], { encoding: "utf8", maxBuffer: 8 * 1024 * 1024 });
  } catch (error) {
    const stdout = (error as { stdout?: string | Buffer }).stdout;
    if (stdout === undefined) throw error;
    return typeof stdout === "string" ? stdout : stdout.toString("utf8");
  }
}

function parseCounts(output: string): { readonly parts: number; readonly candidates: number; readonly corners: number } {
  const match = /parts=(\d+) wheelCandidates=(\d+) corners=(\d+)/.exec(output);
  if (!match) throw new Error(`auditor output did not report counts:\n${output}`);
  return { parts: Number(match[1]), candidates: Number(match[2]), corners: Number(match[3]) };
}

describe("vehicle admission derives wheel facts from real multi-part GLB files", () => {
  it("has both fixtures committed", () => {
    // A generated-but-uncommitted fixture makes this suite pass locally and fail everywhere else.
    expect(existsSync(TRANSFORMED), TRANSFORMED).toBe(true);
    expect(existsSync(MULTI_MATERIAL), MULTI_MATERIAL).toBe(true);
  });

  it("composes a parent chain to place wheels at four distinct corners", () => {
    /*
     * The load-bearing assertion. Every wheel mesh in this fixture is centred on its own origin and its
     * world position exists only after composing root -> axleGroup -> hub -> wheel, with each level
     * contributing part of the offset. Reading local transforms yields four wheels at one point.
     */
    const counts = parseCounts(audit(TRANSFORMED));
    expect(counts.parts).toBe(5);
    expect(counts.candidates, "four wheel-like parts").toBe(4);
    expect(counts.corners, "four distinct outboard corners").toBe(4);
  });

  it("treats a two-material wheel as one wheel, not two partial ones", () => {
    /*
     * Each wheel here is one mesh with two primitives (tyre + rim) on different materials. Counting
     * primitives would report eight candidates; counting mesh nodes reports four.
     */
    const counts = parseCounts(audit(MULTI_MATERIAL));
    expect(counts.parts).toBe(5);
    expect(counts.candidates, "four wheels despite eight primitives").toBe(4);
    expect(counts.corners).toBe(4);
  });

  it("reports wheels as visible outside the body silhouette for both fixtures", () => {
    // Both fixtures place wheels outboard of the bodywork, so the auditor must not call them enclosed.
    for (const fixture of [TRANSFORMED, MULTI_MATERIAL]) {
      const output = audit(fixture);
      expect(output, fixture).toContain("WHEELS-VISIBLE");
      expect(output, `${fixture} must not be reported as enclosed`).not.toContain("wheels are enclosed inside the bodywork");
    }
  });

  it("still refuses hero admission on triangle budget, and says so", () => {
    /*
     * These fixtures are 60 and 108 triangles: geometrically correct wheels on a box body. Admission must
     * reject them for hero use on the triangle floor while having *correctly measured* the wheels -- proving
     * the wheel checks and the budget check are independent rather than one masking the other.
     */
    for (const fixture of [TRANSFORMED, MULTI_MATERIAL]) {
      const output = audit(fixture);
      expect(output, fixture).toContain("triangle-floor");
      expect(output, `${fixture} wheel geometry must not be the reason`).not.toContain("this is a body shell with no wheels modelled");
    }
  });

  it("keeps rendered wheel visibility unproven, because geometry cannot prove it", () => {
    // The distinction the brief insists on: wheel geometry existing is not a viewer seeing tyres.
    for (const fixture of [TRANSFORMED, MULTI_MATERIAL]) {
      expect(audit(fixture), fixture).toContain("rendered-wheel-visibility");
    }
  });

  it("is deterministic across repeated audits", () => {
    // Admission output is retained evidence, so identical bytes must yield an identical verdict.
    for (const fixture of [TRANSFORMED, MULTI_MATERIAL]) {
      expect(audit(fixture), fixture).toBe(audit(fixture));
    }
  });

  it("distinguishes these from the renderer fixture, which is deliberately not wheel-shaped", () => {
    /*
     * `body-and-four-wheels.glb` exists to prove *draw* behaviour and uses cubes, which a geometry auditor
     * correctly refuses to call wheels. Asserting that keeps the two fixture purposes from being conflated
     * later -- and documents that NO-WHEELS on that file is correct, not a detector failure.
     */
    const output = audit("tests/fixtures/gltf-multipart/body-and-four-wheels.glb");
    expect(output).toContain("NO-WHEELS");
    expect(parseCounts(output).candidates).toBe(0);
  });

  it("regenerates byte-identically from its generator", () => {
    /*
     * A committed binary fixture nobody can reproduce becomes unmaintainable. Re-running the generator must
     * reproduce the exact bytes, so a future change to proportions is a visible diff rather than a mystery.
     */
    const before = [TRANSFORMED, MULTI_MATERIAL].map((path) => readFileSync(path));
    execFileSync("node", ["tools/asset-geometry-audit/make-admission-fixtures.mjs"], { encoding: "utf8" });
    const after = [TRANSFORMED, MULTI_MATERIAL].map((path) => readFileSync(path));
    expect(after[0]!.equals(before[0]!), TRANSFORMED).toBe(true);
    expect(after[1]!.equals(before[1]!), MULTI_MATERIAL).toBe(true);
  });
});
