import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { artifact, newRunId, sourceIdentity, validateReceipt, writeImmutableJson, type Artifact, type ProducerReceipt } from '../muse3jsparity-readiness/evidence-lineage';
import { loadMuse301ExecutionRequirements } from '../muse3jsparity-readiness/requirements';

interface L02Input {
  schema:'muse301-l02-input/v1';
  visualManifest:Artifact; humanApproval:Artifact; registry:Artifact; deployment:Artifact; github:Artifact;
  releaseSequence:Artifact; reportRegeneration:Artifact; registryConsumer:Artifact; marketing:Artifact; finalClaims:Artifact; cleanup:Artifact;
  evidence:Artifact[]; packages?:Artifact[]; tarballs?:Artifact[];
  testProofs?:Record<string,{report:string;testFile:string;testTitle:string;projectName?:string}>;
}
const root=process.cwd(),inputPath=process.argv[2],outputDir=process.argv[3];
if(!inputPath||!outputDir)throw new Error('Usage: l02-producer.ts <input.json> <tests/reports/task-dir>');
const out=relative(root,resolve(root,outputDir));if(out.startsWith('..')||!out.startsWith('tests/reports/'))throw new Error('L02 output must remain under tests/reports');mkdirSync(resolve(root,out),{recursive:true});
const input=JSON.parse(readFileSync(resolve(root,inputPath),'utf8')) as L02Input;if(input.schema!=='muse301-l02-input/v1')throw new Error('Invalid L02 input schema');
const source=sourceIdentity(root),startedAt=new Date().toISOString();
const initial=[input.visualManifest,input.humanApproval,input.registry,input.deployment,input.github,input.releaseSequence,input.reportRegeneration,input.registryConsumer,input.marketing,input.finalClaims,input.cleanup,...(input.evidence??[]),...(input.packages??[]),...(input.tarballs??[])];
const refs=new Map<string,Artifact>();
const add=(ref:Artifact)=>{if(!ref?.path||!ref.sha256)return;const actual=artifact(root,ref.path);if(actual.sha256!==ref.sha256)throw new Error(`Changed L02 input ${ref.path}`);const prior=refs.get(ref.path);if(prior&&prior.sha256!==ref.sha256)throw new Error(`Conflicting L02 input ${ref.path}`);refs.set(ref.path,ref);};
for(const ref of initial)add(ref);
// Expand every JSON reference so the parent receipt explicitly binds the full replay closure.
for(const ref of [...refs.values()]){if(!ref.path.endsWith('.json'))continue;let value:unknown;try{value=JSON.parse(readFileSync(resolve(root,ref.path),'utf8'));}catch{continue;}const visit=(node:unknown)=>{if(!node||typeof node!=='object')return;const record=node as Record<string,unknown>;if(typeof record.path==='string'&&typeof record.sha256==='string')try{add(record as unknown as Artifact);}catch(error){throw error;}for(const child of Object.values(record))visit(child);};visit(value);}
const acceptancePath=`${out}/release-acceptance.json`;
writeFileSync(resolve(root,acceptancePath),JSON.stringify({schema:'muse301-release/v1',version:'3.0.1',tag:'v3.0.1',tagCommit:source.commit,visualManifest:input.visualManifest,humanApproval:input.humanApproval,registry:input.registry,deployment:input.deployment,github:input.github},null,2)+'\n',{flag:'wx'});add(artifact(root,acceptancePath));
const requirements=loadMuse301ExecutionRequirements(root).filter(item=>(item.proofGates??item.gates).includes('l02'));
const tasks=requirements.map(item=>item.id),acceptanceTasks=requirements.filter(item=>item.acceptance).map(item=>item.id),sequenceTasks=requirements.filter(item=>item.releaseSequenceAcceptance?.mode==='release').map(item=>item.id),registryTasks=requirements.filter(item=>item.registryConsumerAcceptance).map(item=>item.id),marketingTasks=requirements.filter(item=>item.marketingAcceptance).map(item=>item.id),claimsTasks=requirements.filter(item=>item.finalClaimsAcceptance).map(item=>item.id),regenerationTasks=requirements.filter(item=>item.reportRegenerationAcceptance).map(item=>item.id),cleanupTasks=requirements.filter(item=>item.cleanupAcceptance).map(item=>item.id);
const proofs=requirements.filter(item=>item.tests.length>0).map(item=>{const proof=input.testProofs?.[item.id];if(!proof)throw new Error(`Missing L02 test proof ${item.id}`);return{task:item.id,...proof};});
const receiptPath=`${out}/l02.receipt.json`,endedAt=new Date().toISOString();
const receipt:ProducerReceipt={schema:'muse3jsparity-producer/v1',runId:newRunId(),gate:'l02',tasks,command:['pnpm','exec','tsx','--tsconfig','tsconfig.base.json','tools/release/l02-producer.ts',inputPath,outputDir],cwd:root,exitCode:0,startedAt,endedAt,source,claimSurface:'release tooling',environment:{browser:'post-release evidence closure',backend:'registry, GitHub, Vercel, and canonical replay',hardware:'release coordinator'},artifacts:[...refs.values()],packages:input.packages??[],tarballs:input.tarballs??[],acceptance:acceptancePath,acceptanceProofs:acceptanceTasks.map(task=>({task,artifact:acceptancePath,schema:'muse301-release/v1'})),releaseSequenceProofs:sequenceTasks.map(task=>({task,artifact:input.releaseSequence,mode:'release'})),registryConsumerProofs:registryTasks.map(task=>({task,artifact:input.registryConsumer})),marketingProofs:marketingTasks.map(task=>({task,artifact:input.marketing})),finalClaimsProofs:claimsTasks.map(task=>({task,artifact:input.finalClaims.path})),reportRegenerationProofs:regenerationTasks.map(task=>({task,artifact:input.reportRegeneration})),cleanupProofs:cleanupTasks.map(task=>({task,artifact:input.cleanup.path})),proofs};
const written=writeImmutableJson(resolve(root,receiptPath),receipt),reference={...written,path:receiptPath};
const expected={source,gate:'l02',tasks,now:Date.now(),taskTests:Object.fromEntries(requirements.map(item=>[item.id,item.tests])),taskAssertions:Object.fromEntries(requirements.filter(item=>item.assertions).map(item=>[item.id,item.assertions!])),taskAcceptance:Object.fromEntries(requirements.filter(item=>item.acceptance).map(item=>[item.id,item.acceptance!])),taskReleaseSequences:Object.fromEntries(requirements.filter(item=>item.releaseSequenceAcceptance).map(item=>[item.id,item.releaseSequenceAcceptance!])),taskRegistryConsumers:Object.fromEntries(requirements.filter(item=>item.registryConsumerAcceptance).map(item=>[item.id,item.registryConsumerAcceptance!])),taskMarketing:Object.fromEntries(requirements.filter(item=>item.marketingAcceptance).map(item=>[item.id,item.marketingAcceptance!])),taskFinalClaims:Object.fromEntries(requirements.filter(item=>item.finalClaimsAcceptance).map(item=>[item.id,item.finalClaimsAcceptance!])),taskReportRegeneration:Object.fromEntries(requirements.filter(item=>item.reportRegenerationAcceptance).map(item=>[item.id,item.reportRegenerationAcceptance!])),taskCleanup:Object.fromEntries(requirements.filter(item=>item.cleanupAcceptance).map(item=>[item.id,item.cleanupAcceptance!]))};
const validation=validateReceipt(root,reference,expected);writeImmutableJson(resolve(root,`${out}/validation.json`),{...validation,receipt:reference,source});console.log(JSON.stringify({receipt:reference,valid:validation.valid,errors:validation.errors}));if(!validation.valid)process.exitCode=1;
