import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {optionalPeerFixture,validateOptionalPeerObservation} from './optional-peer-fixture.mjs';
function execute(mode,source){const root=mkdtempSync(join(tmpdir(),'peer-probe-test-'));try{mkdirSync(join(root,'node_modules/@aura3d/engine'),{recursive:true});writeFileSync(join(root,'node_modules/@aura3d/engine/package.json'),JSON.stringify({type:'module',exports:'./index.js'}));writeFileSync(join(root,'node_modules/@aura3d/engine/index.js'),source);if(mode==='present'){mkdirSync(join(root,'node_modules/@aura3d/navigation-recast'),{recursive:true});writeFileSync(join(root,'node_modules/@aura3d/navigation-recast/package.json'),JSON.stringify({type:'module',exports:'./index.js'}));writeFileSync(join(root,'node_modules/@aura3d/navigation-recast/index.js'),'export {};');}writeFileSync(join(root,'probe.mjs'),optionalPeerFixture(mode));const command=spawnSync(process.execPath,['probe.mjs'],{cwd:root,encoding:'utf8'});return {status:command.status,error:command.stderr,observation:command.status===0?JSON.parse(readFileSync(join(root,'optional-peer-result.json'))):null};}finally{rmSync(root,{recursive:true,force:true})}}
test('absence probe distinguishes expected rejection from silently succeeding navigation',()=>{const good=execute('absent',"export function createAuraApp(){};export const navigation={isAvailable:async()=>false,bake:async()=>{throw new Error('navigation peer unavailable')}};");assert.equal(good.status,0,good.error);validateOptionalPeerObservation(good.observation,'absent');const bad=execute('absent',"export function createAuraApp(){};export const navigation={isAvailable:async()=>false,bake:async()=>({})};");assert.notEqual(bad.status,0)});
test('present probe requires actual successful path and disposal assertions',()=>{const source="export function createAuraApp(){};export const navigation={isAvailable:async()=>true,bake:async()=>({disposed:false,dispose(){this.disposed=true}}),path:()=>({success:true,points:[[0,0,0],[1,0,1]]})};";const good=execute('present',source);assert.equal(good.status,0,good.error);validateOptionalPeerObservation(good.observation,'present');assert.notEqual(execute('present',source.replace('success:true','success:false')).status,0);assert.notEqual(execute('present',source.replace('this.disposed=true','')).status,0)});
