import { defineAuraAssets } from "@aura3d/engine";
import { AURAVOICE_AURA3D_PROMPT_ANIMATION_CONTRACT_ID } from "./contract";

export const assetContractId = AURAVOICE_AURA3D_PROMPT_ANIMATION_CONTRACT_ID;

export const animationStudioRequiredAssetKeys = ["miko", "luma", "moonGarden"] as const;

export const animationStudioOptionalAudioAssetKeys = [
  "mikoDialogueStem",
  "lumaDialogueStem",
  "moonGardenMusic",
  "moonGardenChimeSfx"
] as const;

export const assets = defineAuraAssets({
  miko: {
    type: "model",
    format: "glb",
    url: "/aura-assets/miko.catalog.glb",
    bounds: [1.015, 1.95, 0.369],
    hash: "sha256-fcdc2b7502031e556259dfe942fdfbd7abe41963433f2046ed2522d27bce9d65",
    metadata: {
      contractId: assetContractId,
      role: "animation-character",
      license: "CC0-1.0",
      attribution: "Miko — Aura3D-authored CC0 procedural humanoid",
      source:
        "Aura3D-authored rigged GLB generated by scripts/build-characters.ts (CC0). Full 21-joint humanoid rig (hips→spine→chest→neck→head, both arms with forearms+hands, both legs with lower-legs+feet+toes; graded-A) with embedded Idle/Wave/Walk/Talk clips and a facial mouthOpen blendshape morph target for lip-sync. Now ships a real UV-mapped 1024×1024 base-colour bitmap texture (skin tone gradients + cheek blush, woven clothing fabric, brushed accent trim, eye/iris falloff, edge ambient occlusion) instead of flat vertex colours.",
      animationClips: ["Idle", "Wave", "Walk", "Talk"],
      // Authored rig ships a real face morph (mouthOpen), so lip-sync drives a
      // blendshape rather than the primitive mouth-card fallback.
      mouthReadiness: "blendshape",
      mouthMorphTargets: ["mouthOpen"]
    }
  },
  luma: {
    type: "model",
    format: "glb",
    url: "/aura-assets/luma2.catalog.glb",
    bounds: [0.99, 1.95, 0.333],
    hash: "sha256-911c60a074f6d89d0eaeefc1f1eecf4188873880b62aa11b3d02ec2c18a4e036",
    metadata: {
      contractId: assetContractId,
      role: "animation-character",
      license: "CC0-1.0",
      attribution: "Luma — Aura3D-authored CC0 procedural humanoid",
      source:
        "Aura3D-authored rigged GLB generated by scripts/build-characters.ts (CC0). A warm-gold helper that matches Miko's style (coherent cast). Full 21-joint humanoid rig (graded-A) with embedded Idle/Wave/Walk/Talk clips and a facial mouthOpen blendshape morph target. Now ships a real UV-mapped 1024×1024 base-colour bitmap texture (skin tone gradients + cheek blush, woven clothing fabric, brushed accent trim, eye/iris falloff, edge ambient occlusion) instead of flat vertex colours.",
      animationClips: ["Idle", "Wave", "Walk", "Talk"],
      // Authored rig ships a real face morph (mouthOpen), so lip-sync drives a
      // blendshape rather than the primitive mouth-card fallback.
      mouthReadiness: "blendshape",
      mouthMorphTargets: ["mouthOpen"]
    }
  },
  moonGarden: {
    type: "model",
    format: "gltf",
    url: "/aura-assets/moonGarden.gltf",
    bounds: [3.2, 0.6, 1.2],
    hash: "sha256-b7b50e37cc4319df21fa2a598aab9e055d54eeb3f5511a3b3f0d4f6c5101c456",
    metadata: {
      contractId: assetContractId,
      role: "animation-set",
      license: "MIT",
      source: "Aura3D animation-studio local generated starter set anchor",
      walkable: true,
      framingReady: true
    }
  }
} as const);
