"""Build deterministic, route-local Pulse Tunnel V6 art candidates.

This pass establishes one Pulse-specific visual language across the runner,
terminal sentinel, and reactor tunnel: black ceramic shells, cool silver wear,
cyan player cadence, and ember-red terminal threat.  The procedural PNGs are
fixed byte streams generated by this script and embedded in the exported GLBs.
The public asset manifest is deliberately not touched here.
"""

from pathlib import Path
import hashlib
import importlib.util
import json
import math
import struct
import zlib

import bpy
from mathutils import Vector


ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "art-review" / "assets" / "texture-identity-v6"
TEXTURES = OUT / "textures"
OUT.mkdir(parents=True, exist_ok=True)
TEXTURES.mkdir(parents=True, exist_ok=True)

helper_path = Path(__file__).with_name("build-high-fidelity-v5.py")
spec = importlib.util.spec_from_file_location("pulse_v5_helpers", helper_path)
helpers = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(helpers)
helpers.OUT = OUT

reset = helpers.reset
assign = helpers.assign
box = helpers.box
cylinder = helpers.cylinder
torus = helpers.torus
prism = helpers.prism
loft = helpers.loft


def stable_export(filename):
    """Write a canonical GLB without Blender export-order nondeterminism."""
    objects = sorted((obj for obj in bpy.context.scene.objects if obj.type == "MESH"), key=lambda obj: obj.name)
    material_names = sorted({obj.data.materials[0].name for obj in objects if obj.data.materials})
    material_index = {name: index for index, name in enumerate(material_names)}
    binary = bytearray()
    buffer_views = []
    accessors = []

    def align():
        binary.extend(b"\0" * ((4 - len(binary) % 4) % 4))

    def add_view(payload, target=None):
        align()
        offset = len(binary)
        binary.extend(payload)
        view = {"buffer": 0, "byteOffset": offset, "byteLength": len(payload)}
        if target is not None:
            view["target"] = target
        buffer_views.append(view)
        return len(buffer_views) - 1

    def add_accessor(values, kind, component_type, target, minimum=None, maximum=None):
        if component_type == 5126:
            payload = struct.pack("<" + "f" * len(values), *values)
            width = {"VEC2": 2, "VEC3": 3}[kind]
        elif component_type == 5125:
            payload = struct.pack("<" + "I" * len(values), *values)
            width = 1
        else:
            raise ValueError(component_type)
        accessor = {
            "bufferView": add_view(payload, target),
            "componentType": component_type,
            "count": len(values) // width,
            "type": kind,
        }
        if minimum is not None:
            accessor["min"] = minimum
        if maximum is not None:
            accessor["max"] = maximum
        accessors.append(accessor)
        return len(accessors) - 1

    meshes = []
    nodes = []
    for obj in objects:
        mesh = obj.data
        mesh.calc_loop_triangles()
        normal_matrix = obj.matrix_world.to_3x3().inverted().transposed()
        uv_layer = mesh.uv_layers.active.data if mesh.uv_layers.active else None
        positions = []
        normals = []
        texcoords = []
        indices = []
        for triangle in mesh.loop_triangles:
            for loop_index in triangle.loops:
                loop = mesh.loops[loop_index]
                world_position = obj.matrix_world @ mesh.vertices[loop.vertex_index].co
                world_normal = (normal_matrix @ loop.normal).normalized()
                # 1e-3 is far below a display pixel at the review camera and
                # absorbs Blender bevel/normal evaluator ulp drift completely.
                position = [round(float(value), 3) for value in world_position]
                normal = [round(float(value), 3) for value in world_normal]
                positions.extend(0.0 if value == 0 else value for value in position)
                normals.extend(0.0 if value == 0 else value for value in normal)
                if uv_layer is not None:
                    uv = uv_layer[loop_index].uv
                    u, v = round(float(uv.x), 3), round(float(uv.y), 3)
                else:
                    # Stable world-planar UVs ensure authored panel textures also
                    # cover lofted and prism surfaces with no exporter synthesis.
                    u = round((position[0] * 0.36) % 1.0, 3)
                    v = round((position[2] * 0.36 + position[1] * 0.12) % 1.0, 3)
                texcoords.extend((u, v))
                indices.append(len(indices))
        if not indices:
            continue
        triples = list(zip(positions[0::3], positions[1::3], positions[2::3]))
        minimum = [min(entry[axis] for entry in triples) for axis in range(3)]
        maximum = [max(entry[axis] for entry in triples) for axis in range(3)]
        attributes = {
            "POSITION": add_accessor(positions, "VEC3", 5126, 34962, minimum, maximum),
            "NORMAL": add_accessor(normals, "VEC3", 5126, 34962),
            "TEXCOORD_0": add_accessor(texcoords, "VEC2", 5126, 34962),
        }
        primitive = {
            "attributes": attributes,
            "indices": add_accessor(indices, "SCALAR", 5125, 34963, [0], [len(indices) - 1]),
            "mode": 4,
        }
        if obj.data.materials:
            primitive["material"] = material_index[obj.data.materials[0].name]
        meshes.append({"name": obj.name, "primitives": [primitive]})
        nodes.append({"name": obj.name, "mesh": len(meshes) - 1})

    texture_for_material = {
        "runner micro-panel black ceramic": TEXTURES / "runner-panel.png",
        "sentinel deterministic threat chevrons": TEXTURES / "sentinel-chevron.png",
        "reactor deterministic deck plating": TEXTURES / "reactor-deck.png",
    }
    images = []
    textures = []
    image_index_by_path = {}
    gltf_materials = []
    uses_emissive_strength = False
    for name in material_names:
        value = bpy.data.materials[name]
        bsdf = value.node_tree.nodes.get("Principled BSDF")
        base = list(bsdf.inputs["Base Color"].default_value)
        pbr = {
            "baseColorFactor": [round(float(channel), 6) for channel in base],
            "metallicFactor": round(float(bsdf.inputs["Metallic"].default_value), 6),
            "roughnessFactor": round(float(bsdf.inputs["Roughness"].default_value), 6),
        }
        if name in texture_for_material:
            image_path = texture_for_material[name]
            key = image_path.as_posix()
            if key not in image_index_by_path:
                image_view = add_view(image_path.read_bytes())
                image_index_by_path[key] = len(images)
                images.append({"name": image_path.stem, "bufferView": image_view, "mimeType": "image/png"})
                textures.append({"source": len(images) - 1, "sampler": 0})
            pbr["baseColorTexture"] = {"index": image_index_by_path[key]}
        gltf_material = {"name": name, "doubleSided": True, "pbrMetallicRoughness": pbr}
        emission_key = "Emission Color" if "Emission Color" in bsdf.inputs else "Emission"
        emission = list(bsdf.inputs[emission_key].default_value)[:3]
        strength = float(bsdf.inputs["Emission Strength"].default_value)
        if strength > 0 and max(emission) > 0:
            gltf_material["emissiveFactor"] = [round(float(channel), 6) for channel in emission]
            if strength != 1.0:
                gltf_material["extensions"] = {"KHR_materials_emissive_strength": {"emissiveStrength": round(strength, 6)}}
                uses_emissive_strength = True
        gltf_materials.append(gltf_material)

    align()
    document = {
        "asset": {"generator": "Aura3D Pulse canonical GLB writer 1", "version": "2.0"},
        "accessors": accessors,
        "bufferViews": buffer_views,
        "buffers": [{"byteLength": len(binary)}],
        "materials": gltf_materials,
        "meshes": meshes,
        "nodes": nodes,
        "samplers": [{"magFilter": 9728, "minFilter": 9984, "wrapS": 10497, "wrapT": 10497}],
        "scene": 0,
        "scenes": [{"name": "Pulse Tunnel V6 candidate", "nodes": list(range(len(nodes)))}],
    }
    if images:
        document["images"] = images
        document["textures"] = textures
    if uses_emissive_strength:
        document["extensionsUsed"] = ["KHR_materials_emissive_strength"]
    json_bytes = json.dumps(document, sort_keys=True, separators=(",", ":")).encode("utf8")
    json_bytes += b" " * ((4 - len(json_bytes) % 4) % 4)
    binary += b"\0" * ((4 - len(binary) % 4) % 4)
    total = 12 + 8 + len(json_bytes) + 8 + len(binary)
    payload = struct.pack("<4sII", b"glTF", 2, total)
    payload += struct.pack("<II", len(json_bytes), 0x4E4F534A) + json_bytes
    payload += struct.pack("<II", len(binary), 0x004E4942) + bytes(binary)
    (OUT / filename).write_bytes(payload)


def sphere(name, location, scale, mat, segments=48, rings=24):
    """Deterministic UV sphere; Blender's operator rotates ring phases across runs."""
    vertices = [(location[0], location[1] + scale[1], location[2])]
    for ring in range(1, rings):
        phi = math.pi * ring / rings
        for segment in range(segments):
            theta = math.tau * segment / segments
            vertices.append((
                location[0] + math.sin(phi) * math.cos(theta) * scale[0],
                location[1] + math.cos(phi) * scale[1],
                location[2] + math.sin(phi) * math.sin(theta) * scale[2],
            ))
    bottom = len(vertices)
    vertices.append((location[0], location[1] - scale[1], location[2]))
    faces = []
    for segment in range(segments):
        nxt = (segment + 1) % segments
        faces.append((0, 1 + nxt, 1 + segment))
    for ring in range(rings - 2):
        start = 1 + ring * segments
        following = start + segments
        for segment in range(segments):
            nxt = (segment + 1) % segments
            faces.append((start + segment, start + nxt, following + nxt, following + segment))
    last = 1 + (rings - 2) * segments
    for segment in range(segments):
        nxt = (segment + 1) % segments
        faces.append((last + segment, last + nxt, bottom))
    mesh = bpy.data.meshes.new(name + " deterministic mesh")
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    assign(obj, mat, True)
    return obj


def curve_tube(name, points, radius, mat, cyclic=False):
    """Fixed segmented tube using the deterministic sphere joints above."""
    path = list(points)
    if cyclic:
        path.append(path[0])
    built = []
    for index, (start, end) in enumerate(zip(path, path[1:])):
        start_vector = Vector(start)
        end_vector = Vector(end)
        delta = end_vector - start_vector
        midpoint = (start_vector + end_vector) * 0.5
        rotation = delta.to_track_quat("Z", "Y").to_euler()
        built.append(cylinder(f"{name} segment {index}", midpoint, radius, delta.length, mat,
                              rotation, 24, 0.0))
    for index, point in enumerate(path[1:-1]):
        built.append(sphere(f"{name} joint {index}", point, (radius, radius, radius), mat, 24, 12))
    return built


def png(path, width, height, pixel):
    """Write a deterministic RGBA PNG using only fixed stdlib transforms."""
    signature = b"\x89PNG\r\n\x1a\n"

    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)

    rows = bytearray()
    for y in range(height):
        rows.append(0)
        for x in range(width):
            rows.extend(pixel(x, y))
    encoded = signature
    encoded += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    encoded += chunk(b"IDAT", zlib.compress(bytes(rows), 9))
    encoded += chunk(b"IEND", b"")
    path.write_bytes(encoded)


def make_textures():
    def runner_pixel(x, y):
        seam = x % 24 in (0, 1) or y % 24 in (0, 1)
        slash = (x + y * 2) % 31 in (0, 1)
        rivet = (x % 24, y % 24) in ((4, 4), (19, 4), (4, 19), (19, 19))
        if rivet:
            return (102, 236, 248, 255)
        if seam:
            return (8, 27, 35, 255)
        if slash:
            return (42, 72, 78, 255)
        grain = ((x * 17 + y * 29) % 9) - 4
        return (31 + grain, 51 + grain, 57 + grain, 255)

    def threat_pixel(x, y):
        chevron = abs((x % 32) - 16) == (y % 16) or abs((x % 32) - 16) == 15 - (y % 16)
        seam = x % 32 in (0, 1) or y % 32 in (0, 1)
        if chevron:
            return (210, 46, 34, 255)
        if seam:
            return (31, 6, 9, 255)
        grain = ((x * 13 + y * 7) % 11) - 5
        return (65 + grain, 20 + grain // 2, 23 + grain // 2, 255)

    def deck_pixel(x, y):
        lane = x % 32 in (0, 1, 30, 31)
        joint = y % 48 in (0, 1)
        stipple = (x * 11 + y * 19) % 53 == 0
        if lane:
            return (20, 101, 112, 255)
        if joint:
            return (8, 19, 27, 255)
        if stipple:
            return (75, 91, 96, 255)
        grain = ((x * 5 + y * 3) % 13) - 6
        return (32 + grain, 43 + grain, 50 + grain, 255)

    png(TEXTURES / "runner-panel.png", 96, 96, runner_pixel)
    png(TEXTURES / "sentinel-chevron.png", 96, 96, threat_pixel)
    png(TEXTURES / "reactor-deck.png", 128, 128, deck_pixel)


def material(name, color, metallic, roughness, emission=None, strength=0.0, texture=None):
    value = bpy.data.materials.new(name)
    value.diffuse_color = (*color, 1.0)
    value.use_nodes = True
    tree = value.node_tree
    bsdf = tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    if emission:
        key = "Emission Color" if "Emission Color" in bsdf.inputs else "Emission"
        bsdf.inputs[key].default_value = (*emission, 1.0)
        bsdf.inputs["Emission Strength"].default_value = strength
    if texture:
        image = bpy.data.images.load(str(TEXTURES / texture), check_existing=False)
        image.name = name + " deterministic texture"
        image.colorspace_settings.name = "sRGB"
        node = tree.nodes.new("ShaderNodeTexImage")
        node.name = name + " fixed image"
        node.image = image
        node.interpolation = "Closest"
        tree.links.new(node.outputs["Color"], bsdf.inputs["Base Color"])
    return value


def build_runner():
    reset()
    shell = material("runner micro-panel black ceramic", (0.06, 0.10, 0.12), 0.62, 0.27, texture="runner-panel.png")
    graphite = material("runner graphite flight frame", (0.012, 0.021, 0.03), 0.86, 0.23)
    silver = material("runner cool worn edge", (0.34, 0.40, 0.41), 0.88, 0.24)
    cyan = material("runner cyan phase glass", (0.01, 0.17, 0.20), 0.28, 0.13, (0.0, 0.82, 1.0), 3.7)
    white = material("runner white cadence stencil", (0.68, 0.78, 0.78), 0.34, 0.38)

    # A compact forked arrowhead rather than a generic car or pod.
    loft(
        "runner central phase lance",
        [
            (-1.95, 0.04, 0.04, 0.30), (-1.72, 0.20, 0.12, 0.30),
            (-1.18, 0.43, 0.25, 0.31), (-0.42, 0.52, 0.31, 0.31),
            (0.32, 0.47, 0.27, 0.28), (1.06, 0.30, 0.18, 0.23),
            (1.52, 0.14, 0.10, 0.20), (1.75, 0.04, 0.04, 0.18),
        ], 28, shell, subdivision=0,
    )
    loft(
        "runner luminous keel",
        [(-1.56, 0.08, 0.05, 0.09), (-0.82, 0.19, 0.10, 0.08),
         (0.18, 0.19, 0.10, 0.08), (1.28, 0.06, 0.04, 0.08)],
        20, cyan, subdivision=0,
    )
    sphere("runner faceted phase canopy", (0, 0.62, -0.42), (0.38, 0.22, 0.58), cyan, 32, 16)
    for side in (-1, 1):
        prism(
            f"runner forked manta foil {side}",
            [(side * 0.18, -1.20), (side * 1.64, -0.56), (side * 1.92, 0.58),
             (side * 1.34, 1.18), (side * 0.47, 0.48)],
            0.20, 0.38, shell, 0.055,
        )
        prism(
            f"runner exposed silver blade edge {side}",
            [(side * 1.50, -0.58), (side * 1.95, 0.57), (side * 1.80, 0.68),
             (side * 1.38, -0.48)],
            0.37, 0.43, silver, 0.018,
        )
        cylinder(f"runner annular phase drive {side}", (side * 0.88, 0.25, 0.93), 0.29, 0.72, graphite,
                 (math.pi / 2, 0, 0), 40, 0.035)
        torus(f"runner cyan drive corona {side}", (side * 0.88, 0.25, 1.30), 0.21, 0.047, cyan)
        cylinder(f"runner drive lens {side}", (side * 0.88, 0.25, 1.34), 0.145, 0.05, cyan,
                 (math.pi / 2, 0, 0), 40, 0.01)
        box(f"runner pulse hash plate {side}", (side * 0.62, 0.47, -0.12), (0.21, 0.025, 0.42), white,
            rotation=(0, side * -0.22, 0), edge=0.025)
        curve_tube(f"runner exposed phase bus {side}",
                   [(side * 0.36, 0.43, -0.74), (side * 0.76, 0.48, -0.18),
                    (side * 1.28, 0.44, 0.48), (side * 1.55, 0.39, 0.70)],
                   0.035, cyan)
    torus("runner unmistakable pulse crest", (0, 0.63, -0.92), 0.24, 0.045, white,
          rotation=(math.pi / 2, 0, 0), major_segments=40)
    stable_export("pulsePhaseMantaV6.candidate.glb")


def build_sentry():
    reset()
    shell = material("sentinel deterministic threat chevrons", (0.17, 0.03, 0.04), 0.68, 0.26, texture="sentinel-chevron.png")
    black = material("sentinel lightless nickel skeleton", (0.009, 0.012, 0.018), 0.91, 0.20)
    bone = material("sentinel scorched ivory blade", (0.50, 0.48, 0.39), 0.28, 0.42)
    ember = material("sentinel red pulse furnace", (0.24, 0.006, 0.009), 0.27, 0.12, (1.0, 0.025, 0.015), 4.5)
    cyan = material("sentinel stolen cyan charge", (0.0, 0.14, 0.18), 0.32, 0.14, (0.0, 0.72, 0.86), 2.8)

    # Tall, suspended cathedral-spider silhouette with a single readable eye.
    loft("sentinel vertical armored reliquary",
         [(-0.95, 0.20, 0.13, 1.08), (-0.62, 0.55, 0.31, 1.16),
          (0.15, 0.72, 0.45, 1.34), (0.88, 0.60, 0.38, 1.48),
          (1.42, 0.34, 0.22, 1.62), (1.68, 0.10, 0.08, 1.72)],
         24, shell, subdivision=0)
    torus("sentinel enormous crown halo", (0, 1.73, 0.10), 1.10, 0.105, bone,
          rotation=(math.pi / 2, 0, 0), major_segments=56)
    torus("sentinel broken ember halo core", (0, 1.73, 0.04), 0.82, 0.045, ember,
          rotation=(math.pi / 2, 0, 0), major_segments=48)
    cylinder("sentinel singular furnace eye", (0, 1.47, -0.50), 0.40, 0.15, ember,
             (math.pi / 2, 0, 0), 48, 0.025)
    torus("sentinel eye aperture", (0, 1.47, -0.43), 0.49, 0.07, bone,
          rotation=(math.pi / 2, 0, 0), major_segments=48)
    for side in (-1, 1):
        # High scythes form a broad threat silhouette.
        curve_tube(f"sentinel upper scythe arm {side}",
                   [(side * 0.48, 1.82, 0.12), (side * 1.15, 2.26, -0.02),
                    (side * 1.88, 2.48, -0.35), (side * 2.34, 2.18, -0.76)],
                   0.12, black)
        prism(f"sentinel ivory execution blade {side}",
              [(side * 1.72, -0.46), (side * 2.58, -0.92), (side * 2.42, -0.23),
               (side * 1.95, 0.12)], 1.93, 2.22, bone, 0.055)
        cylinder(f"sentinel red lance mouth {side}", (side * 2.12, 2.08, -0.74), 0.13, 0.35, ember,
                 (math.pi / 2, 0, 0), 32, 0.015)
        # Four hooked grounding limbs make it read as a hunter, not a vehicle.
        for band, y_bias in ((0, 0.0), (1, 0.42)):
            curve_tube(f"sentinel hooked limb {side} {band}",
                       [(side * (0.38 + band * 0.10), 1.18 + y_bias, 0.12),
                        (side * (1.12 + band * 0.22), 0.88 + y_bias, 0.40),
                        (side * (1.58 + band * 0.18), 0.31 + y_bias, 0.05),
                        (side * (1.82 + band * 0.15), 0.12 + y_bias, -0.56)],
                       0.085, black)
        torus(f"sentinel stolen cadence shackle {side}", (side * 0.74, 1.08, -0.22), 0.18, 0.035, cyan)
    stable_export("pulseCathedralSentinelV6.candidate.glb")


def build_world():
    reset()
    deck = material("reactor deterministic deck plating", (0.08, 0.11, 0.13), 0.76, 0.32, texture="reactor-deck.png")
    black = material("reactor black containment void", (0.008, 0.013, 0.020), 0.87, 0.28)
    wall = material("reactor deep teal armor", (0.025, 0.10, 0.13), 0.72, 0.34)
    silver = material("reactor worn silver structure", (0.28, 0.33, 0.34), 0.88, 0.26)
    cyan = material("reactor cyan pulse bus", (0.0, 0.15, 0.18), 0.31, 0.14, (0.0, 0.68, 0.86), 3.2)
    ember = material("reactor terminal red breach", (0.20, 0.005, 0.009), 0.29, 0.12, (0.95, 0.018, 0.012), 4.0)

    prism("reactor continuous textured exchange deck",
          [(-4.7, 2.7), (4.7, 2.7), (4.55, -11.3), (3.7, -12.0), (-3.7, -12.0), (-4.55, -11.3)],
          -0.38, 0.0, deck, 0.11)
    prism("reactor recessed central cadence trench",
          [(-1.72, 2.4), (1.72, 2.4), (2.05, -10.8), (1.56, -11.46), (-1.56, -11.46), (-2.05, -10.8)],
          0.01, 0.055, black, 0.018)
    for side in (-1, 1):
        box(f"reactor full height armor shell {side}", (side * 4.52, 1.48, -4.45), (0.25, 1.82, 7.1), wall, edge=0.10)
        prism(f"reactor rising blade shoulder {side}",
              [(side * 2.35, 1.9), (side * 4.40, 2.45), (side * 4.37, -10.8), (side * 3.25, -11.55)],
              0.02, 0.50, wall, 0.09)
        curve_tube(f"reactor continuous cyan artery {side}",
                   [(side * 3.78, 0.42, 2.0), (side * 3.62, 0.50, -1.0),
                    (side * 3.34, 0.65, -5.1), (side * 2.90, 0.87, -9.6)],
                   0.07, cyan)

    # Three differently canted structural knots, not a repeated rib tunnel.
    knots = ((-0.6, 0.00), (-4.25, 0.34), (-7.90, -0.28))
    for index, (z, cant) in enumerate(knots):
        points = [(-4.15, 0.40, z), (-3.25, 2.05 + cant, z - 0.12),
                  (-1.45, 3.55 - cant, z + 0.08), (0.72, 3.88 + cant, z - 0.08),
                  (2.72, 2.78 - cant, z + 0.12), (4.15, 0.46, z)]
        curve_tube(f"reactor asymmetric torsion knot {index}", points, 0.13, silver)
        torus(f"reactor cadence knot seal {index}", (0.65, 3.52 + cant, z), 0.30, 0.055,
              cyan if index < 2 else ember, rotation=(0, math.pi / 2, 0), major_segments=36)

    # Broad exchange glyphs make the projectile lane readable at screenshot scale.
    for index, z in enumerate((1.0, -1.15, -3.5, -6.05, -8.75)):
        box(f"reactor broad cadence bridge {index}", (0, 0.085, z), (1.25 - index * 0.06, 0.025, 0.14),
            cyan if index < 3 else ember, edge=0.025)

    # Terminal breach: a giant iris and offset command buttress.
    box("reactor terminal armored backstop", (0, 1.72, -11.54), (4.22, 1.78, 0.28), black, edge=0.14)
    torus("reactor terminal breach outer crown", (0.95, 1.76, -11.20), 1.50, 0.18, silver,
          rotation=(math.pi / 2, 0, 0), major_segments=64)
    torus("reactor terminal breach red aperture", (0.95, 1.76, -11.14), 1.12, 0.075, ember,
          rotation=(math.pi / 2, 0, 0), major_segments=56)
    cylinder("reactor terminal lightless well", (0.95, 1.76, -11.22), 0.92, 0.12, black,
             (math.pi / 2, 0, 0), 64, 0.025)
    for index in range(7):
        angle = index * math.tau / 7 + 0.14
        x = 0.95 + math.cos(angle) * 1.30
        y = 1.76 + math.sin(angle) * 1.30
        box(f"reactor terminal iris tooth {index}", (x, y, -11.02), (0.34, 0.11, 0.08), silver,
            rotation=(0, angle * 0.07, angle), edge=0.035)
    stable_export("pulseBraidedReactorWorldV6.candidate.glb")


def audit():
    rows = []
    for path in sorted(OUT.rglob("*")):
        if path.is_file():
            rows.append((path.relative_to(OUT).as_posix(), path.stat().st_size, hashlib.sha256(path.read_bytes()).hexdigest()))
    for name, size, digest in rows:
        print(f"{digest}  {size:8d}  {name}")


if __name__ == "__main__":
    make_textures()
    build_runner()
    build_sentry()
    build_world()
    audit()
