/**
 * PRD-10 §7.1.5 / T3.2 — scatter + grass authoring surface and the
 * deterministic per-cell Bridson Poisson planner. Placement is a pure CPU
 * pass over 32 m cells; the `scatter` node carries either the rules
 * (`options`, re-planned identically at compile) or explicit `placements`
 * emitted by kits, place*, room/street and `instances.model` world options.
 *
 * Determinism contract: placements for cell (cx, cz) are generated by a
 * stream seeded `hash(seed, layerIndex, cellX, cellZ)` — same inputs, same
 * bytes, so `checksum` (SHA-256 of the sorted placement buffer) is stable
 * across machines. Bridson runs per cell independently: two points
 * straddling a shared cell border may sit closer than `minDistance` — the
 * spec's correctness unit is the cell.
 */
import type { AuraAssetRef, AuraColor } from "../index.js";
import type { AuraTierValue, AuraWorldNodeBase } from "./types.js";
import {
  AuraWorldNodeBuilder,
  terrainRecordFor,
  type AuraTerrainHandle,
  type AuraWorldShape,
  type TerrainRecord
} from "./terrain.js";

// ------------------------------------------------------------ PRD §7.1.5 types

export interface AuraScatterAsset {
  readonly asset: AuraAssetRef<"model">;
  readonly weight?: number;                    // relative probability, default 1
  readonly scale?: readonly [number, number];  // uniform scale range, default [0.85, 1.15]
  readonly sink?: number;                      // metres, default 0.05
  readonly alignToNormal?: number;             // 0..1, default 0 for trees, 1 for rocks
  readonly impostor?: AuraAssetRef<"texture"> | "auto" | "none";
  readonly wind?: boolean;                     // default true when the asset has foliage materials
}
export interface AuraScatterLayer {
  readonly assets: readonly AuraScatterAsset[];
  readonly density: number;                    // instances per 100 m²
  readonly minDistance?: number;               // Poisson radius, metres
  readonly slopeDeg?: readonly [number, number];
  readonly height?: readonly [number, number]; // world-space metres
  readonly onLayers?: Readonly<Record<string, readonly [number, number]>>; // terrain layer weight ranges
  readonly densityMask?: AuraAssetRef<"texture">;
  readonly exclude?: readonly AuraWorldShape[];
  readonly rotationY?: "random" | number;
  readonly colorVariation?: number;            // 0..0.2
}
export interface AuraScatterOptions extends AuraWorldNodeBase {
  /** Stable node id (diagnostics + scatter records); auto-assigned when omitted. */
  readonly id?: string;
  readonly surface: AuraTerrainHandle | { readonly kind: "area"; readonly shape: AuraWorldShape; readonly y?: number };
  readonly layers: readonly AuraScatterLayer[];
  readonly seed: number;
  readonly lod?: { readonly lod1Distance?: AuraTierValue<number>; readonly impostorDistance?: AuraTierValue<number>; readonly cullDistance?: AuraTierValue<number>; readonly crossfade?: number };
  readonly shadows?: AuraTierValue<"none" | "near" | "all">;   // default { low: "none", medium: "near", high: "near", ultra: "all" }
  readonly budget?: AuraTierValue<number>;                     // enforced via planScatterInstances/enforceFrameBudget
  readonly collision?: "none" | "trunk-capsules";
}
export interface AuraScatterPlacement {
  readonly asset: AuraAssetRef<"model">;
  readonly matrices: Float32Array /* 12 floats (3x4) per instance */;
  readonly colors?: Float32Array;
  readonly wind?: boolean;
  readonly impostor?: AuraAssetRef<"texture"> | "none";
  readonly shadowLod?: "none" | "lod1" | "impostor";
  readonly chunkSize?: number;
  readonly tags?: readonly string[];
}
export interface AuraScatterNode extends AuraWorldNodeBase {
  readonly kind: "scatter";
  readonly id: string;
  readonly options?: AuraScatterOptions;
  readonly placements?: AuraScatterPlacement;
}
export interface AuraScatterResult {
  readonly node: AuraScatterNode;
  readonly instanceCount: number;
  readonly perAsset: Readonly<Record<string, number>>;
  readonly checksum: string;
}

export interface AuraGrassOptions extends AuraWorldNodeBase {
  /** Stable node id; auto-assigned when omitted. */
  readonly id?: string;
  readonly terrain: AuraTerrainHandle;
  readonly onLayers?: Readonly<Record<string, readonly [number, number]>>; // default { "grass-meadow": [0.4, 1] }
  readonly density?: AuraTierValue<number>;       // default { low: 0 (cards), medium: 10, high: 20, ultra: 32 }
  readonly radius?: AuraTierValue<number>;        // default { low: 15, medium: 30, high: 45, ultra: 60 }
  readonly bladeHeight?: readonly [number, number]; // default [0.18, 0.42]
  readonly bladeWidth?: number;                   // default 0.035
  readonly colorFromTerrain?: boolean;            // default true
  readonly tipColor?: AuraColor;
  readonly exclude?: readonly AuraWorldShape[];
}
export interface AuraGrassNode extends AuraWorldNodeBase {
  readonly kind: "grass";
  readonly id: string;
  readonly options: AuraGrassOptions;
}

// ---------------------------------------------------------------- hash/rng --

/** uint32 mix — the per-cell stream seed `hash(seed, layerIndex, cellX, cellZ)`. */
export function scatterHash(seed: number, layerIndex: number, cellX: number, cellZ: number): number {
  let h = (Math.imul(seed | 0, 2654435761) ^ Math.imul(layerIndex | 0, 40503) ^ Math.imul(cellX | 0, 374761393) ^ Math.imul(cellZ | 0, 668265263)) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  h ^= h >>> 16;
  return h >>> 0;
}

/** Mulberry32-style float stream [0, 1). */
export function scatterRng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------- sha-256 --

// Compact sync SHA-256 (no node:crypto — this module ships in browser bundles).
const SHA256_K: readonly number[] = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
];
function rotr(x: number, n: number): number {
  return ((x >>> n) | (x << (32 - n))) >>> 0;
}
function sha256Hex(bytes: Uint8Array): string {
  const bitLen = bytes.length * 8;
  const padded = Math.ceil((bytes.length + 9) / 64) * 64;
  const buf = new Uint8Array(padded);
  buf.set(bytes);
  buf[bytes.length] = 0x80;
  const dv = new DataView(buf.buffer);
  dv.setUint32(padded - 8, Math.floor(bitLen / 0x100000000), false);
  dv.setUint32(padded - 4, bitLen >>> 0, false);
  const h = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
  const w = new Uint32Array(64);
  for (let off = 0; off < padded; off += 64) {
    for (let i = 0; i < 16; i += 1) w[i] = dv.getUint32(off + i * 4, false);
    for (let i = 16; i < 64; i += 1) {
      const s0 = rotr(w[i - 15]!, 7) ^ rotr(w[i - 15]!, 18) ^ (w[i - 15]! >>> 3);
      const s1 = rotr(w[i - 2]!, 17) ^ rotr(w[i - 2]!, 19) ^ (w[i - 2]! >>> 10);
      w[i] = (w[i - 16]! + s0 + w[i - 7]! + s1) >>> 0;
    }
    let [a, b, c, d, e, f, g, hh] = h as [number, number, number, number, number, number, number, number];
    for (let i = 0; i < 64; i += 1) {
      const s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (hh + s1 + ch + SHA256_K[i]! + w[i]!) >>> 0;
      const s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (s0 + maj) >>> 0;
      hh = g; g = f; f = e; e = (d + t1) >>> 0; d = c; c = b; b = a; a = (t1 + t2) >>> 0;
    }
    h[0] = (h[0]! + a) >>> 0; h[1] = (h[1]! + b) >>> 0; h[2] = (h[2]! + c) >>> 0; h[3] = (h[3]! + d) >>> 0;
    h[4] = (h[4]! + e) >>> 0; h[5] = (h[5]! + f) >>> 0; h[6] = (h[6]! + g) >>> 0; h[7] = (h[7]! + hh) >>> 0;
  }
  return h.map((x) => x.toString(16).padStart(8, "0")).join("");
}

/** SHA-256 hex of the sorted placement matrix bytes (§15 determinism). */
export function scatterChecksum(matrices: Float32Array): string {
  const bytes = new Uint8Array(matrices.buffer, matrices.byteOffset, matrices.byteLength);
  return sha256Hex(bytes);
}

// ------------------------------------------------------------ rules eval --

interface SurfaceSampler {
  readonly heightAt: (x: number, z: number) => number;
  readonly slopeDegAt: (x: number, z: number) => number;
  readonly layerWeightsAt: (x: number, z: number) => Readonly<Record<string, number>>;
}

const AREA_SAMPLER_BASE: SurfaceSampler = {
  heightAt: () => 0,
  slopeDegAt: () => 0,
  layerWeightsAt: () => ({})
};

function areaSampler(y: number): SurfaceSampler {
  return { ...AREA_SAMPLER_BASE, heightAt: () => y };
}

function terrainSampler(handle: AuraTerrainHandle): SurfaceSampler | null {
  const record = terrainRecordFor(handle.id);
  if (!record || !record.grid) return null;
  return handle;
}

/**
 * The rules predicate shared by `planScatterInstances` and the compile-time
 * handler: slope/height/`onLayers`/`exclude`. `densityMask` is asset data and
 * resolves on the render path (recorded on the node, documented divergence).
 */
export function scatterRuleAccepts(
  layer: AuraScatterLayer,
  sample: { readonly x: number; readonly z: number; readonly height: number; readonly slopeDeg: number; readonly layers: Readonly<Record<string, number>> },
  excludeInside: (shape: AuraWorldShape, x: number, z: number) => boolean
): boolean {
  if (layer.slopeDeg && (sample.slopeDeg < layer.slopeDeg[0] || sample.slopeDeg > layer.slopeDeg[1])) return false;
  if (layer.height && (sample.height < layer.height[0] || sample.height > layer.height[1])) return false;
  if (layer.onLayers) {
    for (const [name, range] of Object.entries(layer.onLayers)) {
      const w = sample.layers[name] ?? 0;
      if (w < range[0] || w > range[1]) return false;
    }
  }
  if (layer.exclude?.some((s) => excludeInside(s, sample.x, sample.z))) return false;
  return true;
}

// ------------------------------------------------------------- placement --

/** One placed instance, with its producing layer/asset for packing. */
export interface ScatterInstance {
  readonly x: number;
  readonly z: number;
  readonly y: number;
  readonly yawDeg: number;
  readonly scale: number;
  readonly variation: number; // 0..1
  readonly layerIndex: number;
  readonly assetIndex: number;
  readonly wind: boolean;
}

export const SCATTER_CELL_SIZE = 32;

function surfaceBounds(options: AuraScatterOptions, record: TerrainRecord | null): { readonly min: readonly [number, number]; readonly max: readonly [number, number] } {
  const surface = options.surface;
  if ("kind" in surface) {
    const s = surface.shape;
    if (s.kind === "circle") return { min: [s.center[0] - s.radius, s.center[1] - s.radius], max: [s.center[0] + s.radius, s.center[1] + s.radius] };
    if (s.kind === "polygon") {
      const xs = s.points.map((p) => p[0]);
      const ys = s.points.map((p) => p[1]);
      return { min: [Math.min(...xs), Math.min(...ys)], max: [Math.max(...xs), Math.max(...ys)] };
    }
    return { min: [0, 0], max: [0, 0] }; // spline bounds land with world.spline
  }
  if (record) {
    return { min: [record.origin[0], record.origin[2]], max: [record.origin[0] + record.size[0], record.origin[2] + record.size[1]] };
  }
  return { min: [0, 0], max: [0, 0] };
}

function shapeContainsWorld(shape: AuraWorldShape, x: number, z: number): boolean {
  if (shape.kind === "circle") return Math.hypot(x - shape.center[0], z - shape.center[1]) <= shape.radius;
  if (shape.kind === "polygon") {
    let inside = false;
    const pts = shape.points;
    for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
      const [xi, zi] = pts[i]!;
      const [xj, zj] = pts[j]!;
      if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) inside = !inside;
    }
    return inside;
  }
  return false; // spline: resolved with world.spline
}

/**
 * `exclude` shapes are authored in world metres on area surfaces and in
 * normalized terrain uv on terrain surfaces (matching terrain `holes`).
 */
function excludeInside(record: TerrainRecord | null, shape: AuraWorldShape, x: number, z: number): boolean {
  if (record) {
    const u = (x - record.origin[0]) / record.size[0];
    const v = (z - record.origin[2]) / record.size[1];
    if (shape.kind === "circle") {
      return Math.hypot(u - shape.center[0], v - shape.center[1]) <= shape.radius;
    }
    if (shape.kind === "polygon") {
      let inside = false;
      const pts = shape.points;
      for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
        const [xi, zi] = pts[i]!;
        const [xj, zj] = pts[j]!;
        if (zi > v !== zj > v && u < ((xj - xi) * (v - zi)) / (zj - zi) + xi) inside = !inside;
      }
      return inside;
    }
    return false;
  }
  return shapeContainsWorld(shape, x, z);
}

/**
 * §7.1.5 / T3.2 — plan all instances for a scatter surface: per-cell Bridson
 * Poisson over the 32 m grid, filtered by the layer rules, then a seeded
 * weighted asset pick per point. Deterministic in the options+seed.
 *
 * `budget` is NOT applied here — `enforceFrameBudget` slices the stable
 * prefix so the frame pass re-applies it per tier without replanning.
 */
export function planScatterInstances(options: AuraScatterOptions): readonly ScatterInstance[] {
  const record = "kind" in options.surface ? null : terrainRecordFor(options.surface.id) ?? null;
  const sampler: SurfaceSampler | null = "kind" in options.surface
    ? areaSampler(options.surface.y ?? 0)
    : terrainSampler(options.surface);
  if (!sampler) return [];
  const bounds = surfaceBounds(options, record);
  if (bounds.max[0] <= bounds.min[0] || bounds.max[1] <= bounds.min[1]) return [];

  const out: ScatterInstance[] = [];
  const cellX0 = Math.floor(bounds.min[0] / SCATTER_CELL_SIZE);
  const cellX1 = Math.floor((bounds.max[0] - 1e-6) / SCATTER_CELL_SIZE);
  const cellZ0 = Math.floor(bounds.min[1] / SCATTER_CELL_SIZE);
  const cellZ1 = Math.floor((bounds.max[1] - 1e-6) / SCATTER_CELL_SIZE);

  options.layers.forEach((layer, layerIndex) => {
    const r = layer.minDistance ?? Math.max(0.5, Math.sqrt(100 / Math.max(layer.density, 1e-6)) * 0.8);
    for (let cz = cellZ0; cz <= cellZ1; cz += 1) {
      for (let cx = cellX0; cx <= cellX1; cx += 1) {
        const rng = scatterRng(scatterHash(options.seed, layerIndex, cx, cz));
        const cellMinX = cx * SCATTER_CELL_SIZE;
        const cellMinZ = cz * SCATTER_CELL_SIZE;
        const cellMaxX = cellMinX + SCATTER_CELL_SIZE;
        const cellMaxZ = cellMinZ + SCATTER_CELL_SIZE;
        const points = bridsonCell(rng, cellMinX, cellMinZ, cellMaxX, cellMaxZ, r, (layer.density * SCATTER_CELL_SIZE * SCATTER_CELL_SIZE) / 100);
        for (const [px, pz] of points) {
          if (px < bounds.min[0] || px >= bounds.max[0] || pz < bounds.min[1] || pz >= bounds.max[1]) continue;
          if (record && (px < record.origin[0] || px >= record.origin[0] + record.size[0] || pz < record.origin[2] || pz >= record.origin[2] + record.size[1])) continue;
          if ("kind" in options.surface && !shapeContainsWorld(options.surface.shape, px, pz)) continue;
          const slopeDeg = sampler.slopeDegAt(px, pz);
          const height = sampler.heightAt(px, pz);
          const layers = sampler.layerWeightsAt(px, pz);
          if (!scatterRuleAccepts(layer, { x: px, z: pz, height, slopeDeg, layers }, (s, x, z) => excludeInside(record, s, x, z))) continue;
          const assetIndex = pickAssetIndex(layer, rng);
          if (assetIndex < 0) continue;
          const asset = layer.assets[assetIndex]!;
          const [sMin, sMax] = asset.scale ?? [0.85, 1.15];
          const scale = sMin + rng() * (sMax - sMin);
          const yawDeg = layer.rotationY === "random" || layer.rotationY === undefined ? rng() * 360 : layer.rotationY;
          const variation = Math.min(1, Math.max(0, 0.5 + (rng() - 0.5) * 2 * ((layer.colorVariation ?? 0.1) / 0.2)));
          out.push({
            x: px,
            z: pz,
            y: height - (asset.sink ?? 0.05) * scale,
            yawDeg,
            scale,
            variation,
            layerIndex,
            assetIndex,
            wind: asset.wind ?? true
          });
        }
      }
    }
  });
  // Stable order for checksum + budget prefix: cell-major, then layer/asset.
  out.sort((a, b) => a.z - b.z || a.x - b.x || a.layerIndex - b.layerIndex || a.assetIndex - b.assetIndex);
  return out;
}

/** Classic Bridson inside one rect: k=30 attempts, active list, capacity cap. */
function bridsonCell(rng: () => number, minX: number, minZ: number, maxX: number, maxZ: number, radius: number, targetCount: number): [number, number][] {
  const w = maxX - minX;
  const h = maxZ - minZ;
  const cap = Math.max(1, Math.floor(targetCount * 1.5));
  const cell = radius / Math.SQRT2;
  const gw = Math.max(1, Math.ceil(w / cell));
  const gh = Math.max(1, Math.ceil(h / cell));
  const grid = new Int32Array(gw * gh).fill(-1);
  const points: [number, number][] = [];
  const active: number[] = [];
  const place = (x: number, z: number): boolean => {
    const gx = Math.min(gw - 1, Math.max(0, Math.floor((x - minX) / cell)));
    const gz = Math.min(gh - 1, Math.max(0, Math.floor((z - minZ) / cell)));
    for (let oz = Math.max(0, gz - 2); oz <= Math.min(gh - 1, gz + 2); oz += 1) {
      for (let ox = Math.max(0, gx - 2); ox <= Math.min(gw - 1, gx + 2); ox += 1) {
        const i = grid[oz * gw + ox]!;
        if (i >= 0) {
          const [qx, qz] = points[i]!;
          if ((qx - x) * (qx - x) + (qz - z) * (qz - z) < radius * radius) return false;
        }
      }
    }
    points.push([x, z]);
    active.push(points.length - 1);
    grid[gz * gw + gx] = points.length - 1;
    return true;
  };
  place(minX + rng() * w, minZ + rng() * h);
  while (active.length > 0 && points.length < cap) {
    const ai = Math.floor(rng() * active.length);
    const [ax, az] = points[active[ai]!]!;
    let found = false;
    for (let k = 0; k < 30; k += 1) {
      const a = rng() * Math.PI * 2;
      const rr = radius * (1 + rng());
      const x = ax + Math.cos(a) * rr;
      const z = az + Math.sin(a) * rr;
      if (x < minX || x >= maxX || z < minZ || z >= maxZ) continue;
      if (place(x, z)) { found = true; break; }
    }
    if (!found) {
      active[ai] = active[active.length - 1]!;
      active.pop();
    }
  }
  return points;
}

function pickAssetIndex(layer: AuraScatterLayer, rng: () => number): number {
  if (layer.assets.length === 0) return -1;
  const weights = layer.assets.map((a) => Math.max(0, a.weight ?? 1));
  const total = weights.reduce((a, b) => a + b, 0);
  if (total <= 0) return 0;
  let t = rng() * total;
  for (let i = 0; i < layer.assets.length; i += 1) {
    t -= weights[i]!;
    if (t <= 0) return i;
  }
  return layer.assets.length - 1;
}

/**
 * §7.1.5 budget — `planScatterInstances` order is stable, so slicing the
 * first `max` keeps a deterministic prefix; no reshuffle when the tier's
 * budget changes.
 */
export function enforceFrameBudget<T>(instances: readonly T[], max: number): readonly T[] {
  return max >= 0 && instances.length > max ? instances.slice(0, max) : instances;
}

// ------------------------------------------------- packing + node builder --

/** Pack a group of instances into one `placements` block (row-major mat3x4). */
export function packScatterPlacement(asset: AuraAssetRef<"model">, instances: readonly ScatterInstance[], options?: { readonly wind?: boolean; readonly chunkSize?: number; readonly tags?: readonly string[] }): AuraScatterPlacement {
  const matrices = new Float32Array(instances.length * 12);
  const colors = new Float32Array(instances.length * 4);
  for (let i = 0; i < instances.length; i += 1) {
    const p = instances[i]!;
    const c = Math.cos((p.yawDeg * Math.PI) / 180) * p.scale;
    const s = Math.sin((p.yawDeg * Math.PI) / 180) * p.scale;
    // row-major mat3x4: [c 0 s px | 0 1 0 py | -s 0 c pz]
    matrices.set([c, 0, s, p.x, 0, p.scale, 0, p.y, -s, 0, c, p.z], i * 12);
    colors.set([p.variation, p.variation, p.variation, 1], i * 4);
  }
  return {
    asset,
    matrices,
    colors,
    wind: options?.wind ?? instances.some((p) => p.wind),
    chunkSize: options?.chunkSize ?? SCATTER_CELL_SIZE,
    ...(options?.tags ? { tags: options.tags } : {})
  };
}

let scatterSeq = 0;
let grassSeq = 0;

/**
 * §7.1.5 `world.scatter(options)` — emits the rule-carrying `scatter` node and
 * (when the surface resolves at build time) the eager `instanceCount`,
 * `perAsset` and `checksum` of the deterministic plan. The node keeps
 * `options` (not `placements`) so the compile handler re-plans identically.
 */
export function worldScatter(options: AuraScatterOptions): AuraScatterResult {
  if (!options.layers || options.layers.length === 0) {
    throw new Error("world.scatter: at least one layer is required");
  }
  for (const layer of options.layers) {
    if (layer.assets.length === 0) throw new Error("world.scatter: every layer needs >= 1 asset");
    if (layer.density <= 0) throw new Error("world.scatter: layer density must be > 0");
  }
  const id = options.id ?? `scatter-${++scatterSeq}`;
  const node: AuraScatterNode = { kind: "scatter", id, name: options.name ?? id, options };
  const instances = planScatterInstances(options);
  const perAsset: Record<string, number> = {};
  const allMatrices = new Float32Array(instances.length * 12);
  instances.forEach((p, i) => {
    const layer = options.layers[p.layerIndex]!;
    const asset = layer.assets[p.assetIndex]!;
    perAsset[asset.asset.id] = (perAsset[asset.asset.id] ?? 0) + 1;
    const packed = packScatterPlacement(asset.asset, [p]);
    allMatrices.set(packed.matrices, i * 12);
  });
  return {
    node,
    instanceCount: instances.length,
    perAsset,
    checksum: scatterChecksum(allMatrices)
  };
}

/** §7.1.5 `world.grass(options)` — node only; blades are generated on the GPU (§8.5). */
export function worldGrass(options: AuraGrassOptions): AuraWorldNodeBuilder<AuraGrassNode> {
  const id = options.id ?? `grass-${++grassSeq}`;
  const node: AuraGrassNode = { kind: "grass", id, name: options.name ?? id, options };
  return new AuraWorldNodeBuilder<AuraGrassNode>({ ...node });
}
