// PRD-07 P1-T11 — AuraVfxAtlasManifest v1 (C-07-OUT-3, prd07-owned per
// CONTRACTS App. A) and the built-in sequence table. The runtime loader is
// `rendering/src/vfx/VfxAtlas.ts`; the on-disk manifest.json is generated by
// `tools/vfx-atlas-bake/bake.mjs` and validated by `aura3d vfx validate-atlas`
// (C-39).

/** Built-in atlas sequence names (§6.2.6). The bake tool emits one manifest entry per name. */
export type AuraVfxBuiltinSequence =
  | "soft-dot" | "glow" | "flare" | "spark-streak" | "ring" | "ring-thin" | "dust-mote" | "bubble" | "rain-streak"
  | "snowflake" | "smoke-a" | "smoke-b" | "fireball" | "flame-loop" | "muzzle" | "splash" | "electric" | "debris-chips";

export const AURA_VFX_BUILTIN_SEQUENCES: readonly AuraVfxBuiltinSequence[] = [
  "soft-dot", "glow", "flare", "spark-streak", "ring", "ring-thin", "dust-mote", "bubble", "rain-streak",
  "snowflake", "smoke-a", "smoke-b", "fireball", "flame-loop", "muzzle", "splash", "electric", "debris-chips"
];

export interface AuraVfxAtlasPage {
  readonly id: string;
  readonly uri: string;
  readonly size: number;
  readonly premultiplied: true;
  readonly colorSpace: "srgb";
}

export interface AuraVfxAtlasSequenceEntry {
  readonly page: string;
  /** Pixel rect [x, y, w, h] on the page; the rect includes the frame grid, gutter excluded. */
  readonly rect: readonly [number, number, number, number];
  readonly columns: number;
  readonly rows: number;
  readonly frames: number;
  readonly fps?: number;
  readonly loop?: boolean;
}

export interface AuraVfxAtlasManifest {
  readonly version: 1;
  readonly pages: readonly AuraVfxAtlasPage[];
  readonly sequences: Readonly<Record<string, AuraVfxAtlasSequenceEntry>>;
}

/** Pick the atlas page for a C-27 tier: 1k for Low/Medium, 2k for High/Ultra. */
export function vfxAtlasPageForTier(tier: "low" | "medium" | "high" | "ultra", manifest: AuraVfxAtlasManifest): AuraVfxAtlasPage {
  const want2k = tier === "high" || tier === "ultra";
  const bySize = manifest.pages.find((page) => (want2k ? page.size >= 2048 : page.size <= 1024));
  return bySize ?? manifest.pages[0];
}

/** Validate a manifest's geometry: every rect lies inside its page with ≥1px gutter at mip 0. */
export function validateVfxAtlasManifest(manifest: AuraVfxAtlasManifest): readonly string[] {
  const problems: string[] = [];
  const pageById = new Map(manifest.pages.map((page) => [page.id, page]));
  for (const [name, seq] of Object.entries(manifest.sequences)) {
    const page = pageById.get(seq.page);
    if (!page) {
      problems.push(`${name}: unknown page ${seq.page}`);
      continue;
    }
    const [x, y, w, h] = seq.rect;
    if (x < 0 || y < 0 || w <= 0 || h <= 0 || x + w > page.size || y + h > page.size) {
      problems.push(`${name}: rect ${seq.rect} outside page ${seq.page} (${page.size})`);
    }
    const cellW = w / seq.columns;
    const cellH = h / seq.rows;
    if (!Number.isInteger(cellW) || !Number.isInteger(cellH)) {
      problems.push(`${name}: cell size ${cellW}×${cellH} is not integral`);
    }
    if (seq.frames < 1 || seq.frames > seq.columns * seq.rows) {
      problems.push(`${name}: frames ${seq.frames} exceeds grid ${seq.columns}×${seq.rows}`);
    }
  }
  for (const name of AURA_VFX_BUILTIN_SEQUENCES) {
    if (!manifest.sequences[name]) problems.push(`${name}: builtin sequence missing`);
  }
  return problems;
}
