import { readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const json = (path: string): any => JSON.parse(readFileSync(resolve(path), "utf8")); const text = (path: string): string => readFileSync(resolve(path), "utf8");
const baseline = json("tests/reports/current-threejs-baseline.json"); const context = json("benchmark/context/threejs-r185.1-20260808.json"); const browser = json("tests/reports/current-head-to-head/postprocessed-scene/report.json"); const source = text("benchmark/current-head-to-head/postprocessed-scene/main.ts"); const captures = ["aura-off.png", "three-off.png", "aura-on.png", "three-on.png"];
const checks = [
  { id: "current-three-r185", pass: baseline.pass === true && baseline.three?.version === "0.185.1" && browser.baseline?.three?.revision === "185" },
  { id: "frozen-product-and-native-captures", pass: browser.assetSha256 === context.assets.product.sha256 && browser.baseline?.aura?.metadata?.unsupportedExtensions?.length === 0 && captures.every((name) => statSync(resolve(`tests/reports/current-head-to-head/postprocessed-scene/${name}`)).size > 20_000) },
  { id: "real-public-composers", pass: source.includes('from "@aura3d/') && !source.includes("packages/") && browser.baseline?.three?.actualEffectComposer === true && browser.baseline?.three?.actualUnrealBloomPass === true && browser.baseline?.three?.actualOutputPass === true },
  { id: "paired-bloom-pass-execution", pass: browser.baseline?.aura?.passNames?.join("|") === "tone-mapping" && browser.enabled?.aura?.passNames?.join("|") === "bloom|tone-mapping" && browser.baseline?.three?.enabledPasses?.join("|") === "RenderPass|OutputPass" && browser.enabled?.three?.enabledPasses?.join("|") === "RenderPass|UnrealBloomPass|OutputPass" },
  { id: "paired-subject-pixel-change", pass: browser.enabled?.delta?.aura?.changedPixels > 1_000 && browser.enabled?.delta?.three?.changedPixels > 1_000 && browser.baseline?.aura?.hash !== browser.enabled?.aura?.hash && browser.baseline?.three?.hash !== browser.enabled?.three?.hash },
  { id: "matched-background-output", pass: samePixel(browser.baseline?.aura?.backgroundPixel, browser.baseline?.three?.backgroundPixel) && samePixel(browser.enabled?.aura?.backgroundPixel, browser.enabled?.three?.backgroundPixel) },
  { id: "same-session-directional-frame-samples", pass: browser.enabled?.aura?.frameCost?.samples === 11 && browser.enabled?.three?.frameCost?.samples === 11 && browser.enabled?.aura?.frameCost?.medianMs > 0 && browser.enabled?.three?.frameCost?.medianMs > 0 },
  { id: "caller-owned-resource-disposal", pass: Object.values(browser.lifecycle ?? {}).every(Boolean) && Object.keys(browser.lifecycle ?? {}).length === 4 }
];
const failures = checks.filter((entry) => !entry.pass); const auraMedian = browser.enabled?.aura?.frameCost?.medianMs; const threeMedian = browser.enabled?.three?.frameCost?.medianMs; const report = { schema: "aura3d.current-head-to-head-postprocessed-scene/1.0", generatedAt: new Date().toISOString(), pass: failures.length === 0, workload: "postprocessed-scene", verdict: "both-execute-selected-bloom-chain", checks, failures, comparison: { auraPasses: browser.enabled?.aura?.passNames, threePasses: browser.enabled?.three?.enabledPasses, auraRenderTargets: browser.enabled?.aura?.renderTargets, threeRenderTargets: browser.enabled?.three?.renderTargets, auraMedianMs: auraMedian, threeMedianMs: threeMedian, medianRatio: auraMedian > 0 && threeMedian > 0 ? Number((auraMedian / threeMedian).toFixed(3)) : null, observedLosses: ["Personal inspection of all four retained frames found closely aligned baseline subject, framing, and byte-identical backgrounds. With bloom enabled, Aura's halo is tighter while Three.js UnrealBloomPass spreads a broader multiscale halo; visual parity is not claimed.", "The selected effect's measured mean RGB change is closely aligned, but matching a single tuned bloom workload does not establish parity with Three.js's full official and third-party postprocessing ecosystems.", "The 3-warmup/11-sample same-session frame-cost probe is directional only and does not satisfy the frozen 120-warmup/600-frame/five-session Phase 4 performance contract; no non-inferiority verdict is claimed."], claimBoundary: "Public low-level rendering and advanced-runtime package proof, not root createAuraApp proof." }, browser }; const output = resolve("tests/reports/current-head-to-head/postprocessed-scene/aggregate.json"); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); if (failures.length) { console.error(`Postprocessed-scene head-to-head UNPROVEN: ${failures.map((entry) => entry.id).join(", ")}`); process.exitCode = 1; } else console.log(`Postprocessed-scene head-to-head PASS: ${checks.length}/${checks.length}; ${output}`);
function samePixel(left: readonly number[] | undefined, right: readonly number[] | undefined): boolean { return Boolean(left && right && left.length === right.length && left.every((value, index) => value === right[index])); }
