import { test, expect } from "@playwright/test";

// PRD-01 §15 Phase-3 C-02: every representative feature record generated by
// the lane-01 program generator compiles AND links on a real WebGL2 context.
// Runs under a3d-qr=core (the generator only exists in the v2 lane).

interface ProgramCompileCase {
  readonly name: string;
  readonly vertexOk: boolean;
  readonly fragmentOk: boolean;
  readonly linked: boolean;
  readonly infoLog?: string;
}

test("generated programs compile+link on WebGL2", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(String(error)));
  await page.goto("/?tools=program-compile&a3d-qr=core", { waitUntil: "load" });
  await page.waitForFunction(() => window.__QR_READY__ !== undefined || window.__QR_ERROR__ !== undefined, null, {
    timeout: 120_000
  });
  const qrError = await page.evaluate(() => window.__QR_ERROR__);
  expect(qrError).toBeUndefined();

  const report = (await page.evaluate(
    () => (window as unknown as { __QR_PROGRAM_COMPILE__?: { cases: ProgramCompileCase[]; errors: string[] } }).__QR_PROGRAM_COMPILE__
  ))!;
  expect(report.cases.length).toBeGreaterThanOrEqual(13);
  for (const c of report.cases) {
    expect(c.vertexOk, `${c.name} vertex: ${c.infoLog ?? ""}`).toBe(true);
    expect(c.fragmentOk, `${c.name} fragment: ${c.infoLog ?? ""}`).toBe(true);
    expect(c.linked, `${c.name} link: ${c.infoLog ?? ""}`).toBe(true);
  }
  expect(report.errors).toEqual([]);
  expect(errors.filter((e) => !e.includes("favicon"))).toEqual([]);
});
