// T3.13 — option coverage: every option field of every node builder must
// change the compiled scene input, or be declared diagnostic-only.
//
// For each scaffolded row (agent-api/compiler/optionCoverage.ts, generated by
// tools/arch-gates/rules/option-coverage.ts --scaffold) the test compiles
// `scene().add(builder({ field: probeValueA }))` and `probeValueB` through the
// real C-36 compiler (A3D_QR_COMPILER on) and asserts
// `deepDiff(sourceA, sourceB).length > 0` — unless the field is in the merged
// DIAGNOSTIC_ONLY_FIELDS (contract seeds + this lane's diagnosticOnly.prd15.ts).
//
// An owner lane clears an entry without touching lane files: it calls
// registerOptionCoverage for the field from its own module; the option-coverage
// arch gate then lists the stale diagnostic entry for this lane's daily sweep.
import "@aura3d/engine";
import { describe, expect, it } from "vitest";
import { DIAGNOSTIC_ONLY_FIELDS, compileScene, asRuntimeCompiled } from "@aura3d/engine/contracts";
import type { OptionCoverageRow } from "@aura3d/engine/contracts";
import { resolveQrFlags } from "../../../../packages/engine/src/contracts/flags";
import { OPTION_COVERAGE_ROWS } from "../../../../packages/engine/src/agent-api/compiler/optionCoverage";
import { PRD15_DIAGNOSTIC_ONLY_FIELDS } from "../../../../packages/engine/src/agent-api/compiler/diagnosticOnly.prd15";
import type { MountSceneCompileContext } from "../../../../packages/engine/src/agent-api/compiler/compileScene";
import { scene } from "../../../../packages/engine/src/agent-api/nodes/scene";
import type { AuraSceneNode, AuraSceneSnapshot, AuraAssetRef, CollectedLight } from "../../../../packages/engine/src/agent-api/nodes/types";
import type { EnvironmentLightingOptions } from "@aura3d/rendering";
import { lights } from "../../../../packages/engine/src/agent-api/nodes/lights";
import { primitives, primitive } from "../../../../packages/engine/src/agent-api/nodes/primitives";
import { instances, instancedPrimitive } from "../../../../packages/engine/src/agent-api/nodes/instances";
import { labels } from "../../../../packages/engine/src/agent-api/nodes/labels";
import { shadows } from "../../../../packages/engine/src/agent-api/nodes/shadows";
import { geometry } from "../../../../packages/engine/src/agent-api/nodes/geometry";
import { neon } from "../../../../packages/engine/src/agent-api/nodes/neon";
import { interactions } from "../../../../packages/engine/src/agent-api/nodes/interactions";
import { environments } from "../../../../packages/engine/src/agent-api/nodes/environments.composite";
import { envSourceBuilders } from "../../../../packages/engine/src/agent-api/nodes/environments";
import { effects } from "../../../../packages/engine/src/agent-api/nodes/effects.composite";
import { vfxEffectBuilders } from "../../../../packages/engine/src/agent-api/nodes/effects";
import { postEffectBuilders } from "../../../../packages/engine/src/agent-api/nodes/effects.post";
import { lightingEffectBuilders } from "../../../../packages/engine/src/agent-api/nodes/effects.lighting";
import { charts } from "../../../../packages/engine/src/agent-api/nodes/charts";
import { camera } from "../../../../packages/engine/src/agent-api/nodes/camera";
import { group, distanceLod } from "../../../../packages/engine/src/agent-api/nodes/groups";
import { model } from "../../../../packages/engine/src/agent-api/nodes/model";
import { text3D } from "../../../../packages/engine/src/agent-api/nodes/text3d";
import { water } from "../../../../packages/engine/src/agent-api/nodes/water";
import { sky } from "../../../../packages/engine/src/agent-api/nodes/sky";
import { particles } from "../../../../packages/engine/src/agent-api/nodes/particles";
import { animation } from "../../../../packages/engine/src/agent-api/nodes/animation";
import { auraAssetRefBrand } from "../../../../packages/engine/src/agent-api/nodes/assets";

/* ------------------------------ deep diff ------------------------------- */

type Diff = { readonly path: string; readonly a: unknown; readonly b: unknown };

function deepDiff(a: unknown, b: unknown, path = "$"): Diff[] {
  if (Object.is(a, b)) return [];
  if (a === null || b === null || typeof a !== "object" || typeof b !== "object") return [{ path, a, b }];
  if (Array.isArray(a) !== Array.isArray(b)) return [{ path, a, b }];
  if (Array.isArray(a) && Array.isArray(b)) {
    const diffs: Diff[] = [];
    for (let i = 0; i < Math.max(a.length, b.length); i++) diffs.push(...deepDiff(a[i], b[i], `${path}[${i}]`));
    return diffs;
  }
  const aObj = a as Record<string, unknown>;
  const bObj = b as Record<string, unknown>;
  if (ArrayBuffer.isView(a) && ArrayBuffer.isView(b)) {
    const view = a as unknown as ArrayLike<number>;
    const other = b as unknown as ArrayLike<number>;
    const diffs: Diff[] = [];
    for (let i = 0; i < Math.max(view.length, other.length); i++) if (view[i] !== other[i]) diffs.push({ path: `${path}[${i}]`, a: view[i], b: other[i] });
    return diffs;
  }
  const diffs: Diff[] = [];
  for (const key of new Set([...Object.keys(aObj), ...Object.keys(bObj)])) diffs.push(...deepDiff(aObj[key], bObj[key], `${path}.${key}`));
  return diffs;
}

/* --------------------------- builder resolution -------------------------- */

type AnyBuilder = (...args: readonly unknown[]) => unknown;

const NAMESPACES: Record<string, Record<string, unknown>> = {
  lights, primitives, instances, labels, shadows, geometry, neon, interactions,
  environments, envSourceBuilders, effects, vfxEffectBuilders, postEffectBuilders,
  lightingEffectBuilders, charts, camera, water, sky, particles, animation
};
const FUNCTIONS: Record<string, AnyBuilder> = { primitive, instancedPrimitive, group, distanceLod, model, text3D };

function resolveBuilder(name: string): AnyBuilder {
  const [head, ...rest] = name.split(".");
  let target: unknown = FUNCTIONS[head] ?? NAMESPACES[head];
  for (const part of rest) target = (target as Record<string, unknown> | undefined)?.[part];
  if (typeof target !== "function") throw new Error(`builder "${name}" did not resolve to a callable`);
  return target as AnyBuilder;
}

/* ------------------------------ arg fillers ------------------------------ */

const FAKE_MODEL_ASSET = {
  kind: "aura-asset-ref",
  id: "probe-model",
  type: "model",
  source: "probe.glb",
  uri: "probe.glb",
  [auraAssetRefBrand]: { type: "model", id: "probe-model" }
} as unknown as AuraAssetRef<"model">;

const GROUP_CHILD = primitive("box", { name: "group-child", size: 0.5 });

function fillArg(typeName: string, builder: string): unknown {
  if (typeName === "string") {
    if (builder === "text3D") return "Probe";
    if (builder.startsWith("labels.")) return "Probe";
    if (builder === "group") return "probe-group";
    return "probe";
  }
  if (/AuraNodeInput/.test(typeName)) return [GROUP_CHILD];
  if (/AuraBuiltinPrimitive/.test(typeName)) return "box";
  if (/^TAsset|AuraAssetRef/.test(typeName)) return FAKE_MODEL_ASSET;
  if (/AuraCustomGeometrySpec/.test(typeName)) return CUSTOM_GEOMETRY_SPEC;
  if (/AuraTransformSpec/.test(typeName)) return { position: [0, 0, 0] };
  return { __fill: typeName };
}

/* ----------------------------- compile helper ---------------------------- */

const flags = resolveQrFlags({ options: ["compiler"] });

const mountCtx = (): MountSceneCompileContext => ({
  renderer: undefined,
  assets: undefined,
  quality: { tier: "high" } as MountSceneCompileContext["quality"],
  strict: false,
  flags,
  degrade: () => {},
  canvas: { width: 800, height: 600 } as unknown as HTMLCanvasElement,
  environmentLighting: () => ({} as EnvironmentLightingOptions),
  collectedLights: [] as readonly CollectedLight[],
  runtimeWarnings: new Set<string>()
});

function toNode(value: unknown, builder: string): AuraSceneNode {
  const asBuilder = value as { toJSON?: () => AuraSceneNode };
  if (asBuilder && typeof asBuilder.toJSON === "function") return asBuilder.toJSON();
  if (value && typeof value === "object" && "kind" in value) return value as AuraSceneNode;
  if (value && typeof value === "object" && "nodes" in value) {
    const nodes = (value as { nodes: readonly AuraSceneNode[] }).nodes;
    if (nodes.length === 1) return nodes[0];
    return group(`${builder}-wrap`, nodes).toJSON();
  }
  throw new Error(`builder "${builder}" produced no scene node`);
}

/* ------------------------- required option defaults ------------------------ */

// Builders with required option fields still need a valid invocation for the
// OTHER fields' probes; defaults live here (test mechanics) while probes live
// in the generated rows.
const LOD_LEVEL = { name: "near", primitive: "box" as const, maxDistance: 10 };
const LOD_LEVEL_FAR = { name: "far", primitive: "sphere" as const, maxDistance: 40 };
const INSTANCE_TRANSFORM = { position: [0, 0, 0] as [number, number, number] };
const CUSTOM_GEOMETRY_SPEC = {
  kind: "aura-custom-geometry" as const,
  positions: [[0, 0, 0], [1, 0, 0], [0, 1, 0]] as [number, number, number][],
  indices: [0, 1, 2]
};
const CUSTOM_GEOMETRY_SPEC_B = {
  kind: "aura-custom-geometry" as const,
  positions: [[0, 0, 0], [2, 0, 0], [0, 2, 0]] as [number, number, number][],
  indices: [0, 1, 2]
};

const BUILDER_DEFAULTS: Record<string, Record<string, unknown>> = {
  distanceLod: { levels: [LOD_LEVEL] },
  instancedPrimitive: { transforms: [INSTANCE_TRANSFORM] },
  "instances.box": { transforms: [INSTANCE_TRANSFORM] },
  "instances.sphere": { transforms: [INSTANCE_TRANSFORM] },
  "instances.plane": { transforms: [INSTANCE_TRANSFORM] },
  "instances.cylinder": { transforms: [INSTANCE_TRANSFORM] },
  "instances.capsule": { transforms: [INSTANCE_TRANSFORM] },
  "instances.torus": { transforms: [INSTANCE_TRANSFORM] },
  "instances.custom": { transforms: [INSTANCE_TRANSFORM] },
  "instances.model": { transforms: [INSTANCE_TRANSFORM] }
};

// Required fields whose generated probes are invalid shapes get hand-valid
// values here (same role as hand-filling the row).
const PROBE_OVERRIDES: Record<string, { a: unknown; b: unknown }> = {
  "distanceLod.levels": { a: [LOD_LEVEL], b: [LOD_LEVEL, LOD_LEVEL_FAR] },
  "instancedPrimitive.transforms": { a: [INSTANCE_TRANSFORM], b: [INSTANCE_TRANSFORM, { position: [1, 0, 0] }] },
  "text3D.size": { a: 1, b: 2 }
};
for (const name of Object.keys(BUILDER_DEFAULTS)) {
  if (name !== "distanceLod" && name !== "instancedPrimitive") PROBE_OVERRIDES[`${name}.transforms`] = { a: [INSTANCE_TRANSFORM], b: [INSTANCE_TRANSFORM, { position: [1, 0, 0] }] };
}
// Shape-required fields across builders: geometry specs, lod specs, and
// instance colors must stay valid while still differing between A and B.
const SHAPE_REQUIRED: Record<string, { a: unknown; b: unknown }> = {
  geometry: { a: CUSTOM_GEOMETRY_SPEC, b: CUSTOM_GEOMETRY_SPEC_B },
  lod: { a: { levels: [LOD_LEVEL] }, b: { levels: [LOD_LEVEL, LOD_LEVEL_FAR] } },
  colors: { a: ["#000000"], b: ["#ffffff"] },
  instanceColors: { a: ["#000000"], b: ["#ffffff"] },
  text3D: { a: { text: "A", size: 1 }, b: { text: "B", size: 2 } }
};
for (const [field, probes] of Object.entries(SHAPE_REQUIRED)) {
  for (const row of OPTION_COVERAGE_ROWS) {
    if (row.field === field && !(PROBE_OVERRIDES[`${row.builder}.${field}`])) PROBE_OVERRIDES[`${row.builder}.${field}`] = probes;
  }
}

async function compileRow(row: OptionCoverageRow, probe: unknown) {
  const builder = resolveBuilder(row.builder);
  const override = PROBE_OVERRIDES[`${row.builder}.${row.field}`];
  const options = { ...(BUILDER_DEFAULTS[row.builder] ?? {}), [row.field]: override ? (probe === row.probeValueA ? override.a : override.b) : probe };
  const args = [...(row.beforeOptions ?? []).map((t) => fillArg(t, row.builder)), options];
  const node = toNode(builder(...args), row.builder);
  const snapshot = scene().add(node).toJSON() as AuraSceneSnapshot;
  const compiled = await compileScene(snapshot, mountCtx());
  const internals = asRuntimeCompiled(compiled) as Record<string, unknown> | null;
  // Diff only what the compiler handed to the render input or retained as
  // structured state: `source`/`liveNodes`/`dynamicFlat` carry the input node
  // tree verbatim, so a field visible only there was never consumed.
  return {
    handledNodes: internals?.handledNodes,
    actorEntries: internals?.actorEntries,
    primitiveEntries: internals?.primitiveEntries,
    itemCache: internals?.itemCache,
    features: internals?.features,
    degradations: internals?.degradations,
    persistentContributions: internals?.persistentContributions,
    lastInput: internals?.lastInput
  };
}

/* ------------------------- diagnostic-only merge ------------------------- */

const mergedDiagnostics: Record<string, { readonly reason: string; readonly ownerPrd: number }> = {
  ...DIAGNOSTIC_ONLY_FIELDS,
  ...PRD15_DIAGNOSTIC_ONLY_FIELDS
};

const domainOf = (builder: string): string | undefined =>
  builder.startsWith("lights.") ? "light" : builder === "model" || builder === "instances.model" ? "model" : undefined;

function isDiagnosticOnly(row: OptionCoverageRow): string | undefined {
  const key = `${row.builder}.${row.field}`;
  for (const [diagKey, entry] of Object.entries(mergedDiagnostics)) {
    if (diagKey === key || diagKey === `${row.builder}.*` || diagKey === `*.${row.field}`) return `${diagKey}: ${entry.reason}`;
    const [domain, sub] = diagKey.split(".");
    if (row.field === sub && (domain === "transform" || domain === domainOf(row.builder))) return `${diagKey}: ${entry.reason}`;
  }
  return undefined;
}

/* --------------------------------- rows ---------------------------------- */

const rows = OPTION_COVERAGE_ROWS.filter((r) => !r.field.startsWith("__FILL"));

describe("T3.13 option coverage (real C-36 compiler)", () => {
  it("scaffold produced rows", () => {
    expect(rows.length).toBeGreaterThan(1000);
  });

  const uncovered: { row: OptionCoverageRow; key: string }[] = [];
  const failed: { row: OptionCoverageRow; error: unknown }[] = [];

  it("every covered field changes the compiled input", async () => {
    for (const row of rows) {
      const reason = isDiagnosticOnly(row);
      if (reason) continue;
      try {
        const [sourceA, sourceB] = await Promise.all([
          compileRow(row, row.probeValueA),
          compileRow(row, row.probeValueB)
        ]);
        if (deepDiff(sourceA, sourceB).length === 0) uncovered.push({ row, key: `${row.builder}.${row.field}` });
      } catch (error) {
        failed.push({ row, error });
      }
    }
    const report = [
      `uncovered fields (deepDiff === 0): ${uncovered.length}`,
      ...uncovered.slice(0, 200).map((u) => `  ${u.key}`),
      `builder failures: ${failed.length}`,
      ...failed.slice(0, 60).map((f) => `  ${f.row.builder}.${f.row.field}: ${String((f.error as Error)?.message ?? f.error).slice(0, 120)}`)
    ].join("\n");
    if (uncovered.length || failed.length) console.log(report);
    expect(uncovered, `${uncovered.length} fields fell through the compiler:\n${report}`).toEqual([]);
    expect(failed, `${failed.length} builder invocations failed:\n${report}`).toEqual([]);
  });
});
