export type AuraClashEvidenceStatus = "complete" | "implemented" | "needs-visual-qa" | "pending";

export interface AuraClashEvidenceItem {
  id: string;
  label: string;
  status: AuraClashEvidenceStatus;
  proof: string;
  files: string[];
}

export interface AuraClashRouteEvidence {
  path: string;
  purpose: string;
  requiredSignals: string[];
}

export interface AuraClashControlEvidence {
  key: string;
  action: string;
  gameplayEffect: string;
  accessibilityNote: string;
}

export interface AuraClashAssetEvidence {
  name: string;
  typedAsset: string;
  sourcePath: string;
  publicPath: string;
  role: "fighter" | "arena" | "scene";
  provenance: string;
  licenseNote: string;
  thumbnailPath: string;
  bounds: readonly [number, number, number];
  materialSummary: string;
  intendedRouteUsage: string[];
  productionEvidence: string;
  sourceValidationEvidence?: string;
}

export const auraClashAssetEvidence: AuraClashAssetEvidence[] = [
  {
    name: "Mara Volt",
    typedAsset: "assets.fighterMaraVolt",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-mara-volt.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterMaraVolt.18af93d3.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Female_FullBody.gltf plus Hair_Buns.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterMaraVolt.thumb.svg",
    bounds: [0.796, 1.78, 1.184],
    materialSummary: "Eyes, skin, suit, cyan aura accent, and boots are separate named material slots for readable player identity.",
    intendedRouteUsage: ["/playable/ default player", "/accessibility/ playable variant", "/evidence/ asset proof", "/poster/ combined scene representation"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [1.04, 1.04, 1.04], Melee_Hook pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Rook Atlas",
    typedAsset: "assets.fighterRookAtlas",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-rook-atlas.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterRookAtlas.09571256.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Male_FullBody.gltf plus Hair_Buzzed.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterRookAtlas.thumb.svg",
    bounds: [1.131, 1.804, 1.202],
    materialSummary: "Eyes, skin, suit, amber armor accent, and boots are separate named material slots for readable heavy rival identity.",
    intendedRouteUsage: ["/playable/ default rival", "/accessibility/ playable variant", "/evidence/ asset proof", "/poster/ combined scene representation"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [1.22, 1.22, 1.22], Sword_Block pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Nyx Vale",
    typedAsset: "assets.fighterNyxVale",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-nyx-vale.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterNyxVale.13e7bfa8.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Female_FullBody.gltf plus Hair_Long.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterNyxVale.thumb.svg",
    bounds: [1.459, 1.293, 0.869],
    materialSummary: "Eyes, skin, suit, violet/cyan trickster accent, and boots are separate named material slots for readable agile identity.",
    intendedRouteUsage: ["/playable/ selectable fighter", "/accessibility/ playable variant", "/evidence/ asset proof", "/deploy-check/ production asset proof"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [0.98, 0.98, 1.06], NinjaJump_Start pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Kade Ember",
    typedAsset: "assets.fighterKadeEmber",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-kade-ember.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterKadeEmber.5e387f1c.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Male_FullBody.gltf plus Hair_SimpleParted.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterKadeEmber.thumb.svg",
    bounds: [0.766, 1.819, 1.237],
    materialSummary: "Eyes, skin, suit, red/gold ember accent, and boots are separate named material slots for readable balanced fighter identity.",
    intendedRouteUsage: ["/playable/ selectable fighter", "/accessibility/ playable variant", "/evidence/ asset proof", "/deploy-check/ production asset proof"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [1.08, 1.08, 1.08], Sword_Regular_A pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Sable Iron",
    typedAsset: "assets.fighterSableIron",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-sable-iron.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterSableIron.3d88a3a7.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Female_FullBody.gltf plus Hair_BuzzedFemale.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterSableIron.thumb.svg",
    bounds: [0.827, 1.757, 0.81],
    materialSummary: "Eyes, skin, suit, charcoal/ice steel accent, and boots are separate named material slots for readable defensive identity.",
    intendedRouteUsage: ["/playable/ selectable fighter", "/accessibility/ playable variant", "/evidence/ asset proof", "/deploy-check/ production asset proof"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [1.05, 1.05, 1.05], Sword_Block pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Jin Flux",
    typedAsset: "assets.fighterJinFlux",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/fighter-jin-flux.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/fighterJinFlux.6404abf6.glb",
    role: "fighter",
    provenance: "Quaternius Universal Base Characters Standard archive, Superhero_Male_FullBody.gltf plus Hair_SimpleParted.gltf, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Universal Base Characters package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/fighterJinFlux.thumb.svg",
    bounds: [1.64, 1.339, 0.882],
    materialSummary: "Eyes, skin, suit, blue/gold flux accent, and boots are separate named material slots for readable zoner identity.",
    intendedRouteUsage: ["/playable/ selectable fighter", "/accessibility/ playable variant", "/evidence/ asset proof", "/deploy-check/ production asset proof"],
    productionEvidence: "Required by check-production-assets.mjs under the 2 MB fighter gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
    sourceValidationEvidence: "Typed GLB only, no primitive fallback approved. Builder scale [1.02, 1.02, 1.08], NinjaJump_Start pose, export_apply pivot policy, 180 degree source-facing normalization, manifest bounds/materials/thumbnail recorded.",
  },
  {
    name: "Neon Downtown Arena",
    typedAsset: "assets.arenaNeonDowntown",
    sourcePath: "apps/aura-clash-showcase/assets/source/arenas/arena-neon-downtown.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/arenaNeonDowntown.56a42b19.glb",
    role: "arena",
    provenance: "Quaternius Downtown City MegaKit Standard archive, 42 selected arena pieces, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Downtown City MegaKit package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/arenaNeonDowntown.thumb.svg",
    bounds: [20.644, 28.2, 25.322],
    materialSummary: "Asphalt, roof, floor, trim, glass, interior, red brick, concrete, dirt, ornament, street decal, and Aura Clash emissive signage material groups.",
    intendedRouteUsage: ["/evidence/ arena proof", "/deploy-check/ asset proof", "stage data source for Neon Downtown Rooftop variants"],
    productionEvidence: "Required by check-production-assets.mjs under the 25 MB arena gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
  },
  {
    name: "Aura Clash Duel Stage",
    typedAsset: "assets.auraClashDuelStage",
    sourcePath: "apps/aura-clash-showcase/assets/source/scenes/aura-clash-duel-stage.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/auraClashDuelStage.09735d3b.glb",
    role: "scene",
    provenance: "Quaternius Downtown City MegaKit Standard archive plus Aura Clash-authored stage markers/signage, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Downtown kit inputs use Quaternius CC0 1.0 license text; Aura Clash-authored signage and stage markers are project-authored additions.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/auraClashDuelStage.thumb.svg",
    bounds: [20.644, 29.125, 18.628],
    materialSummary: "Live-stage subset with city kit surfaces plus duel-stage backplate, grid, center ring, and neon label materials.",
    intendedRouteUsage: ["/playable/ live stage", "/accessibility/ live stage", "/evidence/ scene proof", "/poster/ capture support"],
    productionEvidence: "Required by check-production-assets.mjs under the 18 MB stage gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
  },
  {
    name: "Aura Clash Playable Scene",
    typedAsset: "assets.auraClashPlayableScene",
    sourcePath: "apps/aura-clash-showcase/assets/source/scenes/aura-clash-playable-scene.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/auraClashPlayableScene.15296b6b.glb",
    role: "scene",
    provenance: "Combined Quaternius Downtown City MegaKit and Universal Base Characters sources plus Aura Clash-authored VFX markers/signage, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius input package license text records CC0 1.0 Universal / Public Domain Dedication; Aura Clash-authored VFX markers and signage are project-authored additions.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/auraClashPlayableScene.thumb.svg",
    bounds: [20.644, 29.7, 25.322],
    materialSummary: "Combined poster/evidence scene with city surfaces, Mara/Rook fighter readability slots, versus ring, impact halo, VFX trails, and neon fighter labels.",
    intendedRouteUsage: ["/poster/ combined capture asset", "/evidence/ combined scene proof", "/deploy-check/ asset proof", "not mounted as live /playable/ runtime scene"],
    productionEvidence: "Required by check-production-assets.mjs under the 22 MB combined-scene gate; aura.assets.json records hash, size, bounds, materials, and thumbnailUrl.",
  },
];

export const auraClashRuntimeMutationEvidenceContract = {
  kind: "aura-clash-runtime-mutation-evidence-contract",
  runtimeExport: "window.__AURA_CLASH_RUNTIME_EVIDENCE__.runtimeMutation",
  requiredSignals: [
    "stableSceneGraph.setSceneUsedForFrameUpdates is false",
    "stableSceneGraph.glbReloadUsedForFrameUpdates is false",
    "typedGlbFighters[].typedAsset uses assets.* keys for both fighters",
    "typedGlbFighters[].runtimeNodeId maps to game.runtimeNode(...) fighter nodes",
    "typedGlbFighters[].body.position changes from AuraClashGame kinematic bodies",
    "gameplayInputProof.collisionHitbox proves input, collision, hit, guard, or miss events",
    "cameraDirector tracks player and opponent bodies, clamps the stage, reports shake, zoom, fov, and reducedMotion",
  ],
  sourceFiles: [
    "apps/aura-clash-showcase/src/main.ts",
    "apps/aura-clash-showcase/src/game/AuraClashGame.ts",
    "apps/aura-clash-showcase/src/game/CameraDirector.ts",
    "apps/aura-clash-showcase/src/game/HitboxSystem.ts",
    "apps/aura-clash-showcase/src/scenes/createFighterNodes.ts",
  ],
} as const;

export const auraClashRouteEvidence: AuraClashRouteEvidence[] = [
  {
    path: "/playable/",
    purpose: "Hands-on arcade route with a keyboard-driven combat loop, HUD, timer, character select, typed GLB stage, and round result states.",
    requiredSignals: [
      "Player can move with A/D or arrow keys, jump with Space, attack, guard, dash, pause with P/Escape, restart, and trigger a special.",
      "Opponent pressure updates health, guard, meter, and combat log state.",
      "Aura3D scene is composed live from the typed duel stage GLB plus selected fighter GLBs.",
      "Gameplay updates mutate persistent game.runtimeNode fighter handles instead of rebuilding the scene graph for frame/state changes.",
    ],
  },
  {
    path: "/evidence/",
    purpose: "Developer proof route showing asset provenance, typed asset paths, implemented controls, routes, and acceptance gates.",
    requiredSignals: [
      "Quaternius source packs are named with local archive paths and hashes in the provenance file.",
      "Launch asset evidence records every public GLB with license note, thumbnail, bounds, material summary, route usage, and fighter source validation fields.",
      "Typed Aura asset names are visible so developers can see the exact API path.",
      "Route source displays hitbox, guard, miss, and body-separation counts from AuraClashRuntimeEvidence.",
      "Route source displays animation states and kinematic body position/velocity source for both fighters.",
      "Incomplete gates are labeled as requiring visual QA instead of being treated as finished.",
    ],
  },
  {
    path: "/accessibility/",
    purpose: "Accessibility route with reduced motion, reduced flash, and high contrast controls exposed directly in the game UI.",
    requiredSignals: [
      "Reduced motion affects motion-heavy visuals.",
      "Reduced flash suppresses impact flashes.",
      "High contrast raises border, text, and UI contrast.",
    ],
  },
  {
    path: "/deploy-check/",
    purpose: "Deployment-readiness route listing the checks required before this becomes the public flagship showcase.",
    requiredSignals: [
      "Route health, screenshot, accessibility, and deploy smoke tests are scaffolded.",
      "Static route files exist for Vercel-style direct URL loading.",
      "Marketing promotion remains gated on visual QA.",
    ],
  },
  {
    path: "/poster/",
    purpose: "Capture route for high-impact launch screenshots, hero posters, and social cards.",
    requiredSignals: [
      "Poster scenarios are named and mapped to exact capture filenames.",
      "Each scenario defines required visual elements.",
      "Capture output remains pending until browser visual QA is approved.",
    ],
  },
];

export const auraClashControlEvidence: AuraClashControlEvidence[] = [
  {
    key: "A / D / Arrow keys",
    action: "Move",
    gameplayEffect: "Moves the player avatar along the combat lane.",
    accessibilityNote: "No rapid input required for basic movement.",
  },
  {
    key: "Space",
    action: "Jump",
    gameplayEffect: "Adds a vertical burst and resets to idle.",
    accessibilityNote: "Can be ignored without blocking core combat.",
  },
  {
    key: "P / Escape",
    action: "Pause",
    gameplayEffect: "Pauses or resumes the round without resetting combat state.",
    accessibilityNote: "Provides keyboard pause paths that do not conflict with Space jump.",
  },
  {
    key: "Shift",
    action: "Dash",
    gameplayEffect: "Triggers a fast lateral movement state and meter gain.",
    accessibilityNote: "Reduced motion mode softens the dash presentation.",
  },
  {
    key: "Q",
    action: "Guard",
    gameplayEffect: "Reduces incoming pressure while active.",
    accessibilityNote: "Hold behavior is visible in the HUD state chip.",
  },
  {
    key: "J",
    action: "Light attack",
    gameplayEffect: "Fast low-damage pressure with combo growth.",
    accessibilityNote: "Attack feedback is text-backed in the combat log.",
  },
  {
    key: "K",
    action: "Heavy attack",
    gameplayEffect: "Slower higher-damage pressure with stronger hitstun.",
    accessibilityNote: "Combat impact is visible without relying only on color.",
  },
  {
    key: "L",
    action: "Special",
    gameplayEffect: "Consumes meter and fires the character super move.",
    accessibilityNote: "Reduced flash mode suppresses high-energy impact flashes.",
  },
  {
    key: "R",
    action: "Restart",
    gameplayEffect: "Resets timer, fighters, meters, and round result state.",
    accessibilityNote: "Provides a keyboard path to replay.",
  },
];

export const auraClashAnimationStates = [
  "idle",
  "light",
  "heavy",
  "special",
  "guard",
  "dash",
  "jump",
  "hitstun",
  "victory",
  "defeat",
] as const;

export const auraClashEvidence: AuraClashEvidenceItem[] = [
  {
    id: "typed-assets",
    label: "Typed Aura3D assets",
    status: "implemented",
    proof: "The live route consumes typed Aura assets through assets.* references: assets.auraClashDuelStage plus selected fighter GLBs, composed at runtime instead of mounted as a standalone playable-scene asset.",
    files: [
      "apps/aura-clash-showcase/src/aura-assets.ts",
      "apps/aura-clash-showcase/public/aura-assets",
      "apps/aura-clash-showcase/src/main.ts",
    ],
  },
  {
    id: "quaternius-provenance",
    label: "Quaternius asset provenance",
    status: "implemented",
    proof: "Downloaded Quaternius packs are recorded with local archive path, size, hash, source URL, selected launch use, and per-GLB source evidence for every public launch asset.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/assets/quaternius-asset-provenance.json",
      "apps/aura-clash-showcase/assets/quaternius-selection.json",
      "apps/aura-clash-showcase/assets/quaternius-staged-manifest.json",
    ],
  },
  {
    id: "launch-glb-source-evidence",
    label: "Launch GLB source evidence",
    status: "implemented",
    proof: "Every public launch GLB has source evidence for provenance, license note, thumbnail, bounds, material summary, and intended route usage; playable fighters additionally record typed-GLB delivery, no primitive fallback approval, scale, pivot policy, facing policy, bounds, material readability, and thumbnail evidence.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/aura.assets.json",
      "apps/aura-clash-showcase/scripts/check-production-assets.mjs",
      "apps/aura-clash-showcase/scripts/blender-build-aura-clash-assets.py",
    ],
  },
  {
    id: "gameplay-loop",
    label: "Playable combat loop",
    status: "implemented",
    proof: "The route exposes A/D or arrow-key movement, Space jump, attacks, guard, dash, meter, round timer, AI pressure, restart, P/Escape pause, and result states.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/styles.css",
      "apps/aura-clash-showcase/playable/index.html",
    ],
  },
  {
    id: "runtime-node-mutation",
    label: "Runtime node mutation evidence",
    status: "implemented",
    proof: "The playable route mounts typed GLB fighter models once with game.runtimeNode IDs, mutates Aura app node handles from AuraClashGame body/state snapshots, and exports JSON proving no per-frame setScene/GLB reload path is used for gameplay updates.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/game/AuraClashGame.ts",
      "apps/aura-clash-showcase/src/game/CameraDirector.ts",
      "apps/aura-clash-showcase/src/game/HitboxSystem.ts",
      "apps/aura-clash-showcase/src/scenes/createFighterNodes.ts",
    ],
  },
  {
    id: "browser-evidence-route-runtime-debug",
    label: "Browser evidence route runtime debug source",
    status: "implemented",
    proof: "The evidence route DOM displays hitbox event counts, guard/miss/body-separation counts, animation states, and kinematic body position/velocity values from AuraClashRuntimeEvidence.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/game/AuraClashGame.ts",
      "apps/aura-clash-showcase/src/game/types.ts",
    ],
  },
  {
    id: "route-surface",
    label: "Showcase routes",
    status: "implemented",
    proof: "Playable, evidence, accessibility, deploy-check, and poster route HTML entry points exist for static hosting.",
    files: [
      "apps/aura-clash-showcase/playable/index.html",
      "apps/aura-clash-showcase/evidence/index.html",
      "apps/aura-clash-showcase/accessibility/index.html",
      "apps/aura-clash-showcase/deploy-check/index.html",
      "apps/aura-clash-showcase/poster/index.html",
    ],
  },
  {
    id: "accessibility-controls",
    label: "Accessibility controls",
    status: "implemented",
    proof: "Reduced motion, reduced flash, and high contrast toggles are available in the game UI; reduced motion also suppresses scene/camera animation where practical.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/styles.css",
      "apps/aura-clash-showcase/accessibility/index.html",
    ],
  },
  {
    id: "test-scaffold",
    label: "Route and capture test scaffold",
    status: "implemented",
    proof: "Playwright specs are scaffolded for route health, playable smoke, accessibility, deploy check, and screenshot capture.",
    files: [
      "apps/aura-clash-showcase/playwright.config.ts",
      "apps/aura-clash-showcase/tests/route-health.spec.ts",
      "apps/aura-clash-showcase/tests/playable-smoke.spec.ts",
      "apps/aura-clash-showcase/tests/accessibility.spec.ts",
      "apps/aura-clash-showcase/tests/deploy-check.spec.ts",
      "apps/aura-clash-showcase/tests/screenshot.spec.ts",
    ],
  },
  {
    id: "visual-qa",
    label: "10/10 visual QA",
    status: "needs-visual-qa",
    proof: "The implementation has not been browser-reviewed or screenshot-approved in this pass.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/styles.css",
      "apps/aura-clash-showcase/tests/screenshot.spec.ts",
    ],
  },
];

export const auraClashAcceptanceGates: AuraClashEvidenceItem[] = [
  {
    id: "asset-integrity",
    label: "Asset integrity",
    status: "implemented",
    proof: "Source GLBs, public GLBs, selected Quaternius files, and typed asset registry files exist in the app structure.",
    files: [
      "apps/aura-clash-showcase/assets/source",
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/public/aura-assets",
      "apps/aura-clash-showcase/src/aura-assets.ts",
    ],
  },
  {
    id: "fighter-source-validation",
    label: "Playable fighter source validation",
    status: "implemented",
    proof: "The source evidence manifest records all six playable fighters as typed GLBs with no approved primitive fallback, plus production gate source, scale, pivot policy, facing policy, bounds, material readability, and thumbnail evidence.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/scripts/check-production-assets.mjs",
      "apps/aura-clash-showcase/scripts/blender-build-aura-clash-assets.py",
      "apps/aura-clash-showcase/aura.assets.json",
    ],
  },
  {
    id: "public-api",
    label: "Public Aura3D API usage",
    status: "implemented",
    proof: "The showcase uses createAuraApp, scene, model, camera, lights, and effects from @aura3d/engine with typed assets.",
    files: ["apps/aura-clash-showcase/src/main.ts"],
  },
  {
    id: "browser-qa",
    label: "Browser visual approval",
    status: "needs-visual-qa",
    proof: "Requires explicit browser/screenshot review before declaring the flagship showcase complete.",
    files: ["apps/aura-clash-showcase/tests/screenshot.spec.ts"],
  },
  {
    id: "marketing-promotion",
    label: "Marketing promotion",
    status: "pending",
    proof: "Main Aura3D marketing integration should wait until the game route is visually approved.",
    files: ["docs/project/aura-clash-showcase.md"],
  },
];
