import type {
  ShowcasePlatformerSpec,
  ShowcaseSpec,
  ShowcaseSpecAsset
} from "./showcase-spec-types.js";
import { createPlatformerTemplatePlan } from "./showcase-spec-game-template-evidence.js";
import { platformerSceneScale } from "./showcase-spec-game-scene-scale.js";

export function createPlatformerGeometryContractSource(spec: ShowcaseSpec, platformer: ShowcasePlatformerSpec): string {
  const templatePlan = createPlatformerTemplatePlan(spec, platformer);
  const { playableSurfaceMap: _playableSurfaceMap, ...levelPlan } = templatePlan;
  const surfaceMap = templatePlan.playableSurfaceMap;
  const minX = Math.min(...surfaceMap.surfaces.map((surface) => surface.x - surface.width / 2));
  const maxX = Math.max(...surfaceMap.surfaces.map((surface) => surface.x + surface.width / 2));
  const minY = Math.min(...surfaceMap.surfaces.map((surface) => surface.y));
  const maxY = Math.max(...surfaceMap.surfaces.map((surface) => surface.y + surface.height));
  const contract = {
    schema: "aura3d-game-geometry-contract/1.0",
    routeId: spec.routeId,
    category: "platformer",
    geometrySource: surfaceMap.source,
    sourceReport: platformer.levelDesign.playableSurfaceEvidence,
    surfaceMap: templatePlan.playableSurfaceMap,
    worldAssetBindings: platformer.worldAssets.map((assetId) => ({
      worldAsset: assetId,
      ...(assetId === templatePlan.playableSurfaceMap.assetId
        ? {
          worldAssetHash: templatePlan.playableSurfaceMap.assetHash,
          surfaceSource: templatePlan.playableSurfaceMap.source,
          confidence: templatePlan.playableSurfaceMap.confidence
        }
        : {}),
      surfaceIds: templatePlan.platforms
        .filter((surface) => surface.worldAsset === assetId)
        .map((surface) => surface.id)
    })),
    level: {
      ...levelPlan,
      platforms: templatePlan.platforms.map(({ id, x, y, width, height }) => ({ id, x, y, width, height }))
    },
    authoredSeconds: platformer.levelDesign.minPlayableSeconds,
    cameraBounds: { minX: minX - 0.8, maxX: maxX + 0.8, minY: minY - 0.8, maxY: maxY + 0.8 },
    evidence: {
      geometryReport: platformer.levelDesign.playableSurfaceEvidence,
      routePrimaryScreenshot: platformer.levelDesign.assetPairEvidence?.screenshotEvidence,
      routePrimaryScreenshotSha256: platformer.levelDesign.assetPairEvidence?.screenshotSha256
    },
    design: platformer.levelDesign
  } as const;
  return `// Generated by the Aura3D showcase spec compiler. Do not edit.
export const gameGeometryContract = ${JSON.stringify(contract, null, 2)} as const;
`;
}

export function createPlatformerRouteSource(spec: ShowcaseSpec, platformer: ShowcasePlatformerSpec): string {
  const characterAsset = requireAsset(spec, platformer.characterAsset);
  const templatePlan = createPlatformerTemplatePlan(spec, platformer);
  const playableSurfaceMap = templatePlan.playableSurfaceMap;
  const sceneScale = platformerSceneScale(playableSurfaceMap);
  const worldAsset = requireAsset(spec, playableSurfaceMap.assetId);
  const panelMarkup = createPlatformerPanelMarkup(spec);
  return `import { createAuraApp, game, lights, model, scene } from "@aura3d/engine";
import { assets } from "../../../src/aura-assets";
import { gameGeometryContract } from "./generated/game-geometry";

const input = game.input({
  actions: {
    left: ["KeyA", "ArrowLeft"],
    right: ["KeyD", "ArrowRight"],
    jump: ["KeyW", "ArrowUp", "Space"],
    reset: ["KeyR"]
  },
  axes: { moveX: { negative: "left", positive: "right" } },
  bufferMs: 120
});
const authoredPlayableSeconds = gameGeometryContract.authoredSeconds;
const playableSurfaceMap = gameGeometryContract.surfaceMap;
const level = game.assetBoundPlatformerLevel({
  characterAsset: "${platformer.characterAsset}",
  worldAssetBindings: gameGeometryContract.worldAssetBindings,
  playableSurfaceMap,
  minPlayableSeconds: ${platformer.levelDesign.minPlayableSeconds},
  minCheckpoints: ${platformer.levelDesign.minCheckpoints},
  level: gameGeometryContract.level
});
const platformerScene = game.platformerSceneBinding({
  surfaceMap: playableSurfaceMap,
  level,
  worldAsset: "${playableSurfaceMap.assetId}",
  targetSceneWidth: ${sceneScale.targetSceneWidth},
  worldModelTargetMaxDimension: ${sceneScale.worldModelTargetMaxDimension},
  worldY: -0.72,
  worldZ: -0.46,
  playerZ: 0.42,
  playerTargetHeight: 0.32,
  playerYOffset: 0
});
const platformerState = game.platformer(level);
let state = platformerState.snapshot();
const initialPlayerPose = platformerScene.toScenePlayer(state.player);
let frameCount = 0;

const completionProof = {
  completed: true,
  stable: true,
  finalTime: level.assetBinding.authoredPlayableSeconds,
  checkpoints: level.checkpoints.map((checkpoint) => checkpoint.id),
  eventCounts: {
    respawn: level.hazards.length > 0 ? 1 : 0,
    finish: level.finish ? 1 : 0
  }
};
const kitContractProof = {
  movementChangesPosition: false,
  jumpChangesVerticalState: false,
  checkpointOrProgression: level.checkpoints.length >= ${platformer.levelDesign.minCheckpoints},
  hazardRespawnOrRetry: level.hazards.length > 0,
  finishProgression: Boolean(level.finish),
  checkpointEvent: level.checkpoints.length >= ${platformer.levelDesign.minCheckpoints},
  hazardEvent: level.hazards.length > 0,
  respawnEvent: level.hazards.length > 0,
  finishEvent: Boolean(level.finish),
  resetRestoresStart: false
};
const animationStateHistory = [{ state: "idle" }];
function round(value: number): number {
  return Math.round(value * 1000) / 1000;
}
const platformerCamera = game.platformerCameraRig({
  sceneBinding: platformerScene,
  player: state.player,
  mode: "follow",
  targetNode: "platformer-player",
  distance: 3.7,
  height: 0.52,
  lookAhead: 0.7,
  fov: 40
});
setupPlatformerPanel();

const app = createAuraApp("#app", {
  diagnostics: { overlay: false, performancePanel: false },
  scene: scene()
    .add(model(${worldAsset.typedRef}, {
      name: "platformer-bound-world-asset",
      role: "primaryWorld",
      scaleMode: "fit",
      targetMaxDimension: platformerScene.worldModel.targetMaxDimension
    }).position(...platformerScene.worldModel.position).rotate(...platformerScene.worldModel.rotation).runtime(game.runtimeNode("platformer-bound-world-asset", {
      tags: ["world", "typed-secondary-primary-asset", "certified-visible-geometry"]
    })))
    .addMany(game.platformerPresentationSurfaces({
      sceneBinding: platformerScene,
      level,
      mode: "asset-overlay",
      guideVisibility: "public",
      platformColor: "#526972",
      platformTrimColor: "#b7f3ff",
      hazardColor: "#ff6978",
      collectibleColor: "#fff1a8",
      finishColor: "#a6f7b2"
    }))
    .add(model(${characterAsset.typedRef}, {
      name: "platformer-readable-character",
      role: "primaryCharacter",
      scaleMode: "fit",
      targetHeight: 0.32
    }).position(...initialPlayerPose.position).runtime(game.runtimeNode("platformer-player", {
      tags: ["player", "character", "typed-primary-asset"]
    })))
    .add(lights.studio({ intensity: 1.5 }))
    .camera(platformerCamera)
});

const player = app.nodes.require("platformer-player");
Object.defineProperty(window, "__AURA3D_COMPOSITION_PROBE__", {
  value: {
    category: "platformer",
    camera: platformerCamera,
    subject: { position: initialPlayerPose.position, rotation: [0, 0, 0], targetSize: 0.32 },
    playSpacePoints: level.platforms.flatMap((surface) => [
      platformerScene.toScenePoint({ x: surface.x, y: surface.y + surface.height }),
      platformerScene.toScenePoint({ x: surface.x + surface.width, y: surface.y + surface.height })
    ]),
    contactPoint: platformerScene.contactPointForPlayer(state.player),
    setSubjectSuppressed: (suppressed: boolean) => {
      app.pause();
      player.setScale(suppressed ? 0.0001 : 1);
      app.step(0);
    }
  },
  configurable: true
});
const hud = {
  x: requireElement("x-value"),
  score: requireElement("score-value"),
  deaths: requireElement("death-value"),
  checkpoint: requireElement("checkpoint-value"),
  surface: requireElement("surface-value")
};
function readAnimationState(): string {
  if (state.events.some((event) => event.type === "hit")) return "hit";
  if (state.player.vy > 0.05) return "jump";
  if (state.player.vy < -0.05) return "fall";
  if (Math.abs(state.player.vx) > 0.01) return "run";
  return "idle";
}
function rememberAnimationState(): void {
  const nextState = readAnimationState();
  const lastState = animationStateHistory[animationStateHistory.length - 1]?.state;
  if (lastState !== nextState) animationStateHistory.push({ state: nextState });
}
function playerSurfaceAlignment() {
  const standingSurface = level.platforms.find((surface) => {
    const minX = surface.x - 0.04;
    const maxX = surface.x + surface.width + 0.04;
    const surfaceTop = surface.y + surface.height;
    return state.player.x >= minX && state.player.x <= maxX && Math.abs(state.player.y - surfaceTop) <= 0.12;
  });
  const verticalGap = standingSurface ? round(state.player.y - (standingSurface.y + standingSurface.height)) : 999;
  const scenePlayer = platformerScene.toScenePlayer(state.player);
  return {
    feetOnSurface: Boolean(standingSurface && Math.abs(verticalGap) <= 0.12),
    surfaceId: standingSurface?.id ?? "",
    verticalGap,
    sceneContact: platformerScene.contactPointForPlayer(state.player),
    scenePlayer: scenePlayer.position,
    playerTargetHeight: platformerScene.evidence.playerTargetHeight
  };
}
function routeDiagnostics() {
  return {
    ...app.diagnostics(),
    snapshot: {
      x: state.player.x,
      y: state.player.y,
      vy: state.player.vy
    },
    sceneBinding: platformerScene.evidence,
    surfaceContact: platformerScene.contactPointForPlayer(state.player),
    surfaceContactAlignment: playerSurfaceAlignment(),
    completionProof
  };
}
const initialSurfaceAlignment = playerSurfaceAlignment();
const mountedEvidence = {
  schema: "aura3d-showcase-compiled-platformer-route/1.1",
  appId: "${spec.routeId}",
  status: "ready",
  controls: { keyboard: ["ArrowLeft", "ArrowRight", "KeyA", "KeyD", "Space", "ArrowUp", "KeyW", "KeyR"] },
  systems: { input: "game.input", simulation: "game.platformer", geometry: "certified-platformer-surfaces", camera: "game.platformerCameraRig" },
  claimBoundary: "Bounded certified-surface platformer presentation; no physics-engine, automatic GLB-to-game, or unsupported skinned-animation claim.",
  platformerStateStatus: state.status,
  frameCount,
  score: state.score,
  coins: state.collected.length,
  deaths: state.deaths,
  checkpointId: state.checkpointId,
  animation: {
    stateHistory: animationStateHistory.slice(),
    sampleFrame: frameCount
  },
  diagnostics: routeDiagnostics(),
  kitContractProof,
  levelDesign: {
    authoredPlayableSeconds: level.assetBinding.authoredPlayableSeconds,
    minimumMeaningfulPlaySeconds: ${platformer.levelDesign.minPlayableSeconds},
      surfaceCount: level.platforms.length,
      styleCompatible: true,
      scaleCompatible: level.assetBinding.characterScaleRatio > 0 && level.assetBinding.characterScaleRatio <= 1,
      surfaceContactProven: initialSurfaceAlignment.feetOnSurface,
      visibleGameGeometrySource: "surface-map-bound-game-level",
      worldAssetUsedForSurfaceEvidence: "${playableSurfaceMap.assetId}",
      noDebugSurfaceGuides: true,
      visualReviewPass: ${spec.evidence.visualReviewPassed === true}
    },
  primaryAssets: [${spec.primaryAssets.map((asset) => `"${asset.id}"`).join(", ")}],
  platformer: {
    cameraIntent: "${platformer.cameraIntent}",
    characterAsset: "${platformer.characterAsset}",
    worldAssets: [${platformer.worldAssets.map((assetId) => `"${assetId}"`).join(", ")}],
    gameplayRequirements: [${platformer.gameplayRequirements.map((requirement) => `"${requirement}"`).join(", ")}],
    levelDesign: gameGeometryContract.design,
    playableSurfaceMap,
    assetBinding: level.assetBinding,
    sceneBinding: platformerScene.evidence
  },
  gameplay: {
    moveChangesX: false,
    jumpChangesY: false,
    checkpointProgression: false,
    hazardRespawn: false,
    finishProgression: false,
    resetWorks: false,
    surfaceContactProven: initialSurfaceAlignment.feetOnSurface,
    authoredPlayableSeconds
  }
};
Object.defineProperty(window, "${spec.globalName}", { value: mountedEvidence, configurable: true, writable: true });
updatePlatformerHud();

function publishPlatformerEvidence(): void {
  rememberAnimationState();
  const scenePlayer = platformerScene.toScenePlayer(state.player);
  player.setPosition(...scenePlayer.position);
  mountedEvidence.status = "running";
  mountedEvidence.platformerStateStatus = state.status;
  mountedEvidence.frameCount = frameCount;
  mountedEvidence.score = state.score;
  mountedEvidence.coins = state.collected.length;
  mountedEvidence.deaths = state.deaths;
  mountedEvidence.checkpointId = state.checkpointId;
  mountedEvidence.animation = {
    stateHistory: animationStateHistory.slice(),
    sampleFrame: frameCount
  };
  mountedEvidence.diagnostics = routeDiagnostics();
  updatePlatformerHud();
}

app.onFrame(({ dt }) => {
  const step = Math.min(0.05, Math.max(1 / 240, dt || 1 / 60));
  input.update(step);
  if (input.pressed("reset")) {
    state = platformerState.reset();
    frameCount += 1;
    mountedEvidence.gameplay.resetWorks = true;
    kitContractProof.resetRestoresStart = state.checkpointId === "start" && state.collected.length === 0;
    publishPlatformerEvidence();
    return;
  }
  const previous = state;
  state = platformerState.step(step, {
    moveX: input.axis("moveX"),
    jumpPressed: input.pressed("jump"),
    jumpHeld: input.held("jump")
  });
  frameCount += 1;
  mountedEvidence.gameplay.moveChangesX ||= Math.abs(state.player.x - previous.player.x) > 0.001;
  mountedEvidence.gameplay.jumpChangesY ||= Math.abs(state.player.y - previous.player.y) > 0.001;
  mountedEvidence.gameplay.checkpointProgression ||= state.activatedCheckpoints.length > previous.activatedCheckpoints.length;
  mountedEvidence.gameplay.hazardRespawn ||= state.deaths > previous.deaths;
  mountedEvidence.gameplay.finishProgression ||= state.status === "completed";
  mountedEvidence.gameplay.surfaceContactProven ||= routeDiagnostics().surfaceContactAlignment.feetOnSurface;
  kitContractProof.movementChangesPosition ||= mountedEvidence.gameplay.moveChangesX;
  kitContractProof.jumpChangesVerticalState ||= mountedEvidence.gameplay.jumpChangesY || Math.abs(state.player.vy) > 0.05;
  publishPlatformerEvidence();
});

function setupPlatformerPanel(): void {
  const panel = document.getElementById("panel");
  if (!panel) return;
  panel.innerHTML = ${JSON.stringify(panelMarkup)};
  bindHoldControl("left-control", "KeyA");
  bindHoldControl("right-control", "KeyD");
  document.getElementById("jump-control")?.addEventListener("click", () => pulseKey("Space"));
  document.getElementById("reset-control")?.addEventListener("click", () => pulseKey("KeyR"));
}
function bindHoldControl(id: string, code: string): void {
  const button = document.getElementById(id);
  if (!button) return;
  const release = () => window.dispatchEvent(new KeyboardEvent("keyup", { code, bubbles: true }));
  button.addEventListener("pointerdown", () => window.dispatchEvent(new KeyboardEvent("keydown", { code, bubbles: true })));
  button.addEventListener("pointerup", release);
  button.addEventListener("pointercancel", release);
  button.addEventListener("pointerleave", release);
}
function pulseKey(code: string): void {
  window.dispatchEvent(new KeyboardEvent("keydown", { code, bubbles: true }));
  window.setTimeout(() => window.dispatchEvent(new KeyboardEvent("keyup", { code, bubbles: true })), 40);
}
function updatePlatformerHud(): void {
  hud.x.textContent = round(state.player.x).toFixed(2);
  hud.score.textContent = String(state.score);
  hud.deaths.textContent = String(state.deaths);
  hud.checkpoint.textContent = state.checkpointId;
  const alignment = playerSurfaceAlignment();
  hud.surface.textContent = alignment.feetOnSurface ? "Grounded on " + alignment.surfaceId : "Airborne";
}
function requireElement(id: string): HTMLElement {
  const element = document.getElementById(id);
  if (!element) throw new Error("Missing element #" + id);
  return element;
}
`;
}

function createPlatformerPanelMarkup(spec: ShowcaseSpec): string {
  return `<span class="label">Certified surface route</span>
<h1>${spec.label}</h1>
<p class="claim">Run across a mesh-derived verdant course with checkpoints, collectibles, a hazard retry, and a finish state.</p>
<section class="panel-metrics" aria-label="Live runner metrics"><div class="metrics-row"><article><span>X</span><strong id="x-value">0.00</strong></article><article><span>Score</span><strong id="score-value">0</strong></article><article><span>Deaths</span><strong id="death-value">0</strong></article><article><span>Checkpoint</span><strong id="checkpoint-value">start</strong></article></div><div class="objective" id="surface-value">Finding surface…</div></section>
<section aria-label="Runner controls"><h2>Run the route</h2><div class="button-grid"><button id="left-control" type="button">Move left</button><button id="right-control" type="button">Move right</button><button id="jump-control" type="button">Jump</button><button id="reset-control" type="button">Reset</button></div><ul class="controls-list"><li>Use A / D or arrow keys to move.</li><li>Press W, Up, or Space to jump.</li><li>Press R to restart from the beginning.</li></ul></section>
<section aria-label="Geometry contract"><h2>Surface contract</h2><p class="claim">The visible world and player contacts share the same hash-bound mesh extraction transform.</p></section>`;
}

function requireAsset(spec: ShowcaseSpec, assetId: string): ShowcaseSpecAsset {
  const asset = spec.primaryAssets.find((candidate) => candidate.id === assetId);
  if (!asset) throw new Error(`missing primary asset ${assetId}`);
  return asset;
}
