// Deprecated subpath: keeps its pre-collapse surface until removeIn 4.1.0; new imports belong on ./renderer.
// Generated by tools/generate-resolution-maps — edit aura.exports.json instead.
const key = "@aura3d/engine/rendering";
const warned = ((globalThis as { __a3dDeprecatedSubpaths?: Set<string> }).__a3dDeprecatedSubpaths ??= new Set<string>());
if (!warned.has(key)) {
  warned.add(key);
  // eslint-disable-next-line no-console
  console.warn(`[aura3d] ${key} is deprecated and resolves to ./renderer; it will be removed in 4.1.0.`);
}
export * from "@aura3d/rendering";
