import { dirname, posix } from "node:path";
import * as ts from "typescript";
import type { AuraCodemod } from "../../../contracts/commands.js";

/**
 * PRD-05 §6.8/R11 — `assets-route-modules` codemod (C-39).
 * Rewrites `import { assets } from "<…>/src/aura-assets"` specifiers to the
 * route-scoped module emitted by `aura3d assets typegen --route apps/<app>`
 * (`apps/<app>/src/aura-assets.route.ts`). Pure `source → code + rows`.
 */

const ROUTE_MODULE_BASENAME = "aura-assets.route";

type CodemodResult = ReturnType<AuraCodemod["transform"]>;
type CodemodRow = CodemodResult["rows"][number];

export const assetsRouteModulesCodemod: AuraCodemod = {
  name: "assets-route-modules",
  owner: "prd05",
  description:
    "Rewrite monolithic `src/aura-assets` imports to the route-scoped `aura-assets.route` module emitted by `assets typegen --route`.",
  transform(source: string, fileName: string): CodemodResult {
    const normalized = fileName.replace(/\\/g, "/");
    const routeModuleDir = routeModuleDirFor(normalized);
    const sourceFile = ts.createSourceFile(normalized, source, ts.ScriptTarget.Latest, true);
    const edits: { start: number; end: number; text: string }[] = [];
    const rows: CodemodRow[] = [];

    for (const statement of sourceFile.statements) {
      if (!ts.isImportDeclaration(statement)) continue;
      const specifier = statement.moduleSpecifier;
      if (!ts.isStringLiteral(specifier)) continue;
      const modulePath = specifier.text;
      if (!isMonolithicAssetsSpecifier(modulePath)) continue;
      const line = sourceFile.getLineAndCharacterOfPosition(specifier.getStart(sourceFile)).line + 1;
      if (routeModuleDir === undefined) {
        rows.push({
          file: normalized,
          line,
          construct: `import ${JSON.stringify(modulePath)}`,
          mapping: "none",
          note: "file is not under an apps/<name>/ or src/ root; run `assets typegen --route` manually and point this import at its aura-assets.route module",
        });
        continue;
      }
      const target = relativeSpecifier(dirname(normalized), `${routeModuleDir}/${ROUTE_MODULE_BASENAME}`);
      edits.push({ start: specifier.getStart(sourceFile), end: specifier.getEnd(), text: JSON.stringify(target) });
      rows.push({
        file: normalized,
        line,
        construct: `import ${JSON.stringify(modulePath)}`,
        mapping: "exact",
        target,
        note: `route module generated by \`assets typegen --route ${routeModuleDir.replace(/\/src$/, "")}\``,
      });
    }

    if (edits.length === 0) return { code: source, rows };
    let code = source;
    for (const edit of edits.sort((a, b) => b.start - a.start)) {
      code = code.slice(0, edit.start) + edit.text + code.slice(edit.end);
    }
    return { code, rows };
  },
};

/** `../../../src/aura-assets`, `../aura-assets`, `src/aura-assets` — not `.route`. */
function isMonolithicAssetsSpecifier(specifier: string): boolean {
  const trimmed = specifier.replace(/\.(ts|js|mjs|d\.ts)$/i, "");
  return trimmed.endsWith("/aura-assets") || trimmed === "aura-assets";
}

/**
 * Route module lives at `<route>/src/aura-assets.route.ts`.
 * - `apps/<app>/...` → `apps/<app>/src/aura-assets.route`
 * - `<root>/src/...` (templates, fixtures) → `<root>/src/aura-assets.route`
 */
function routeModuleDirFor(fileName: string): string | undefined {
  const appMatch = /(^|\/)apps\/[^/]+(?=\/|$)/.exec(fileName);
  if (appMatch) {
    const prefix = fileName.slice(0, appMatch.index + appMatch[0].length);
    return `${prefix}/src`;
  }
  const srcIndex = fileName.indexOf("/src/");
  if (srcIndex >= 0) return fileName.slice(0, srcIndex + "/src".length);
  if (fileName.startsWith("src/")) return "src";
  return undefined;
}

function relativeSpecifier(fromDir: string, toModulePath: string): string {
  const normalizedFrom = fromDir.replace(/\\/g, "/");
  let rel = posix.relative(normalizedFrom, toModulePath.replace(/\\/g, "/"));
  if (rel === "") rel = ".";
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}
