import { readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const json = (path: string): any => JSON.parse(readFileSync(resolve(path), "utf8")); const text = (path: string): string => readFileSync(resolve(path), "utf8");
const baseline = json("tests/reports/current-threejs-baseline.json"); const context = json("benchmark/context/threejs-r185.1-20260808.json"); const browser = json("tests/reports/current-head-to-head/custom-material-shader/report.json"); const source = text("benchmark/current-head-to-head/custom-material-shader/main.ts"); const captures = ["aura-before.png", "three-before.png", "aura-after.png", "three-after.png"];
const checks = [
  { id: "current-three-r185", pass: baseline.pass === true && baseline.three?.version === "0.185.1" && browser.before?.three?.revision === "185" },
  { id: "frozen-native-viewport-and-captures", pass: browser.before?.viewport?.width === context.commonRenderContract.viewport.width && browser.before?.viewport?.height === context.commonRenderContract.viewport.height && browser.before?.viewport?.dpr === context.commonRenderContract.devicePixelRatio && captures.every((name) => statSync(resolve(`tests/reports/current-head-to-head/custom-material-shader/${name}`)).size > 10_000) },
  { id: "public-realistic-stacks", pass: source.includes('from "@aura3d/rendering"') && source.includes('from "three"') && source.includes("PortableShaderMaterial") && source.includes("THREE.ShaderMaterial") && !source.includes("packages/") && !source.includes("createProgram(") && browser.before?.aura?.compileOk === true && browser.before?.three?.actualShaderMaterial === true },
  { id: "native-custom-shader-submissions", pass: browser.before?.aura?.actualCompiledShaderProgram === true && browser.before?.aura?.drawCalls === 1 && browser.before?.aura?.deviceDrawCalls > 0 && browser.before?.three?.actualCompiledShaderProgram === true && browser.before?.three?.drawCalls === 1 && browser.before?.three?.triangles > 3_000 },
  { id: "paired-uniform-pixel-change", pass: browser.after?.interaction?.applied === true && browser.before?.aura?.time === browser.before?.three?.time && browser.after?.aura?.time === browser.after?.three?.time && browser.before?.aura?.pixelHash !== browser.after?.aura?.pixelHash && browser.before?.three?.pixelHash !== browser.after?.three?.pixelHash },
  { id: "caller-owned-resource-disposal", pass: Object.values(browser.lifecycle ?? {}).every(Boolean) && Object.keys(browser.lifecycle ?? {}).length === 7 }
];
const failures = checks.filter((entry) => !entry.pass); const report = { schema: "aura3d.current-head-to-head-custom-material-shader/1.0", generatedAt: new Date().toISOString(), pass: failures.length === 0, workload: "custom-material-shader", verdict: "both-submit-native-custom-shaders", checks, failures, comparison: { auraDrawCalls: browser.before?.aura?.drawCalls, threeDrawCalls: browser.before?.three?.drawCalls, observedLosses: ["Aura's portable material requires explicit paired GLSL and WGSL stages while this Three.js WebGL ShaderMaterial workload requires one GLSL pair.", "The paired captures are not pixel-equivalent: Three.js is visibly brighter and more magenta while Aura is darker and bluer under the same authored shader colors, so renderer color/output parity is not established.", "This proves one selected custom shader, uniform update, and lifecycle path; it does not establish Three.js TSL/node-material ecosystem parity, WebGPU parity, visual parity, or performance non-inferiority."], claimBoundary: "Public low-level rendering-package proof, not root createAuraApp proof." }, browser }; const output = resolve("tests/reports/current-head-to-head/custom-material-shader/aggregate.json"); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); if (failures.length) { console.error(`Custom shader head-to-head UNPROVEN: ${failures.map((entry) => entry.id).join(", ")}`); process.exitCode = 1; } else console.log(`Custom shader head-to-head PASS: ${checks.length}/${checks.length}; ${output}`);
