export { AnimationClipThreeCompat } from "./AnimationClip";
export type { ThreeCompatKeyframeTrack, ThreeCompatLoopMode } from "./AnimationClip";
export { AnimationActionThreeCompat } from "./AnimationAction";
export { AnimationMixerThreeCompat } from "./AnimationMixer";
export { SkeletonThreeCompat } from "./Skeleton";
export type { ThreeCompatBone } from "./Skeleton";
export { SkinnedMeshThreeCompat } from "./SkinnedMesh";
export { MorphTargetMixerThreeCompat } from "./MorphTargetMixer";
export type { ThreeCompatMorphTargetWeight } from "./MorphTargetMixer";
export { createThreeCompatAnimationDiagnostics, inspectThreeCompatAnimatedAssets, THREE_COMPAT_ANIMATED_GLTF_ASSETS } from "./AnimationDiagnostics";
export type { ThreeCompatAnimatedAssetDiagnostic } from "./AnimationDiagnostics";
