/**
 * Dependency-bound evidence freshness.
 *
 * ## Why this exists
 *
 * `apps/aura-clash-showcase/launch-evidence/first-frame.png` was regenerated by one producer into an
 * old-looking visual while a different, current visual-regression producer rendered the correct
 * textured arena. Re-running the intended producer corrected the file, but the incident proved three
 * structural faults, none of which is fixed by regenerating anything:
 *
 * 1. Two producers could write semantically overlapping evidence at the same path.
 * 2. Stale output could appear current, because freshness was inferred from *modification time*.
 * 3. Nothing bound an artifact to the implementation, asset, config or renderer it validated.
 *
 * A modification time proves only that a file was written. It cannot distinguish "regenerated from the
 * current implementation" from "regenerated by the wrong producer" or "regenerated after the asset
 * changed but before the route did". So freshness here is a **dependency fingerprint**: an artifact
 * records the hashes of everything it depends on, and is stale when any of them no longer match.
 *
 * A second, subtler fault this module makes visible: the route-primary probe records a hash of
 * `route-health.json`, and the composition regenerator *writes that same file*. Running the documented
 * order (probe, then composition) therefore always leaves the probe describing a file the next step
 * mutates, permanently invalidating its own binding. That is a producer-ordering cycle, and it is
 * reported as a distinct, named cause rather than as a generic mismatch, because the fix is an ordering
 * change and not a regeneration.
 */
import { createHash, randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

export const EVIDENCE_FRESHNESS_SCHEMA = "aura3d-evidence-freshness/1.0";

/** Dependency kinds an artifact can be bound to. Each has a distinct staleness meaning. */
export const DEPENDENCY_KINDS = Object.freeze([
  "route-source",
  "route-gate-config",
  "route-health",
  "primary-asset",
  "renderer-fingerprint",
  "camera-config",
  "producer-version",
  "viewport-contract",
  "screenshot"
]);

/**
 * Files whose content defines rendered output.
 *
 * Deliberately a *declared* list rather than "everything in packages/": a fingerprint over the whole
 * repository would change on every unrelated edit and train readers to ignore staleness reports. These
 * are the modules that actually decide what a frame looks like.
 */
export const RENDERER_FINGERPRINT_SOURCES = Object.freeze([
  "packages/engine/src/agent-api/index.ts",
  "packages/engine/src/agent-api/SceneGroundingUtils.ts",
  "packages/engine/src/agent-api/SubjectFramingUtils.ts",
  "packages/engine/src/agent-api/LayeredSceneComposition.ts",
  "packages/engine/src/agent-api/GameSceneGeometryBindings.ts",
  "packages/engine/src/agent-api/GameSceneGeometryMath.ts",
  "packages/engine/src/production-runtime/TypedGLBActor.ts",
  "packages/engine/src/production-runtime/GameRenderPreset.ts",
  "packages/assets/src/GLTFRenderResources.ts",
  "packages/assets/src/GLTFLoader.ts"
]);

export function sha256(buffer) {
  return `sha256-${createHash("sha256").update(buffer).digest("hex")}`;
}

export function hashFileIfPresent(absolutePath) {
  return existsSync(absolutePath) ? sha256(readFileSync(absolutePath)) : undefined;
}

/**
 * Fingerprint the renderer code that determines pixel output.
 *
 * Path-then-content so moving a file changes the fingerprint too: a rename can change which module
 * wins resolution without changing any bytes.
 */
export function createRendererFingerprint(root = process.cwd(), sources = RENDERER_FINGERPRINT_SOURCES) {
  const hash = createHash("sha256");
  let present = 0;
  for (const relativePath of [...sources].sort()) {
    const absolute = resolve(root, relativePath);
    if (!existsSync(absolute)) continue;
    present += 1;
    hash.update(relativePath);
    hash.update("\0");
    hash.update(readFileSync(absolute));
    hash.update("\0");
  }
  // A fingerprint over zero files would silently compare equal everywhere.
  if (present === 0) return "sha256-no-renderer-sources";
  return `sha256-${hash.digest("hex")}`;
}

/**
 * Fingerprint a producer: its own source plus a caller-declared version.
 *
 * The version alone is not enough (nobody remembers to bump it); the source alone is not enough
 * (a deliberate output-format change should invalidate artifacts even if refactoring left bytes
 * equivalent). Both together make "the producer changed" detectable.
 */
export function createProducerFingerprint(producerRelativePath, version, root = process.cwd()) {
  const absolute = resolve(root, producerRelativePath);
  const hash = createHash("sha256");
  hash.update(String(version));
  hash.update("\0");
  hash.update(producerRelativePath);
  hash.update("\0");
  if (existsSync(absolute)) hash.update(readFileSync(absolute));
  return `sha256-${hash.digest("hex")}`;
}

/** Stable hash of a plain config object, key-order independent. */
export function createConfigFingerprint(config) {
  return sha256(Buffer.from(stableStringify(config), "utf8"));
}

function stableStringify(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  const keys = Object.keys(value).filter((key) => value[key] !== undefined).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;
}

/**
 * Build the freshness block an artifact embeds.
 *
 * `dependencies` is a list of `{ kind, id, hash }`. Callers pass the *current* values at generation
 * time; validation later recomputes them and compares.
 */
export function createFreshnessBinding(options) {
  const dependencies = (options.dependencies ?? [])
    .filter((dependency) => dependency && dependency.hash !== undefined)
    .map((dependency) => ({
      kind: String(dependency.kind),
      id: String(dependency.id),
      hash: String(dependency.hash)
    }))
    .sort((a, b) => (a.kind === b.kind ? a.id.localeCompare(b.id) : a.kind.localeCompare(b.kind)));
  for (const dependency of dependencies) {
    if (!DEPENDENCY_KINDS.includes(dependency.kind)) {
      throw new Error(`Unknown evidence dependency kind "${dependency.kind}". Known: ${DEPENDENCY_KINDS.join(", ")}`);
    }
  }
  return {
    schema: EVIDENCE_FRESHNESS_SCHEMA,
    artifact: options.artifact,
    producer: {
      id: options.producerId,
      version: String(options.producerVersion),
      fingerprint: options.producerFingerprint
    },
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    dependencies
  };
}

/**
 * Explain why an artifact is stale, dimension by dimension.
 *
 * Returns every mismatch rather than the first, because a single regeneration usually resolves several
 * and a caller needs the full set to know what to re-run. `fresh` is true only when nothing mismatched
 * and nothing was missing -- an unbound artifact is reported as `unbound`, never as fresh, since the
 * whole failure mode being fixed is stale output that *looked* current.
 */
export function explainArtifactStaleness(options) {
  const artifactPath = options.artifactPath;
  const binding = options.binding;
  const current = options.currentDependencies ?? [];
  const reasons = [];

  if (!binding || typeof binding !== "object") {
    return {
      artifact: artifactPath,
      fresh: false,
      unbound: true,
      reasons: [{
        kind: "producer-version",
        id: "freshness-binding",
        status: "missing",
        detail: `${artifactPath} carries no freshness binding, so it cannot be distinguished from stale output. Modification time is not evidence.`
      }],
      producerConflicts: []
    };
  }
  if (binding.schema !== EVIDENCE_FRESHNESS_SCHEMA) {
    reasons.push({
      kind: "producer-version",
      id: "schema",
      status: "mismatch",
      expected: EVIDENCE_FRESHNESS_SCHEMA,
      actual: String(binding.schema),
      detail: `freshness schema is ${String(binding.schema)}, expected ${EVIDENCE_FRESHNESS_SCHEMA}`
    });
  }

  const recorded = new Map((binding.dependencies ?? []).map((dependency) => [`${dependency.kind}:${dependency.id}`, dependency]));

  /*
   * Compare hash *values*, not their spelling.
   *
   * Retained evidence is inconsistent about the `sha256-` prefix: the route-primary probe stores
   * `routeGateHash` bare while storing `sourceHash`, `routeHealthHash` and per-asset `manifestHash`
   * prefixed. Comparing raw strings reported a mismatch between two identical digests, which is worse
   * than a missed staleness: a staleness explainer that cries wolf gets ignored. Normalising here fixes
   * the comparison without rewriting retained artifacts to suit the checker.
   */
  const normalizeHash = (value) => String(value).replace(/^sha256-/, "");
  for (const dependency of current) {
    if (dependency?.hash === undefined) continue;
    const key = `${dependency.kind}:${dependency.id}`;
    const previous = recorded.get(key);
    if (!previous) {
      reasons.push({
        kind: dependency.kind,
        id: dependency.id,
        status: "unbound",
        actual: String(dependency.hash),
        detail: `${artifactPath} does not record ${dependency.kind} "${dependency.id}", so a change to it cannot invalidate this artifact`
      });
      continue;
    }
    if (normalizeHash(previous.hash) !== normalizeHash(dependency.hash)) {
      reasons.push({
        kind: dependency.kind,
        id: dependency.id,
        status: "mismatch",
        expected: String(dependency.hash),
        actual: String(previous.hash),
        detail: `${dependency.kind} "${dependency.id}" changed since ${artifactPath} was generated (recorded ${short(previous.hash)}, current ${short(dependency.hash)})`
      });
    }
    recorded.delete(key);
  }
  for (const [key, dependency] of recorded) {
    reasons.push({
      kind: dependency.kind,
      id: dependency.id,
      status: "removed",
      actual: String(dependency.hash),
      detail: `${artifactPath} records ${key}, which no longer exists in the current dependency set`
    });
  }

  const producerConflicts = options.producerConflicts ?? [];
  for (const conflict of producerConflicts) {
    reasons.push({
      kind: "producer-version",
      id: conflict.path,
      status: "producer-conflict",
      detail: conflict.detail
    });
  }

  return {
    artifact: artifactPath,
    fresh: reasons.length === 0,
    unbound: false,
    reasons,
    producerConflicts
  };
}

function short(hash) {
  const value = String(hash);
  return value.startsWith("sha256-") ? `${value.slice(7, 15)}...` : value.slice(0, 8);
}

/**
 * Write a file atomically.
 *
 * A partially-written artifact is worse than a stale one: it looks like evidence and parses as garbage.
 * Writing to a sibling temp file and renaming makes the replacement atomic on the same filesystem, so a
 * reader sees either the whole previous file or the whole new one.
 */
export function writeArtifactAtomically(absolutePath, contents) {
  mkdirSync(dirname(absolutePath), { recursive: true });
  /*
   * The temp name must be unique per *call*, not per process-millisecond.
   *
   * This was `${absolutePath}.${pid}.${Date.now()}.tmp`, which is not unique: 200 rapid calls in one process
   * produce **one** name, because `Date.now()` has millisecond resolution and the pid is constant. Two writers
   * sharing a temp path is not a theoretical hazard -- the second `writeFileSync` destroys the first writer's
   * staged bytes before it renames, so one artifact silently becomes the other's content while both calls report
   * success. That is the same class of fault as the stale-first-frame incident this module exists to prevent:
   * output that looks written and is wrong.
   *
   * Random suffix plus a monotonic counter: the counter guarantees uniqueness within a process even if the RNG
   * repeats, and the random bytes guarantee it across concurrent processes.
   */
  const temp = `${absolutePath}.${process.pid}.${nextWriteSequence()}.${randomBytes(6).toString("hex")}.tmp`;
  try {
    writeFileSync(temp, contents);
    renameSync(temp, absolutePath);
  } catch (error) {
    if (existsSync(temp)) {
      try { unlinkSync(temp); } catch { /* best effort cleanup */ }
    }
    throw error;
  }
  return absolutePath;
}

/** Monotonic per-process counter for temp-file naming. */
let writeSequence = 0;
function nextWriteSequence() {
  writeSequence += 1;
  return writeSequence;
}

/** Serialize JSON evidence deterministically and write it atomically. */
export function writeJsonArtifactAtomically(absolutePath, value) {
  return writeArtifactAtomically(absolutePath, `${JSON.stringify(value, null, 2)}\n`);
}

/**
 * Detect two producers claiming the same artifact path.
 *
 * `ownership` maps a producer id to the artifact paths it writes. Any path claimed twice is a defect by
 * construction, regardless of whether it has misfired yet: it is exactly the condition that let a stale
 * Aura Clash first frame appear current.
 */
export function findProducerOwnershipConflicts(ownership) {
  const byPath = new Map();
  for (const [producerId, paths] of Object.entries(ownership)) {
    for (const path of paths) {
      const existing = byPath.get(path);
      if (existing) existing.push(producerId);
      else byPath.set(path, [producerId]);
    }
  }
  return [...byPath.entries()]
    .filter(([, producers]) => producers.length > 1)
    .map(([path, producers]) => ({
      path,
      producers: [...producers].sort(),
      detail: `${path} is claimed by ${producers.length} producers (${[...producers].sort().join(", ")}); exactly one producer may own an authoritative artifact path`
    }))
    .sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Detect producer-ordering cycles.
 *
 * `graph` maps a producer id to `{ writes, hashes }`. The degenerate and real case: producer A records a
 * hash of a file that producer B rewrites, so running A before B always leaves A's binding stale and A
 * must run again afterwards. The mutual case is worse: neither ordering satisfies both bindings.
 *
 * Reported separately from a hash mismatch because the remedy differs: a mismatch is fixed by
 * regenerating, a cycle is fixed by changing the order.
 */
export function findProducerOrderingCycles(graph, documentedOrder) {
  const producers = Object.entries(graph);
  const cycles = [];
  /*
   * A one-way dependency is not a cycle when the documented order already satisfies it.
   *
   * This previously flagged every one-way edge, which conflated two different things: composition binding the probe's
   * output is a legitimate DAG edge (run probe, then composition), while the probe binding a file composition rewrites
   * was a genuine cycle. Reporting both as "cycle" made the real defect indistinguishable from correct sequencing --
   * and a checker that cries wolf gets ignored, which is the failure mode this whole module exists to avoid.
   *
   * With `documentedOrder` supplied, a one-way edge is reported only when the order does *not* satisfy it. Mutual
   * edges remain cycles regardless, since no single ordering can satisfy both.
   */
  const orderIndex = new Map((documentedOrder ?? []).map((id, index) => [id, index]));
  const satisfiedByOrder = (dependentId, producerId) => {
    if (orderIndex.size === 0) return false;
    const dependent = orderIndex.get(dependentId);
    const producer = orderIndex.get(producerId);
    // The dependent must run *after* the producer whose output it binds.
    return dependent !== undefined && producer !== undefined && producer < dependent;
  };
  for (const [aId, a] of producers) {
    for (const [bId, b] of producers) {
      if (aId >= bId) continue;
      const aHashesBWrites = (a.hashes ?? []).filter((path) => (b.writes ?? []).includes(path));
      const bHashesAWrites = (b.hashes ?? []).filter((path) => (a.writes ?? []).includes(path));
      if (aHashesBWrites.length > 0 && bHashesAWrites.length > 0) {
        cycles.push({
          producers: [aId, bId],
          mutual: true,
          paths: [...new Set([...aHashesBWrites, ...bHashesAWrites])].sort(),
          detail: `${aId} records hashes of files ${bId} writes (${aHashesBWrites.join(", ")}) while ${bId} records hashes of files ${aId} writes (${bHashesAWrites.join(", ")}); no single ordering satisfies both bindings, so one producer must run twice`
        });
      } else if (aHashesBWrites.length > 0 && !satisfiedByOrder(aId, bId)) {
        cycles.push({
          producers: [aId, bId],
          mutual: false,
          paths: [...aHashesBWrites].sort(),
          detail: `${aId} records hashes of ${aHashesBWrites.join(", ")}, which ${bId} rewrites, and the documented order does not run ${bId} first; ${aId}'s binding is therefore left stale`
        });
      } else if (bHashesAWrites.length > 0 && !satisfiedByOrder(bId, aId)) {
        cycles.push({
          producers: [bId, aId],
          mutual: false,
          paths: [...bHashesAWrites].sort(),
          detail: `${bId} records hashes of ${bHashesAWrites.join(", ")}, which ${aId} rewrites, and the documented order does not run ${aId} first; ${bId}'s binding is therefore left stale`
        });
      }
    }
  }
  return cycles;
}

/** Recursively list files under a directory, relative to `root`. */
export function listFiles(directory, root = directory) {
  if (!existsSync(directory)) return [];
  const out = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const absolute = join(directory, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(absolute, root));
    else if (entry.isFile()) out.push(relative(root, absolute).replace(/\\/g, "/"));
  }
  return out;
}

/** True when `path` was modified more recently than `other`. Diagnostic only, never a freshness proof. */
export function isNewerThan(path, other) {
  if (!existsSync(path) || !existsSync(other)) return false;
  return statSync(path).mtimeMs > statSync(other).mtimeMs;
}
