// Emits the game-referenced model id set for the 05-S10 ≤80MB derived
// aggregate: every model id the 18 quality-rebuild games reference through
// `apps/<dir>/aura.assets.json` or `assets.<id>` in their src/, intersected
// with the root aura.assets.json model entries (the only ids the optimizer
// can derive). Writes tools/asset-optimize/derived-ids.txt for the CI step.
//
//   tsx --tsconfig tsconfig.base.json tools/asset-optimize/game-referenced-ids.mts [--check]
// --check verifies the committed file is fresh (CI gate against drift).
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = process.cwd();
const outFile = resolve(repoRoot, "tools/asset-optimize/derived-ids.txt");
const gamesDoc = JSON.parse(readFileSync(join(repoRoot, "tools/quality-rebuild-capture/games.json"), "utf8"));
const games: { id: string; appDir: string }[] = gamesDoc.games;

const rootManifest = JSON.parse(readFileSync(join(repoRoot, "aura.assets.json"), "utf8"));
const optimizable = new Set(
  (rootManifest.assets as { id: string; type?: string; format?: string }[])
    .filter((e) => e.type === "model" || e.format === "glb" || e.format === "gltf")
    .map((e) => e.id)
);

const ASSET_REF = /assets\.([a-z][A-Za-z0-9_]*)/g;
// module-path / extension fragments that `assets.<x>` regex also catches on
// import specifiers (`import ... from "./assets.json"`, `assets.ts` …).
const REF_IGNORE = new Set(["$", "json", "mjs", "ts", "js", "tsx", "mts", "py", "x", "map"]);

const collectSrcIds = (dir: string): Set<string> => {
  const ids = new Set<string>();
  const stack = [join(repoRoot, "apps", dir, "src")];
  while (stack.length) {
    const cur = stack.pop()!;
    if (!existsSync(cur)) continue;
    for (const name of readdirSync(cur, { withFileTypes: true })) {
      const p = join(cur, name.name);
      if (name.isDirectory()) { if (name.name !== "node_modules") stack.push(p); continue; }
      if (!/\.(ts|tsx|mts|js|jsx)$/.test(name.name)) continue;
      const src = readFileSync(p, "utf8");
      for (const m of src.matchAll(ASSET_REF)) if (!REF_IGNORE.has(m[1]!)) ids.add(m[1]!);
    }
  }
  return ids;
};

const referenced = new Map<string, Set<string>>(); // id -> games referencing it
for (const game of games) {
  const appRoot = join(repoRoot, "apps", game.appDir);
  const ids = new Set<string>();
  const manifestPath = join(appRoot, "aura.assets.json");
  if (existsSync(manifestPath)) {
    for (const e of JSON.parse(readFileSync(manifestPath, "utf8")).assets ?? []) {
      if (e.type === "model" || e.format === "glb" || e.format === "gltf") ids.add(e.id);
    }
  }
  for (const id of collectSrcIds(game.appDir)) ids.add(id);
  for (const id of ids) {
    const g = referenced.get(id) ?? new Set<string>();
    g.add(game.id);
    referenced.set(id, g);
  }
}

const ids = [...referenced.keys()].filter((id) => optimizable.has(id)).sort();
const unresolved = [...referenced.keys()].filter((id) => !optimizable.has(id)).sort();
const content = `# Game-referenced model ids — generated by game-referenced-ids.mts.
# Input: tools/quality-rebuild-capture/games.json appDirs; refs via per-app
# aura.assets.json model entries + assets.<id> in src/, intersected with the
# root manifest's model entries. Consumed by asset-optimize.yml's --ids step.
${ids.join("\n")}\n`;

const perGame = games.map((g) => {
  const own = [...referenced.entries()].filter(([, gs]) => gs.has(g.id)).length;
  return `${g.id}: ${own}`;
});
console.log(`referenced (raw): ${referenced.size}; optimizable∩: ${ids.length}; unresolved refs: ${unresolved.length}`);
console.log(`per-game refs: ${perGame.join(", ")}`);
if (unresolved.length) console.log(`unresolved (not in root manifest models): ${unresolved.join(", ")}`);

if (process.argv.includes("--check")) {
  const committed = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (committed !== content) {
    console.error(`${outFile} is stale — re-run game-referenced-ids.mts.`);
    process.exit(1);
  }
  console.log("derived-ids.txt is fresh.");
} else {
  writeFileSync(outFile, content);
  console.log(`wrote ${outFile} (${ids.length} ids).`);
}
