import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * Evidence freshness must be *dependency-bound*, not time-bound.
 *
 * The incident these tests exist for: `apps/aura-clash-showcase/launch-evidence/first-frame.png` was
 * regenerated by one producer into an old-looking visual while a different, current producer rendered
 * the correct textured arena. Re-running the right producer fixed the file, but nothing structural
 * prevented a recurrence, because freshness was inferred from modification time -- which proves only
 * that *something* wrote the file, not that the current implementation did.
 *
 * Every test below therefore asserts on a *cause*, not on a boolean: a report that says "stale" without
 * naming the dependency that moved is not actionable, and one that cries wolf gets ignored.
 */

interface FreshnessModule {
  readonly EVIDENCE_FRESHNESS_SCHEMA: string;
  readonly DEPENDENCY_KINDS: readonly string[];
  readonly RENDERER_FINGERPRINT_SOURCES: readonly string[];
  sha256(buffer: Buffer | string): string;
  createRendererFingerprint(root?: string, sources?: readonly string[]): string;
  createProducerFingerprint(producerRelativePath: string, version: string, root?: string): string;
  createConfigFingerprint(config: unknown): string;
  createFreshnessBinding(options: Record<string, unknown>): {
    readonly schema: string;
    readonly dependencies: readonly { kind: string; id: string; hash: string }[];
    readonly producer: { id: string; version: string };
  };
  explainArtifactStaleness(options: Record<string, unknown>): {
    readonly fresh: boolean;
    readonly unbound: boolean;
    readonly reasons: readonly {
      kind: string;
      id: string;
      status: string;
      detail: string;
      /** Recorded and current digests, present on `mismatch` so a report names both sides. */
      expected?: string;
      actual?: string;
    }[];
  };
  writeArtifactAtomically(absolutePath: string, contents: string | Buffer): string;
  writeJsonArtifactAtomically(absolutePath: string, value: unknown): string;
  findProducerOwnershipConflicts(ownership: Record<string, readonly string[]>): readonly {
    readonly path: string;
    readonly producers: readonly string[];
    readonly detail: string;
  }[];
  findProducerOrderingCycles(
    graph: Record<string, { writes: readonly string[]; hashes: readonly string[] }>,
    documentedOrder?: readonly string[]
  ): readonly {
    readonly producers: readonly string[];
    readonly mutual: boolean;
    readonly paths: readonly string[];
    readonly detail: string;
  }[];
}

const modulePromise = import(
  pathToFileURL(join(process.cwd(), "tools/evidence-freshness/index.mjs")).href
) as Promise<FreshnessModule>;

const registryPromise = import(
  pathToFileURL(join(process.cwd(), "tools/evidence-freshness/producer-registry.mjs")).href
) as Promise<{
  readonly PRODUCER_OWNERSHIP: Record<string, readonly string[]>;
  readonly PRODUCER_ORDERING_GRAPH: Record<string, { writes: readonly string[]; hashes: readonly string[] }>;
  readonly DOCUMENTED_PRODUCER_ORDER: readonly string[];
}>;

/** A binding over one dependency of each kind, so each dimension can be perturbed independently. */
async function baselineDependencies() {
  return [
    { kind: "route-source", id: "showcase-demo", hash: "sha256-aaa" },
    { kind: "route-gate-config", id: "route-gates.json", hash: "sha256-bbb" },
    { kind: "route-health", id: "showcase-demo/route-health.json", hash: "sha256-ccc" },
    { kind: "primary-asset", id: "heroCar", hash: "sha256-ddd" },
    { kind: "renderer-fingerprint", id: "agent-api+assets", hash: "sha256-eee" },
    { kind: "camera-config", id: "showcase-demo", hash: "sha256-fff" },
    { kind: "producer-version", id: "demo-producer", hash: "sha256-ggg" },
    { kind: "viewport-contract", id: "showcase-demo", hash: "sha256-hhh" },
    { kind: "screenshot", id: "showcase-demo.png", hash: "sha256-iii" }
  ];
}

async function bindingOver(dependencies: readonly Record<string, string>[]) {
  const { createFreshnessBinding } = await modulePromise;
  return createFreshnessBinding({
    artifact: "tests/reports/demo/showcase-demo.json",
    producerId: "demo-producer",
    producerVersion: "1.0",
    producerFingerprint: "sha256-ggg",
    generatedAt: "2026-08-01T00:00:00.000Z",
    dependencies
  });
}

describe("freshness binding records every dependency dimension", () => {
  it("keeps one entry per declared dependency kind", async () => {
    const { DEPENDENCY_KINDS } = await modulePromise;
    const binding = await bindingOver(await baselineDependencies());
    // Every kind the module claims to support must be representable in a binding.
    for (const kind of DEPENDENCY_KINDS) {
      expect(binding.dependencies.some((dependency) => dependency.kind === kind), `kind ${kind}`).toBe(true);
    }
  });

  it("rejects an unknown dependency kind rather than silently dropping it", async () => {
    // Silently dropping would produce an artifact that looks bound but is not.
    await expect(bindingOver([{ kind: "vibes", id: "x", hash: "sha256-x" }])).rejects.toThrow(/Unknown evidence dependency kind "vibes"/);
  });

  it("orders dependencies deterministically regardless of input order", async () => {
    const dependencies = await baselineDependencies();
    const forward = await bindingOver(dependencies);
    const reversed = await bindingOver([...dependencies].reverse());
    expect(reversed.dependencies).toEqual(forward.dependencies);
  });

  it("drops dependencies with no hash instead of recording undefined", async () => {
    const binding = await bindingOver([
      { kind: "route-source", id: "showcase-demo", hash: "sha256-aaa" },
      { kind: "route-health", id: "missing" } as unknown as Record<string, string>
    ]);
    expect(binding.dependencies).toHaveLength(1);
  });
});

describe("explainArtifactStaleness names the exact dependency that moved", () => {
  it("reports fresh when every dependency matches", async () => {
    const { explainArtifactStaleness } = await modulePromise;
    const dependencies = await baselineDependencies();
    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/showcase-demo.json",
      binding: await bindingOver(dependencies),
      currentDependencies: dependencies
    });
    expect(report.fresh).toBe(true);
    expect(report.reasons).toEqual([]);
  });

  // One case per staleness dimension the brief requires.
  for (const [kind, id] of [
    ["route-source", "showcase-demo"],
    ["route-gate-config", "route-gates.json"],
    ["route-health", "showcase-demo/route-health.json"],
    ["primary-asset", "heroCar"],
    ["renderer-fingerprint", "agent-api+assets"],
    ["camera-config", "showcase-demo"],
    ["producer-version", "demo-producer"],
    ["viewport-contract", "showcase-demo"],
    ["screenshot", "showcase-demo.png"]
  ] as const) {
    it(`rejects a stale ${kind}`, async () => {
      const { explainArtifactStaleness } = await modulePromise;
      const dependencies = await baselineDependencies();
      const binding = await bindingOver(dependencies);
      const changed = dependencies.map((dependency) =>
        dependency.kind === kind && dependency.id === id ? { ...dependency, hash: "sha256-CHANGED" } : dependency
      );
      const report = explainArtifactStaleness({
        artifactPath: "tests/reports/demo/showcase-demo.json",
        binding,
        currentDependencies: changed
      });
      expect(report.fresh).toBe(false);
      const reason = report.reasons.find((entry) => entry.kind === kind && entry.id === id);
      expect(reason?.status).toBe("mismatch");
      // The message must name the dimension, or the report is not actionable.
      expect(reason?.detail).toContain(kind);
    });
  }

  it("reports a dependency the artifact does not record as unbound, never as fresh", async () => {
    const { explainArtifactStaleness } = await modulePromise;
    const dependencies = await baselineDependencies();
    const partial = dependencies.filter((dependency) => dependency.kind !== "renderer-fingerprint");
    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/showcase-demo.json",
      binding: await bindingOver(partial),
      currentDependencies: dependencies
    });
    expect(report.fresh).toBe(false);
    const reason = report.reasons.find((entry) => entry.kind === "renderer-fingerprint");
    expect(reason?.status).toBe("unbound");
    expect(reason?.detail).toContain("cannot invalidate");
  });

  it("treats an artifact with no binding as unbound rather than current", async () => {
    const { explainArtifactStaleness } = await modulePromise;
    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/legacy.json",
      binding: undefined,
      currentDependencies: await baselineDependencies()
    });
    expect(report.fresh).toBe(false);
    expect(report.unbound).toBe(true);
    // Explicitly rejects the modification-time heuristic that caused the incident.
    expect(report.reasons[0]?.detail).toContain("Modification time is not evidence");
  });

  it("lists every mismatch, not just the first", async () => {
    const { explainArtifactStaleness } = await modulePromise;
    const dependencies = await baselineDependencies();
    const binding = await bindingOver(dependencies);
    const changed = dependencies.map((dependency) =>
      ["route-source", "primary-asset", "screenshot"].includes(dependency.kind)
        ? { ...dependency, hash: "sha256-CHANGED" }
        : dependency
    );
    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/showcase-demo.json",
      binding,
      currentDependencies: changed
    });
    expect(report.reasons.filter((reason) => reason.status === "mismatch")).toHaveLength(3);
  });

  it("compares hash values rather than their spelling", async () => {
    // Retained evidence is inconsistent about the `sha256-` prefix: the route-primary probe stores
    // `routeGateHash` bare while storing its siblings prefixed. A spelling-sensitive comparison reported
    // two identical digests as a mismatch.
    const { explainArtifactStaleness } = await modulePromise;
    const binding = await bindingOver([{ kind: "route-gate-config", id: "route-gates.json", hash: "sha256-abc123" }]);
    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/showcase-demo.json",
      binding,
      currentDependencies: [{ kind: "route-gate-config", id: "route-gates.json", hash: "abc123" }]
    });
    expect(report.fresh).toBe(true);
  });
});

describe("renderer and producer fingerprints respond to real change", () => {
  it("changes when a declared renderer source changes", async () => {
    const { createRendererFingerprint } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-fingerprint-"));
    try {
      const sources = ["a.ts", "b.ts"];
      mkdirSync(join(root, "sub"), { recursive: true });
      writeFileSync(join(root, "a.ts"), "one");
      writeFileSync(join(root, "b.ts"), "two");
      const before = createRendererFingerprint(root, sources);
      writeFileSync(join(root, "b.ts"), "two-changed");
      const after = createRendererFingerprint(root, sources);
      expect(after).not.toBe(before);
      // And is stable when nothing changes.
      expect(createRendererFingerprint(root, sources)).toBe(after);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("changes when a renderer source is renamed even with identical bytes", async () => {
    const { createRendererFingerprint } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-fingerprint-rename-"));
    try {
      writeFileSync(join(root, "a.ts"), "same");
      const before = createRendererFingerprint(root, ["a.ts"]);
      writeFileSync(join(root, "renamed.ts"), "same");
      const after = createRendererFingerprint(root, ["renamed.ts"]);
      expect(after).not.toBe(before);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("does not silently compare equal when no renderer source exists", async () => {
    const { createRendererFingerprint } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-fingerprint-empty-"));
    try {
      expect(createRendererFingerprint(root, ["nope.ts"])).toBe("sha256-no-renderer-sources");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("resolves a real fingerprint over the repository's declared renderer sources", async () => {
    const { createRendererFingerprint, RENDERER_FINGERPRINT_SOURCES } = await modulePromise;
    // The declared list must actually exist, or the fingerprint is vacuous.
    for (const source of RENDERER_FINGERPRINT_SOURCES) {
      expect(existsSync(join(process.cwd(), source)), source).toBe(true);
    }
    expect(createRendererFingerprint(process.cwd())).not.toBe("sha256-no-renderer-sources");
  });

  it("changes a producer fingerprint on a version bump alone", async () => {
    const { createProducerFingerprint } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-producer-"));
    try {
      writeFileSync(join(root, "producer.mjs"), "export const x = 1;");
      const v1 = createProducerFingerprint("producer.mjs", "1.0", root);
      const v2 = createProducerFingerprint("producer.mjs", "1.1", root);
      expect(v2).not.toBe(v1);
      // ...and on a source change at the same version.
      writeFileSync(join(root, "producer.mjs"), "export const x = 2;");
      expect(createProducerFingerprint("producer.mjs", "1.0", root)).not.toBe(v1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("hashes config independently of key order", async () => {
    const { createConfigFingerprint } = await modulePromise;
    expect(createConfigFingerprint({ width: 1440, height: 900 })).toBe(createConfigFingerprint({ height: 900, width: 1440 }));
    expect(createConfigFingerprint({ width: 1440, height: 900 })).not.toBe(createConfigFingerprint({ width: 1441, height: 900 }));
  });
});

describe("atomic writes", () => {
  it("replaces a file without leaving a partial artifact, and leaves no temp files", async () => {
    const { writeJsonArtifactAtomically } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-atomic-"));
    try {
      const target = join(root, "nested", "evidence.json");
      writeJsonArtifactAtomically(target, { pass: true });
      expect(JSON.parse(readFileSync(target, "utf8"))).toEqual({ pass: true });
      writeJsonArtifactAtomically(target, { pass: false });
      expect(JSON.parse(readFileSync(target, "utf8"))).toEqual({ pass: false });
      const { listFiles } = await modulePromise as unknown as { listFiles(dir: string): readonly string[] };
      expect(listFiles(root).filter((file) => file.endsWith(".tmp"))).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("creates missing parent directories", async () => {
    const { writeArtifactAtomically } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-atomic-mkdir-"));
    try {
      const target = join(root, "a", "b", "c", "file.txt");
      writeArtifactAtomically(target, "hello");
      expect(readFileSync(target, "utf8")).toBe("hello");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("producer ownership and ordering", () => {
  it("detects two producers claiming one authoritative path", async () => {
    const { findProducerOwnershipConflicts } = await modulePromise;
    const conflicts = findProducerOwnershipConflicts({
      "producer-a": ["apps/demo/launch-evidence/first-frame.png"],
      "producer-b": ["apps/demo/launch-evidence/first-frame.png"]
    });
    expect(conflicts).toHaveLength(1);
    expect(conflicts[0]?.producers).toEqual(["producer-a", "producer-b"]);
    expect(conflicts[0]?.detail).toContain("exactly one producer may own");
  });

  it("reports no conflict for the repository's declared ownership map", async () => {
    // This is the structural guarantee the stale-first-frame incident lacked.
    const { findProducerOwnershipConflicts } = await modulePromise;
    const { PRODUCER_OWNERSHIP } = await registryPromise;
    expect(findProducerOwnershipConflicts(PRODUCER_OWNERSHIP)).toEqual([]);
  });

  it("detects a one-way dependency the documented order does not satisfy", async () => {
    const { findProducerOrderingCycles } = await modulePromise;
    const graph = {
      first: { writes: ["out/first.json"], hashes: ["state/health.json"] },
      second: { writes: ["state/health.json"], hashes: [] }
    };
    // No order supplied: any one-way edge is reported.
    const withoutOrder = findProducerOrderingCycles(graph);
    expect(withoutOrder).toHaveLength(1);
    expect(withoutOrder[0]?.mutual).toBe(false);

    // Wrong order: `first` binds what `second` rewrites, but runs before it.
    expect(findProducerOrderingCycles(graph, ["first", "second"])).toHaveLength(1);
  });

  it("does not report a one-way dependency the documented order already satisfies", async () => {
    /*
     * The distinction that made the checker usable: composition depending on the probe's output is correct
     * sequencing, not a defect. Reporting every one-way edge as a "cycle" made the real defect indistinguishable
     * from correct ordering -- and a checker that cries wolf gets ignored, which is the failure this module exists
     * to prevent.
     */
    const { findProducerOrderingCycles } = await modulePromise;
    const graph = {
      producer: { writes: ["out/artifact.json"], hashes: [] },
      consumer: { writes: ["out/derived.json"], hashes: ["out/artifact.json"] }
    };
    expect(findProducerOrderingCycles(graph, ["producer", "consumer"])).toEqual([]);
  });

  it("has no ordering cycle in the repository's real producer graph", async () => {
    /*
     * This test previously asserted the *presence* of a mutual cycle: the route-primary probe bound a hash of
     * `apps/<route>/route-health.json` while the composition producer rewrote that file and bound the probe's own
     * output. Neither ordering satisfied both bindings, so the documented order compensated by running the probe
     * twice.
     *
     * That cycle is now eliminated rather than compensated. Composition derives everything it writes into
     * route-health *from* the probe's output, so those fields were never a real probe dependency:
     * `hashRouteHealthDependency` excludes the `gameAssetPairEvidence` block and the `screenshotSha256` /
     * `routePrimaryScreenshotSha256` digests wherever they appear, and `createRouteSourceHash` normalises the same
     * digests inside generated route sources. Every producer now runs exactly once.
     */
    const { findProducerOrderingCycles } = await modulePromise;
    const { PRODUCER_ORDERING_GRAPH, DOCUMENTED_PRODUCER_ORDER } = await registryPromise;
    expect(findProducerOrderingCycles(PRODUCER_ORDERING_GRAPH, DOCUMENTED_PRODUCER_ORDER)).toEqual([]);

    // No producer needs to run twice any more.
    const counts = new Map<string, number>();
    for (const producer of DOCUMENTED_PRODUCER_ORDER) counts.set(producer, (counts.get(producer) ?? 0) + 1);
    for (const [producer, count] of counts) {
      expect(count, `${producer} must appear once in the documented order`).toBe(1);
    }

    // And composition must still run after the probe it depends on, or the order would be wrong in the other way.
    expect(DOCUMENTED_PRODUCER_ORDER.indexOf("route-primary-probes"))
      .toBeLessThan(DOCUMENTED_PRODUCER_ORDER.indexOf("regenerate-game-composition-evidence"));
  });

  it("reports no cycle for an acyclic graph", async () => {
    const { findProducerOrderingCycles } = await modulePromise;
    expect(findProducerOrderingCycles({
      a: { writes: ["out/a.json"], hashes: ["src/x.ts"] },
      b: { writes: ["out/b.json"], hashes: ["src/y.ts"] }
    })).toEqual([]);
  });
});

describe("the route-primary probe now binds the previously-unbound dimensions", () => {
  it("records renderer fingerprint, producer identity and viewport contract", async () => {
    const path = "tests/reports/showcase-route-primary-probes/showcase-turbo-drift-circuit.json";
    expect(existsSync(path), path).toBe(true);
    const probe = JSON.parse(readFileSync(path, "utf8")) as {
      readonly freshness?: {
        readonly producer?: { readonly id?: string; readonly version?: string; readonly fingerprint?: string };
        readonly dependencies?: readonly { readonly kind: string }[];
      };
    };
    const kinds = new Set((probe.freshness?.dependencies ?? []).map((dependency) => dependency.kind));
    for (const kind of ["route-source", "route-gate-config", "route-health", "primary-asset", "renderer-fingerprint", "producer-version", "viewport-contract"]) {
      expect(kinds.has(kind), `probe must bind ${kind}`).toBe(true);
    }
    expect(probe.freshness?.producer?.id).toBe("route-primary-probes");
    expect(probe.freshness?.producer?.fingerprint).toMatch(/^sha256-[a-f0-9]{64}$/);
  });

  it("binds the renderer fingerprint the current tree actually produces", async () => {
    const { createRendererFingerprint } = await modulePromise;
    const probe = JSON.parse(
      readFileSync("tests/reports/showcase-route-primary-probes/showcase-turbo-drift-circuit.json", "utf8")
    ) as { readonly freshness?: { readonly dependencies?: readonly { kind: string; hash: string }[] } };
    const recorded = (probe.freshness?.dependencies ?? []).find((dependency) => dependency.kind === "renderer-fingerprint");
    // If this fails, the retained probe predates a renderer change and must be regenerated -- which is
    // exactly the signal the binding exists to provide.
    expect(recorded?.hash).toBe(createRendererFingerprint(process.cwd()));
  });
});

describe("concurrent writers cannot race a shared artifact", () => {
  /**
   * The brief requires that parallel tests cannot race shared retained artifacts. That was defect 71's root cause:
   * a non-authoritative producer wrote real repository evidence, and the resulting failures looked like flakiness
   * because the failing test name changed between runs.
   *
   * A found defect, not a hypothetical: the temp-file name was
   * `${path}.${pid}.${Date.now()}.tmp`, which is **not unique**. 200 rapid calls in one process produce *one* name,
   * because `Date.now()` has millisecond resolution and the pid is constant. Two writers sharing a temp path means
   * the second `writeFileSync` destroys the first writer's staged bytes before it renames -- one artifact silently
   * becomes the other's content while both calls report success. Same class as the stale-first-frame incident:
   * output that looks written and is wrong.
   */

  it("generates a unique temp path per call, not per process-millisecond", async () => {
    const { writeArtifactAtomically } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-race-unique-"));
    try {
      const target = join(root, "evidence.json");
      // If temp names collided, a leftover or a lost write would show up across many rapid calls.
      for (let index = 0; index < 200; index += 1) {
        writeArtifactAtomically(target, `payload-${index}`);
      }
      expect(readFileSync(target, "utf8")).toBe("payload-199");
      const { listFiles } = await modulePromise as unknown as { listFiles(dir: string): readonly string[] };
      expect(listFiles(root).filter((file) => file.endsWith(".tmp"))).toEqual([]);
      expect(listFiles(root)).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("does not key the temp name on wall-clock time alone", () => {
    /*
     * A behavioural regression guard on the naming scheme itself.
     *
     * Measured: the previous `${path}.${pid}.${Date.now()}.tmp` yields **2 distinct names across 200 rapid calls**,
     * while a per-call unique scheme yields 200. The concurrency tests above can pass by luck under synchronous
     * serialization, so this pins the property that made them pass rather than only the outcome.
     */
    const source = readFileSync("tools/evidence-freshness/index.mjs", "utf8");
    expect(source).toContain("nextWriteSequence()");
    expect(source).toContain("randomBytes(6)");
    // The retired scheme must not come back.
    expect(source).not.toContain("${absolutePath}.${process.pid}.${Date.now()}.tmp");
  });

  it("leaves a whole, parseable artifact when many writers target one path concurrently", async () => {
    /*
     * The invariant that matters for a reader: whatever wins, the file is *one* writer's complete output. A partial
     * or interleaved artifact is worse than a stale one -- it looks like evidence and parses as garbage.
     */
    const { writeJsonArtifactAtomically } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-race-concurrent-"));
    try {
      const target = join(root, "probe.json");
      const writers = Array.from({ length: 24 }, (_unused, index) => Promise.resolve().then(() => {
        // Payloads of very different sizes, so an interleaved write would be detectable as a truncation.
        writeJsonArtifactAtomically(target, { writer: index, filler: "z".repeat(1_000 * (index + 1)) });
      }));
      await Promise.all(writers);
      const parsed = JSON.parse(readFileSync(target, "utf8")) as { writer: number; filler: string };
      // Exactly one writer's payload, internally consistent: filler length must match its own writer index.
      expect(parsed.filler.length).toBe(1_000 * (parsed.writer + 1));
      expect(new Set(parsed.filler)).toEqual(new Set(["z"]));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("never leaves temp files behind after concurrent writes", async () => {
    // A stray `.tmp` beside a retained artifact is how a later reader picks up a half-written file.
    const { writeJsonArtifactAtomically, listFiles } = await modulePromise as unknown as {
      writeJsonArtifactAtomically(path: string, value: unknown): string;
      listFiles(dir: string): readonly string[];
    };
    const root = mkdtempSync(join(tmpdir(), "aura3d-race-cleanup-"));
    try {
      const target = join(root, "summary.json");
      await Promise.all(Array.from({ length: 30 }, (_unused, index) =>
        Promise.resolve().then(() => writeJsonArtifactAtomically(target, { index }))));
      expect(listFiles(root)).toEqual(["summary.json"]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("keeps distinct artifact paths independent under concurrent writes", async () => {
    /*
     * Producers write many artifacts in one run. A temp-name scheme keyed only on the target path could still
     * collide across *different* targets if it were keyed on time alone; this proves each path keeps its own value.
     */
    const { writeJsonArtifactAtomically } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-race-multi-"));
    try {
      const paths = Array.from({ length: 12 }, (_unused, index) => join(root, `route-${index}.json`));
      await Promise.all(paths.map((path, index) =>
        Promise.resolve().then(() => writeJsonArtifactAtomically(path, { route: index }))));
      for (const [index, path] of paths.entries()) {
        expect(JSON.parse(readFileSync(path, "utf8"))).toEqual({ route: index });
      }
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("screenshot digest mismatch is a staleness cause in its own right", () => {
  it("rejects an artifact whose recorded screenshot digest no longer matches the file", async () => {
    /*
     * The brief lists "mismatched screenshot SHA rejected" separately from asset/route/renderer staleness, and
     * rightly: a screenshot can be regenerated while every other dependency is unchanged. That is exactly the Aura
     * Clash stale-first-frame shape -- one artifact rewritten by the wrong producer with the rest of the world
     * untouched.
     */
    const { explainArtifactStaleness, sha256 } = await modulePromise;
    const root = mkdtempSync(join(tmpdir(), "aura3d-shot-digest-"));
    try {
      const screenshot = join(root, "first-frame.png");
      writeFileSync(screenshot, "original-bytes");
      const recordedDigest = sha256(readFileSync(screenshot));
      const binding = await bindingOver([{ kind: "screenshot", id: "first-frame.png", hash: recordedDigest }]);

      // Unchanged file: fresh.
      expect(explainArtifactStaleness({
        artifactPath: "launch-evidence/visual-approval.json",
        binding,
        currentDependencies: [{ kind: "screenshot", id: "first-frame.png", hash: sha256(readFileSync(screenshot)) }]
      }).fresh).toBe(true);

      // Rewritten by another producer: stale, named by cause.
      writeFileSync(screenshot, "regenerated-by-a-different-producer");
      const report = explainArtifactStaleness({
        artifactPath: "launch-evidence/visual-approval.json",
        binding,
        currentDependencies: [{ kind: "screenshot", id: "first-frame.png", hash: sha256(readFileSync(screenshot)) }]
      });
      expect(report.fresh).toBe(false);
      const reason = report.reasons.find((entry) => entry.kind === "screenshot");
      expect(reason?.status).toBe("mismatch");
      expect(reason?.detail).toContain("first-frame.png");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("explain-staleness output lists the exact dependency mismatch", () => {
  it("names every mismatched dependency with both digests, not just a count", async () => {
    /*
     * The brief requires the explainer to list the *exact* dependency mismatch. A report saying "3 dependencies
     * changed" is not actionable; the Aura Clash incident needed to know it was the screenshot and not the asset.
     */
    const { explainArtifactStaleness } = await modulePromise;
    const dependencies = await baselineDependencies();
    const binding = await bindingOver(dependencies);
    const changed = dependencies.map((dependency) =>
      ["primary-asset", "screenshot"].includes(dependency.kind)
        ? { ...dependency, hash: "sha256-MOVED" }
        : dependency);

    const report = explainArtifactStaleness({
      artifactPath: "tests/reports/demo/showcase-demo.json",
      binding,
      currentDependencies: changed
    });
    const mismatches = report.reasons.filter((reason) => reason.status === "mismatch");
    expect(mismatches).toHaveLength(2);
    for (const mismatch of mismatches) {
      // Each names its kind, its id, and both the recorded and current digests.
      expect(mismatch.detail).toContain(mismatch.kind);
      expect(mismatch.detail).toContain(mismatch.id);
      expect(mismatch.expected).toBeTruthy();
      expect(mismatch.actual).toBeTruthy();
      expect(mismatch.expected).not.toBe(mismatch.actual);
    }
    // Unchanged dependencies are not reported, so the signal is not diluted.
    expect(report.reasons.some((reason) => reason.kind === "route-source")).toBe(false);
  });
});

describe("the repository's retained evidence is provably current", () => {
  /**
   * An end-to-end assertion on the real artifacts, not on fixtures.
   *
   * Every dimension this module measures was tested in isolation above. That is necessary but not sufficient: the
   * bindings only protect anything if the *actual* retained evidence satisfies them. Before this pass, 11 of 13
   * route-primary probes were not provably current -- they predated the narrowed bindings and recorded whole-file
   * route-health digests -- and nothing failed.
   *
   * Uses `execFileSync` on the real command so the assertion covers the same code path a developer runs.
   */
  function explainStaleness(): {
    readonly staleArtifactCount: number;
    readonly frozenRoutes: readonly string[];
    readonly orderingCycles: readonly unknown[];
    readonly ownershipConflicts: readonly unknown[];
    readonly artifacts: readonly { readonly artifact: string; readonly fresh: boolean; readonly reasons: readonly { kind: string; status: string }[] }[];
  } {
    const stdout = execFileSync("node", ["tools/evidence-freshness/explain-staleness.mjs", "--json"], {
      cwd: process.cwd(),
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024
    });
    return JSON.parse(stdout);
  }

  it("reports zero stale artifacts", () => {
    const report = explainStaleness();
    const stale = report.artifacts.filter((artifact) => !artifact.fresh);
    // Name the offenders, so a failure is actionable rather than a bare count.
    expect(stale.map((artifact) => artifact.artifact)).toEqual([]);
    expect(report.staleArtifactCount).toBe(0);
  });

  it("audits a non-trivial number of artifacts, so a clean report is not vacuous", () => {
    /*
     * Guards the way this check could rot: over-filtering routes would drive the stale count to zero by auditing
     * nothing. A clean report over an empty set proves nothing at all.
     */
    const report = explainStaleness();
    expect(report.artifacts.length).toBeGreaterThanOrEqual(8);
    for (const artifact of report.artifacts) {
      expect(artifact.artifact).toMatch(/^tests\/reports\/showcase-route-primary-probes\/.+\.json$/);
    }
  });

  it("reports no producer ownership conflict and no ordering cycle", () => {
    const report = explainStaleness();
    expect(report.ownershipConflicts).toEqual([]);
    // Zero cycles is the post-elimination state: the probe no longer binds fields composition derives from it.
    expect(report.orderingCycles).toEqual([]);
  });

  it("names frozen routes explicitly rather than silently skipping them", () => {
    /*
     * `retainedEvidenceFrozen` routes are excluded because regenerating them is forbidden -- reporting them as stale
     * would be unfalsifiable, since the only implied remedy is the one thing the freeze prevents. Excluding them
     * silently would be worse: a reader could not tell an intentional freeze from a missing audit.
     */
    const report = explainStaleness();
    expect(report.frozenRoutes).toContain("showcase-racing-game-layer-proof");
    expect(report.frozenRoutes).toContain("showcase-platformer-game-layer-proof");
    // Frozen routes must not also appear as audited artifacts.
    for (const frozen of report.frozenRoutes) {
      expect(report.artifacts.some((artifact) => artifact.artifact.includes(frozen))).toBe(false);
    }
  });
});

describe("the producer registry covers every retained artifact class", () => {
  /**
   * Why this test exists.
   *
   * `findProducerOwnershipConflicts` guarantees "at most one owner per path". It says nothing about *at least* one --
   * so an artifact class with no declared owner passes the conflict check trivially while enjoying none of its
   * protection. Auditing `tests/reports/` against the registry found **four** such classes, three of which were
   * created during this pass (`multipart-primitive-draw`, `asset-screening`, `replicability-metrics`) plus
   * `showcase-game-visual-qa`. Adding producers without declaring them is precisely how the original ownership
   * ambiguity arose, and I reproduced it.
   *
   * The registry is only meaningful if it is complete, and completeness only holds if something checks it.
   */

  it("declares an owner for every artifact directory it claims to cover", async () => {
    const { PRODUCER_OWNERSHIP, OWNED_ARTIFACT_DIRECTORIES } = await registryPromise as unknown as {
      readonly PRODUCER_OWNERSHIP: Record<string, readonly string[]>;
      readonly OWNED_ARTIFACT_DIRECTORIES: readonly string[];
    };
    const declaredPaths = Object.values(PRODUCER_OWNERSHIP).flat().join("|");
    const undeclared = OWNED_ARTIFACT_DIRECTORIES.filter(
      (directory) => !declaredPaths.includes(`tests/reports/${directory}/`)
    );
    expect(undeclared, "every owned artifact directory needs a declared producer").toEqual([]);
  });

  it("covers every artifact directory that actually exists on disk", async () => {
    /*
     * The complement of the check above: the declared *list* could itself omit a directory. Comparing against the
     * filesystem catches a producer that shipped without being added to either the ownership map or the coverage list.
     */
    const { OWNED_ARTIFACT_DIRECTORIES } = await registryPromise as unknown as {
      readonly OWNED_ARTIFACT_DIRECTORIES: readonly string[];
    };
    for (const directory of OWNED_ARTIFACT_DIRECTORIES) {
      expect(
        existsSync(join("tests/reports", directory)),
        `${directory} is declared as owned but does not exist; remove it or produce it`
      ).toBe(true);
    }
  });

  it("keeps the documented order consistent with the declared producers", async () => {
    /*
     * A producer present in the ownership map but absent from the documented order has no defined position, so a
     * caller cannot know when to run it -- which is how the probe/composition ordering defect became possible.
     */
    const { PRODUCER_OWNERSHIP, PRODUCER_ORDERING_GRAPH, DOCUMENTED_PRODUCER_ORDER } = await registryPromise as unknown as {
      readonly PRODUCER_OWNERSHIP: Record<string, readonly string[]>;
      readonly PRODUCER_ORDERING_GRAPH: Record<string, { writes: readonly string[]; hashes: readonly string[] }>;
      readonly DOCUMENTED_PRODUCER_ORDER: readonly string[];
    };
    // Every producer in the ordering graph must have a position in the documented order.
    for (const producer of Object.keys(PRODUCER_ORDERING_GRAPH)) {
      expect(DOCUMENTED_PRODUCER_ORDER, `${producer} must appear in the documented order`).toContain(producer);
    }
    // Every producer in the graph must also own the paths it claims to write.
    for (const [producer, entry] of Object.entries(PRODUCER_ORDERING_GRAPH)) {
      expect(PRODUCER_OWNERSHIP[producer], `${producer} must declare ownership`).toBeTruthy();
      expect(entry.writes).toEqual(PRODUCER_OWNERSHIP[producer]);
    }
  });

  it("still reports no ownership conflict or ordering cycle with the added producers", async () => {
    // Adding four producers must not introduce a second writer or an unsatisfiable order.
    const { findProducerOwnershipConflicts, findProducerOrderingCycles } = await modulePromise;
    const { PRODUCER_OWNERSHIP, PRODUCER_ORDERING_GRAPH, DOCUMENTED_PRODUCER_ORDER } = await registryPromise;
    expect(findProducerOwnershipConflicts(PRODUCER_OWNERSHIP)).toEqual([]);
    expect(findProducerOrderingCycles(PRODUCER_ORDERING_GRAPH, DOCUMENTED_PRODUCER_ORDER)).toEqual([]);
    // Sanity: the registry is not trivially small.
    expect(Object.keys(PRODUCER_OWNERSHIP).length).toBeGreaterThanOrEqual(10);
  });
});

describe("the freshness verdict is itself retained evidence", () => {
  /**
   * WS6 requires each artifact establish 14 things, the last being "stale reason if rejected". Every other field is
   * recorded in the probes. This one existed **only as console text and a `--json` stream nobody captured** -- so
   * the freshness verdict, the judgement this whole system exists to produce, was the single evidence class with no
   * durable record. A release reviewer had to re-run the tool and trust a terminal rather than read a file.
   */
  const AUDIT_PATH = "tests/reports/evidence-freshness/staleness-audit.json";

  interface Audit {
    readonly schema?: string;
    readonly generatedAt?: string;
    readonly rendererFingerprint?: string;
    readonly staleArtifactCount?: number;
    readonly frozenRoutes?: readonly string[];
    readonly ownershipConflicts?: readonly unknown[];
    readonly orderingCycles?: readonly unknown[];
    readonly artifacts?: readonly {
      readonly artifact: string;
      readonly fresh: boolean;
      readonly unbound: boolean;
      readonly reasons: readonly { readonly kind: string; readonly id: string; readonly status: string; readonly detail: string }[];
    }[];
  }

  function audit(): Audit {
    return JSON.parse(readFileSync(AUDIT_PATH, "utf8")) as Audit;
  }

  it("is retained on disk, not only printed", () => {
    expect(existsSync(AUDIT_PATH), `${AUDIT_PATH} must exist`).toBe(true);
  });

  it("records the schema, timestamp and renderer fingerprint its verdict is bound to", () => {
    /*
     * A verdict without the fingerprint it was computed against is unfalsifiable later: a reader cannot tell
     * whether "0 stale" described the current tree or one from three commits ago.
     */
    const report = audit();
    expect(report.schema).toBe("aura3d-explain-staleness/1.0");
    expect(Number.isNaN(Date.parse(String(report.generatedAt)))).toBe(false);
    expect(report.rendererFingerprint).toMatch(/^sha256-[a-f0-9]{64}$/);
  });

  it("records a per-artifact verdict with a reasons array, which is the WS6 stale-reason field", () => {
    const report = audit();
    expect(report.artifacts?.length ?? 0, "must audit a non-trivial artifact set").toBeGreaterThanOrEqual(8);
    for (const artifact of report.artifacts ?? []) {
      expect(artifact.artifact, "each entry names its artifact path").toBeTruthy();
      expect(typeof artifact.fresh).toBe("boolean");
      expect(Array.isArray(artifact.reasons), `${artifact.artifact} reasons array`).toBe(true);
      /*
       * The load-bearing invariant: a stale artifact must carry at least one machine-readable reason. A stale
       * verdict with no reason is exactly the unfalsifiable report this system exists to prevent -- it tells a
       * reader something is wrong without telling them what to regenerate.
       */
      if (!artifact.fresh && !artifact.unbound) {
        expect(artifact.reasons.length, `${artifact.artifact} is stale but gives no reason`).toBeGreaterThan(0);
        for (const reason of artifact.reasons) {
          expect(reason.kind, "reason names the dependency kind").toBeTruthy();
          expect(reason.status, "reason names its status").toBeTruthy();
        }
      }
    }
  });

  it("agrees with its own summary count", () => {
    // A count that disagrees with the per-artifact verdicts would make either number untrustworthy.
    const report = audit();
    const counted = (report.artifacts ?? []).filter((artifact) => !artifact.fresh).length;
    expect(report.staleArtifactCount).toBe(counted);
  });

  it("names frozen routes explicitly rather than silently skipping them", () => {
    /*
     * Reporting a deliberately-frozen artifact as stale is unfalsifiable -- the only remedy implied is
     * regeneration, which the freeze forbids. Silently omitting it is worse: a reader cannot distinguish an
     * intentional freeze from a missing audit.
     */
    const report = audit();
    expect(report.frozenRoutes).toContain("showcase-racing-game-layer-proof");
    expect(report.frozenRoutes).toContain("showcase-platformer-game-layer-proof");
    for (const artifact of report.artifacts ?? []) {
      for (const frozen of report.frozenRoutes ?? []) {
        expect(artifact.artifact, `frozen route ${frozen} must not be audited`).not.toContain(frozen);
      }
    }
  });

  it("records zero ownership conflicts and zero ordering cycles", () => {
    const report = audit();
    expect(report.ownershipConflicts).toEqual([]);
    expect(report.orderingCycles).toEqual([]);
  });

  it("declares itself in the producer registry, like every other producer", async () => {
    const { PRODUCER_OWNERSHIP, DOCUMENTED_PRODUCER_ORDER } = await registryPromise;
    /*
     * It would be incoherent for the arbiter of retained evidence to be the one producer exempt from the ownership
     * rules it enforces. An undeclared artifact class passes the "at most one owner" check trivially while enjoying
     * none of its protection.
     */
    expect(Object.keys(PRODUCER_OWNERSHIP)).toContain("evidence-freshness-audit");
    expect(PRODUCER_OWNERSHIP["evidence-freshness-audit"]).toContain(AUDIT_PATH);
    expect(DOCUMENTED_PRODUCER_ORDER).toContain("evidence-freshness-audit");
    // It judges every other artifact, so it must be ordered last.
    expect(DOCUMENTED_PRODUCER_ORDER[DOCUMENTED_PRODUCER_ORDER.length - 1]).toBe("evidence-freshness-audit");
  });
});
