import { describe, expect, it } from 'vitest';
import { checkDocumentInvariants, isStructuralDocumentLine, CONTROLLED_CLAIM_DOCUMENTS } from '../../../tools/muse3jsparity-docs-audit/document-invariants';
const history='## 2.0.4 (old)\nOriginal history\n';
function fixture(){return Object.fromEntries(CONTROLLED_CLAIM_DOCUMENTS.map(p=>[p,p==='CHANGELOG.md'?'## 3.0.1\n## 3.0.0\n'+history:p==='README.md'?'## Current Release 3.0.1\n### 2.0.4 history':p.includes('llms')?'Source 3.0.1 effects nodes camera rigs gameFeel SDF text decal rigid body':p.includes('release-checklist')?'Version: 3.0.1\naura3d-301-release-notes.md':p.startsWith('marketing/')?'<a href="/releases/tag/v3.0.1">Notes</a> @aura3d/engine@3.0.1 <section id="release-204">2.0.4 history</section>':'bounded evidence']));}
describe('final document source invariants',()=>{
 it('accepts exact current pins, mirror and retained history',()=>{const docs=fixture();expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toEqual([]);});
 it('keeps published pins truthful during the candidate stage',()=>{const docs=fixture();docs['CHANGELOG.md']=docs['CHANGELOG.md']!.replace('## 3.0.1','## 3.0.1 (unreleased candidate)');for(const p of ['marketing/index.html','marketing/docs/index.html'])docs[p]=docs[p]!.replaceAll('v3.0.1','v3.0.0').replaceAll('@3.0.1','@3.0.0')+' 3.0.1 source candidate; verification pending';expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toEqual([]);docs['marketing/index.html']+=' 3.0.1 live';expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toContain('candidate falsely claimed published:marketing/index.html');});
 it('detects editing older changelog history even with current header',()=>{const docs=fixture();docs['CHANGELOG.md']+='rewritten';expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toContain('CHANGELOG 2.0.4 and older history changed');});
 it('requires unchanged controlled surfaces, mirror and current checklist',()=>{const docs=fixture();docs['public/llms.txt']='other';docs['docs/project/release/release-checklist.md']='Version: 3.0.0';expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toEqual(expect.arrayContaining(['llms mirror differs byte-for-byte','release checklist targets wrong version','release checklist lacks current notes reference']));});
 it('does not confuse historical section pins with current installation',()=>{const docs=fixture();docs['marketing/index.html']+=' @aura3d/engine@3.0.0';expect(checkDocumentInvariants(p=>docs[p]!,()=>history)).toContain('stale live install pin:marketing/index.html');});
 it('permits formatting but never treats a capability heading or code as structural',()=>{for(const line of ['# Overview','```ts','| --- | :---: |','</section>'])expect(isStructuralDocumentLine(line)).toBe(true);for(const line of ['# Full native parity','## 120 FPS everywhere','scene.render()','<h1>Production quality</h1>'])expect(isStructuralDocumentLine(line)).toBe(false);});
});
