import { describe, expect, it } from "vitest";
import { BLOOM_PERF_QUALITY_LIMITS, validateEnginePerfReport } from "../../browser/muse3jsparity-301-engine-perf-contract";

// Contract-negative fixture only. These records are never release evidence.
function fixture() {
 const ids=["bloomChain","instance4k","light64","particle10k"];
 return {schema:"aura3d.engine-perf-301/v1",producer:"tests/browser/muse3jsparity-301-engine-perf.spec.ts",complete:true,bloomQuality:{limits:BLOOM_PERF_QUALITY_LIMITS,aura:{haloPixels:1000,haloEnergy:10000,basePixels:200,clippedFraction:0,centroid:[320,180]},three:{haloPixels:1000,haloEnergy:10000,basePixels:200,clippedFraction:0,centroid:[320,180]}},failures:[],errors:[],workloads:ids.map(workload=>({workload,engines:Object.fromEntries(["aura","three"].map(engine=>{
  const quality={resolution:[640,360],pixelRatio:1,antialias:false,adaptive:false,camera:{position:[0,0,4],fov:45,near:.1,far:100},workload,instances:workload==="instance4k"?4000:0,lights:workload==="light64"?64:0,particles:workload==="particle10k"?10000:0,bloom:workload==="bloomChain"?{mips:5,format:"half-float",threshold:1,strength:1,radius:1}:null};
  return [engine,{engine,workload,backend:"webgl2",hardware:"fixture-no-hardware-evidence",entryPoint:engine==="aura"?(workload==="particle10k"?"@aura3d/rendering:ParticleSystem.update + Renderer.renderAsync":"@aura3d/engine:createAuraApp.stepAsync"):"three@0.185.1:WebGLRenderer.render"+(workload==="bloomChain"?" + EffectComposer/UnrealBloomPass":""),revision:engine==="three"?"185":"workspace",quality,qualityFingerprint:JSON.stringify(quality),adaptation:[],effectiveLights:workload==="light64"?64:null,trials:Array.from({length:3},()=>({samples:Array.from({length:60},()=>({renderSize:[640,360],gpuCompleted:true,cpuSubmissionMs:1,engineCallAwaitMs:2,gpuCompletionMs:1,readbackMs:.1,completedFrameMs:4,rafPacingMs:16.7,textureStorageBytes:640*360*32,bloomObservation:{native:{mipCount:5,halfFloat:true,threshold:1,intensity:1},toneMapping:"aces",exposure:1,outputColorSpace:"srgb"},textureAllocations:[[320,180],[160,90],[80,45],[40,23],[20,12]].flatMap(([width,height])=>Array.from({length:2},()=>({width,height,halfFloat:true}))),liveParticles:workload==="particle10k"?10000:0,native:{viewportDraws:[[320,180],[160,90],[80,45],[40,23],[20,12]].flatMap(v=>[v,v]),drawCalls:1,triangles:workload==="particle10k"?20000:48000,maxDrawInstances:workload==="instance4k"?4000:0}}))}))}];
 }))}))};
}
describe("actual engine performance report contract",()=>{
 it("accepts structurally complete records without treating fixtures as actual evidence",()=>{expect(validateEnginePerfReport(fixture())).toEqual([]);});
 it("rejects missing native counters even under complete flag",()=>{const r=fixture();delete (r.workloads[0]!.engines.aura as any).trials[0].samples[0].native;expect(validateEnginePerfReport(r).join()).toContain("invalid completed frame");});
 it("rejects one unfenced frame",()=>{const r=fixture();(r.workloads[1]!.engines.aura as any).trials[2].samples[59].gpuCompleted=false;expect(validateEnginePerfReport(r).join()).toContain("invalid completed frame");});
 it("rejects both opponents agreeing on a reduced workload",()=>{const r=fixture();for(const e of Object.values(r.workloads[1]!.engines) as any[]){e.quality.instances=3000;e.qualityFingerprint=JSON.stringify(e.quality);}expect(validateEnginePerfReport(r).join()).toContain("frozen workload changed");});
 it("rejects one live particle short and duplicate workload",()=>{const r=fixture();(r.workloads[3]!.engines.aura as any).trials[0].samples[0].liveParticles=9999;r.workloads[2]!.workload="instance4k";expect(validateEnginePerfReport(r).join()).toContain("10000 live rendered particles missing");expect(validateEnginePerfReport(r).join()).toContain("Missing or duplicate workloads");});
 it("rejects missing bloom mip draws despite claimed settings",()=>{const r=fixture();(r.workloads[0]!.engines.aura as any).trials[0].samples[0].native.viewportDraws=[];expect(validateEnginePerfReport(r).join()).toContain("native mip draws missing");});
 it("rejects a native Aura bloom strength capped below the frozen workload",()=>{const r=fixture();(r.workloads[0]!.engines.aura as any).trials[0].samples[0].bloomObservation.native.intensity=.92;expect(validateEnginePerfReport(r).join()).toContain("observed bloom settings missing");});
 it("rejects reduced bloom output despite identical settings",()=>{const r=fixture();r.bloomQuality.aura.haloPixels=500;expect(validateEnginePerfReport(r).join()).toContain("equivalent-quality band");});
 it("rejects unknown Aura entry point",()=>{const r=fixture();(r.workloads[0]!.engines.aura as any).entryPoint="@aura3d/synthetic:loop";expect(validateEnginePerfReport(r).join()).toContain("engine entry point missing");});
});
