import { createHash, createPublicKey, verify } from 'node:crypto';
import { mkdirSync,mkdtempSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { it,expect,vi } from 'vitest';
const state=vi.hoisted(()=>({plan:null as any}));
vi.mock('../../../tools/release/exact-release-plan.mjs',()=>({loadValidatedReleasePlan:()=>state.plan}));
import { createPackageProvenanceReport } from '../../../tools/package-provenance/index.js';
function fixture(){const root=mkdtempSync(join(tmpdir(),'aura29-provenance-'));mkdirSync(join(root,'tests/reports'),{recursive:true});const packages=Array.from({length:29},(_,i)=>{const bytes=Buffer.from(`candidate${i}`),tarball=`tests/reports/p${i}.tgz`;writeFileSync(join(root,tarball),bytes);return {name:i?`@aura3d/p${i}`:'@aura3d/engine',version:'3.0.1',tarball,sha256:createHash('sha256').update(bytes).digest('hex'),integrity:`sha512-${createHash('sha512').update(bytes).digest('base64')}`};});state.plan={version:'3.0.1',reference:{path:'tests/reports/plan.json',sha256:'a'.repeat(64)},source:{commit:'c',fingerprint:'f'},packages};writeFileSync(join(root,'tests/reports/plan.json'),JSON.stringify(state.plan));writeFileSync(join(root,'package.json'),JSON.stringify({name:'@aura3d/engine',version:'3.0.1'}));const smoke={ok:true,packageName:'@aura3d/engine',packageVersion:'3.0.1',tarballPath:packages[0]!.tarball,tarballSha256:packages[0]!.sha256,packMode:'validated-release-plan',releasePlan:state.plan.reference,installedIdentity:{},exactPackages:{ok:true,packageCount:29,releasePlan:state.plan.reference,packages:packages.map(p=>({...p,ok:true,installedIntegrity:p.integrity}))}};const save=()=>writeFileSync(join(root,'tests/reports/package-install-smoke.json'),JSON.stringify(smoke));save();return {root,smoke,save};}
it('signs separately verifiable subjects for all29 exact tested candidates',()=>{const f=fixture();try{const report=createPackageProvenanceReport(f.root);expect(report.ok).toBe(true);expect(report.packageCount).toBe(29);for(const raw of report.packages??[]){const p=raw as any;expect(verify(null,Buffer.from(JSON.stringify(p.statement)),createPublicKey(p.signature.publicKeyPem),Buffer.from(p.signature.signatureBase64,'base64'))).toBe(true);}}finally{rmSync(f.root,{recursive:true,force:true});}});
it('rejects a missing package smoke even when aggregate says29passed',()=>{const f=fixture();try{f.smoke.exactPackages.packages.pop();f.save();const report=createPackageProvenanceReport(f.root);expect(report.ok).toBe(false);expect(report.violations.join(' ')).toContain('All29 exact candidate');}finally{rmSync(f.root,{recursive:true,force:true});}});
it('rejects an observed installed integrity different from the candidate',()=>{const f=fixture();try{f.smoke.exactPackages.packages[28]!.installedIntegrity='sha512-wrong';f.save();const report=createPackageProvenanceReport(f.root);expect(report.ok).toBe(false);expect(report.violations.join(' ')).toContain('Missing verified smoke/installed identity');}finally{rmSync(f.root,{recursive:true,force:true});}});
