/**
 * Generates the committed attract-mode fixture (BF-A6).
 *
 * The "expert run" is the competent planner segment from rules.ts: the simulated
 * run plays until its first top-out, and everything before that boundary is a
 * long, line-clearing stretch of real play. That segment becomes the attract
 * loop. Run via:
 *   pnpm exec tsx --tsconfig tsconfig.base.json apps/showcase-blockfall-reactor/scripts/write-expert-fixture.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEMO_REPLAY_60S,
  REPLAY_PROOF_FRAMES,
  checksumString,
  createOpeningBoard,
  sixtySecondReplayPlanFacts,
  runReplay
} from "../src/rules";
import {
  ATTRACT_RUN_KIND,
  serializeAttractRun,
  type AttractRunFixture
} from "../src/attract";

const here = dirname(fileURLToPath(import.meta.url));

const facts = sixtySecondReplayPlanFacts();
if (!facts.gameOverProven || facts.segmentBoundaries.length === 0) {
  throw new Error("Expected the sixty-second plan to top out at least once; regenerate with a valid planner.");
}
const boundary = facts.segmentBoundaries[0];
if (typeof boundary !== "number" || boundary <= 0) throw new Error("Invalid segment boundary.");

// Every event strictly before the first top-out belongs to the expert segment.
const events = DEMO_REPLAY_60S.filter((event) => event.frame < boundary);
if (events.length === 0) throw new Error("Expert segment came out empty.");

const frames = Math.max(...events.map((event) => event.frame + 20), 240);
const result = runReplay(events, { frames, board: createOpeningBoard() });
if (result.finalSummary.lines === 0 || result.finalSummary.score === 0) {
  throw new Error("Expert segment did not clear lines or score; not good enough for attract mode.");
}

const fixture: AttractRunFixture = {
  kind: ATTRACT_RUN_KIND,
  label: "expert reactor segment before first top-out",
  seed: result.seed,
  frames,
  openingBoard: true,
  events,
  expected: {
    finalScore: result.finalSummary.score,
    finalLines: result.finalSummary.lines,
    stateChecksum: result.finalChecksum,
    scoreHash: checksumString("score:" + result.finalSummary.score)
  }
};

const outPath = resolve(here, "../../../tests/fixtures/blockfall/expert-run.json");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, serializeAttractRun(fixture) + "\n");

// The mounted route cannot import .json under the TS dev server (browsers need
// explicit JSON import attributes), so emit a TS twin of the same bytes. A unit
// test asserts the two never drift.
const dataPath = resolve(here, "../src/expert-run-data.ts");
const dataModule =
  "/**\n" +
  " * Generated by scripts/write-expert-fixture.ts — do not hand-edit.\n" +
  " * Embedded twin of tests/fixtures/blockfall/expert-run.json (BF-A6 attract run).\n" +
  " */\n" +
  "export const EXPERT_RUN_DATA_JSON = " + JSON.stringify(serializeAttractRun(fixture)) + ";\n";
writeFileSync(dataPath, dataModule);
console.log("wrote " + dataPath);
console.log("wrote " + outPath);
console.log("events:", events.length, "frames:", frames, "(proof window is", REPLAY_PROOF_FRAMES + ")");
console.log("finalScore:", fixture.expected.finalScore, "lines:", fixture.expected.finalLines);
console.log("stateChecksum:", fixture.expected.stateChecksum, "scoreHash:", fixture.expected.scoreHash);