import { readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const json = (path: string): any => JSON.parse(readFileSync(resolve(path), "utf8")); const text = (path: string): string => readFileSync(resolve(path), "utf8"); const baseline = json("tests/reports/current-threejs-baseline.json"); const context = json("benchmark/context/threejs-r185.1-20260808.json"); const browser = json("tests/reports/current-head-to-head/xr-interaction/report.json"); const source = text("benchmark/current-head-to-head/xr-interaction/main.ts"); const captures = ["aura-before.png", "three-before.png", "aura-after.png", "three-after.png"];
const checks = [
  { id: "current-three-official-xr-stack", pass: baseline.three?.version === "0.185.1" && browser.before?.three?.revision === "185" && browser.before?.three?.actualWebXRManager === true && browser.before?.three?.actualXRButton === true },
  { id: "exact-frozen-product-and-native-captures", pass: browser.assetSha256 === context.assets.product.sha256 && captures.every((name) => statSync(resolve(`tests/reports/current-head-to-head/xr-interaction/${name}`)).size > 10_000) },
  { id: "honest-injected-evidence-boundary", pass: browser.after?.interaction?.injected === true && browser.after?.three?.actualInjectedXRSession === true && source.includes('realHeadsetClaimed: false') },
  { id: "public-aura-controller-sample", pass: browser.after?.aura?.publicPackageOnly === true && browser.after?.aura?.actualWebXRSessionController === true && browser.after?.aura?.session?.started?.started === true && browser.after?.aura?.session?.sample?.controllerCount === 1 && browser.after?.aura?.session?.sample?.controllers?.[0]?.triggerPressed === true },
  { id: "official-xrbutton-manager-handoff", pass: browser.after?.three?.xrButtonDispatched === true && browser.after?.three?.isPresenting === true && browser.after?.three?.explicitManagerHandoff === false },
  { id: "paired-visible-selection-state", pass: browser.before?.aura?.hash !== browser.after?.aura?.hash && browser.before?.three?.hash !== browser.after?.three?.hash && browser.after?.aura?.session?.hapticPulses === 1 },
  { id: "matched-background-output", pass: maxDelta(browser.before?.aura?.backgroundPixel, browser.before?.three?.backgroundPixel) <= 3 && maxDelta(browser.after?.aura?.backgroundPixel, browser.after?.three?.backgroundPixel) <= 3 },
  { id: "caller-owned-lifecycle", pass: Object.values(browser.lifecycle ?? {}).every(Boolean) && Object.keys(browser.lifecycle ?? {}).length === 6 }
];
const failures = checks.filter((entry) => !entry.pass); const report = { schema: "aura3d.current-head-to-head-xr-interaction/1.0", generatedAt: new Date().toISOString(), pass: failures.length === 0, workload: "xr-interaction", verdict: "injected-xr-interaction-equivalence-only", checks, failures, comparison: { auraDrawCalls: browser.after?.aura?.drawCalls, threeDrawCalls: browser.after?.three?.drawCalls, observedLosses: ["Personal inspection of all four retained mirror-view frames confirms exact backgrounds, closely aligned product/floor framing, the same selection translation, and the cyan target at the same injected controller location. Normalized paired RMSE is 0.00671716 before and 0.00700155 after; small material, shadow, and raster differences remain.", "This environment supplies an injected XRSession-like object. It proves public controller sampling/haptics and official XRButton-to-WebXRManager session wiring, but no real headset, stereoscopic projection, device pose quality, browser XR compositor, hand tracking, AR camera, or headset performance."], claimBoundary: "Injected-session WebXR interaction evidence only; real-device XR remains unproven." }, browser }; const output = resolve("tests/reports/current-head-to-head/xr-interaction/aggregate.json"); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); if (failures.length) { console.error(`XR head-to-head UNPROVEN: ${failures.map((entry) => entry.id).join(", ")}`); process.exitCode = 1; } else console.log(`XR head-to-head PASS: ${checks.length}/${checks.length}; ${output}`);
function maxDelta(left: readonly number[] | undefined, right: readonly number[] | undefined): number { if (!left || !right) return Number.POSITIVE_INFINITY; return Math.max(...left.map((value, index) => Math.abs(value - (right[index] ?? 0)))); }
