/**
 * `@aura3d/engine` "." — the PRD-15 §6.6 public surface.
 * Explicit named exports only: the §6.6 keep-set (game/template/benchmark
 * import tally + contracts + lane contracts) as live exports, plus the
 * union of still-consumed names as @deprecated re-exports kept at 4.0.0
 * (§6.6 step 3). Generated by tools/export-surface/scaffold.ts — regenerate with
 * `pnpm exec tsx --tsconfig tsconfig.base.json tools/export-surface/scaffold.ts --write`.
 */

// Lane provide() side-effects — how lane contract implementations reach ".".
import "../lanes/index.js";

// ── Live surface (§6.6 keep-set) ────────────────────────────────────────
export { AnimationController, appExtensionsAll, asRuntimeCompiled, auditArtDirection, AuraColorParseError, AuraSceneBuilder, bindGameTouchControls, bindRuntimeCompiled, blendSkyBandColor, camera, captionCueAtTime, captureFromUrl, characterAssembly, charts, checkSpatialInvariants, city, clearFocus, combatFrameAdvantage, compilePromptEpisodePlan, compilePromptPlanV2, compilerSlot, compileScene, composeWorldMatrix, createAnimationPerformanceCoverage, createAnimationRenderOutputPackageMetadata, createArchitectureKit, createAssetDiagnostics, createAudioStemManifest, createAuraApp, createAuraRouteHealthSnapshot, createAuraText3DGeometry, createAuraVoiceBridgePackage, createAuraVoiceVisemeTrack, createCameraPathFromPreset, createCinematicKit, createCollisionLayers, createCombatAi, createDiagnosticsPanel, createDigitalTwinKit, createEnvironment, createFightingGameKit, createGame, createGameApp, createGameArcadeVehicle, createGameAudio, createGlbBlendshapeVisemeCue, createInitialDiagnostics, createMeshSurfaceQuery, createPrimitiveMouthVisemeCues, createProductConfiguratorKit, createProductionRuntimeCollectedLights, createPromptAnimationDeterministicScreenshotFixtureMetadata, createShotPlaybackPlan, createSmartCityKit, createVehicleChassis, createVehicleDriverAi, decomposeMatrix, defineAuraAssets, defineDubMap, definePromptPlan, DIAGNOSTIC_ONLY_FIELDS, DIAGNOSTICS_SECTION_KEYS, diagnosticsSectionsAll, distanceLod, distributeInRegion, effects, enforceFrameBudget, environments, eulerToQuaternion, fitSizeToRegion, focusCameraIntent, focusObject, focusSemanticRegion, game, gameFeel, games, geometry, glbVisemeBlendshapeExample, groundedFittedModelPosition, groundedRenderedAssetPlacement, group, groups, installShotPlayback, instances, interactions, labels, lights, lookLint, looks, material, model, nodeHandleExtensionFor, nodeHandleExtensionsAll, nodeHandlerFor, nodeHandlersAll, optionCoverageRows, parseAuraColor, parseAuraColorSrgb, particles, physics, placedBounds, placedBoundsFromAsset, planLayeredSceneComposition, planScatterInstances, planSkyBackdrop, platformerCompositionSpec, postPresets, prefabs, primitiveMouthVisemeExample, primitives, product, promptPlanToScene, registerAppExtension, registerDiagnosticsSection, registerEnvironmentSource, registerLookLintRule, registerNodeHandleExtension, registerNodeHandler, registerOptionCoverage, renderer, resolveBoundsAnchor, resolveChaseFraming, resolveEnvironment, resolveQrFlags, resolveSemanticRegion, sampleAuraVoiceBridgeAtTime, sampleCameraPath, sampleShotPlaybackPlan, sampleVisemeTrack, scatterWindOffset, scene, sceneKits, SCREEN_FEEL_BLACKBOARD_KEY, setCompilerImpl, shadows, skyBandCountForRamp, snapshotDiagnostics, solar, solveCombatFrameData, solvePlatformerMotion, StubActorAnimationApi, StubAppAtmosphere, StubAppEffects, stubCameraRigFactories, StubFeelBus, StubLightingRuntime, StubModelMaterialHandle, StubPostSurface, StubTimeController, text3D, timeline, ui, updateCompiledScene, validateAuraVoiceBridgePackage, validateCombatFrameData, vehicleChassisSpecFromBounds, WIND_CHUNK, workflows, worldQueriesSlot } from "../agent-api/index.js";
export type { AnyNodeHandler, AppExtension, ArtDirectionViolation, AuraActorAnimationApi, AuraActorAnimationStateSnapshot, AuraAnimationAssetLike, AuraAnimationDiagnostics, AuraAntiAliasMode, AuraApp, AuraAppAtmosphere, AuraAppEffects, AuraAppExtensionMap, AuraAppTarget, AuraAssetBudget, AuraAssetDecodersOption, AuraAssetDefinition, AuraAssetLodLevel, AuraAssetLodOption, AuraAssetMap, AuraAssetRef, AuraAssetRequiredDecoder, AuraAssetsOption, AuraAssetVariants, AuraAutoExposureOptions, AuraBiomeId, AuraBiomeRig, AuraBodyHandle, AuraBoneMaskSpec, AuraBoneSocket, AuraCameraController, AuraCameraLayer, AuraCameraOption, AuraCameraPose, AuraCameraRailOptions, AuraCameraRig, AuraCameraRigContext, AuraCameraRigFactories, AuraCameraSequence, AuraCameraSequencePlayback, AuraCameraShot, AuraCameraSpec, AuraCameraSubject, AuraCompiledFeature, AuraCreateAppAnimationOptions, AuraCustomGeometrySpec, AuraCustomPostPass, AuraDecalOptions, AuraDegradation, AuraDegradationCode, AuraDiagnostics, AuraDiagnosticsSectionKey, AuraDirectionalShadowOptions, AuraEaseName, AuraEffectInstanceHandle, AuraEffectsDiagnostics, AuraEnvironmentSource, AuraEnvironmentSourceKind, AuraEnvironmentSourceResolution, AuraEulerOrder, AuraFeelBus, AuraFeelEventSpec, AuraFovKickLayer, AuraHeightFogSpec, AuraHeightQuery, AuraLightingDiagnostics, AuraLightingModel, AuraLightingOptions, AuraLightingRuntime, AuraLightsApiAdditions, AuraLocalShadowOptions, AuraLookDiagnostics, AuraLookId, AuraLookLintCode, AuraLookLintContext, AuraLookLintFinding, AuraLookLintRule, AuraLookNode, AuraLookOverrides, AuraLoopOptions, AuraMaterialDiagnostics, AuraMaterialSpec, AuraMaterialTextureSlot, AuraModelColliderOption, AuraModelLodOption, AuraModelMaterialHandle, AuraModelMaterialOverride, AuraNamedAnimationClipDefinition, AuraNodeHandleExtensionMap, AuraNodeInput, AuraNodeKindMap, AuraOutputDiagnostics, AuraOutputOptions, AuraOutputOverlay, AuraOutputSurface, AuraPhysicsRuntime, AuraPostDiagnostics, AuraPostPreset, AuraPostPresetId, AuraPostSurface, AuraPunchLayer, AuraQuat, AuraRendererMaterialOptions, AuraResolvedClipInfo, AuraResolvedMaterialInfo, AuraRootLodLevelSpec, AuraRootMotionSpec, AuraRootVec3, AuraRuntimeNodeHandle, AuraRuntimeNodeRegistryV2, AuraSceneNode, AuraSceneSnapshot, AuraScreenFeelUniforms, AuraShadowOptions, AuraSkyNode, AuraSkySpec, AuraSkySunSpec, AuraStudioLookId, AuraTimeController, AuraToneMappingOperator, AuraTransformSpec, AuraTraumaLayer, AuraVec3, AuraVfxEffectSpec, AuraVfxKind, AuraVolumetricFogSpec, AuraWindSpec, AuraWorldQualityTier, AuraWorldQueries, AuraWorldTransform, CameraPath, CameraPresetId, CaptureContext, CharacterAssemblyPlan, CombatAi, CombatAiAggression, CombatFrameAdvantage, CombatFrameData, CompiledActor, CompiledScene, CompilerImpl, CreateGameOptions, DiagnosticsSection, DriverRoute, FightingGameSnapshot, FocusResult, Game, GameAcceptance, GameArcadeVehicle, GameArcadeVehicleInput, GameArcadeVehicleState, GameAudio, GameAudioContextLike, GameAudioOptions, GameBeacon, GameBudgets, GameCombatEvent, GameCombatMove, GameCombatWorld, GameCombatWorldSnapshot, GameEffectsController, GameEntryV2, GameFallingBlockAction, GameFallingBlocksEvent, GameFallingBlocksSnapshot, GameFxKind, GameFxLayer, GameGenre, GameInputController, GameInputReplayEvent, GameInputReplayPlan, GameKitRect, GamePlatformerSnapshot, GameRacingKit, GameRacingSnapshot, GameScenario, GameSession, GameSessionState, GameShell, GameShellLayout, GroundRaycaster, Hud, HudMountOptions, HudWidgetSpec, MeshSurfaceQuery, NodeHandleExtension, NodeHandler, OptionCoverageRow, PauseReason, QrFlagInput, RebuildTier, RenderSourceContributions, RouteHealthQualityGate, RuntimeCompiledSceneInternals, RuntimeNodeHandleLike, SceneCompileContext, SemanticRegion, SurfaceSample, TouchControls, TouchPreset, TransitionSpec, VehicleChassis, VehicleDriverAi, VehiclePose, VehicleSurface, VehicleVec3 } from "../agent-api/index.js";

// ── Deprecated union (kept at 4.0.0 per §6.6 step 3 — removes in the next minor; each names its destination) ──
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { A3DEnvironment } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/renderer`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { A3DRenderer } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/animation`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { AnimationAction } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/animation`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { AnimationClip } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/animation`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { AnimationLayer } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/animation`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { AnimationMixer } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/animation`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { AnimationTrack } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraColor } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraCreateAppOptions } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraCreateGameAppOptions } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export type { AuraDiagnosticsOverlay } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraEffectNode } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraLightNode } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraModelOptions } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { AuraNodeBuilder } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraPerformanceQuality } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { AuraPrimitiveNode } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { captureAuraAppScreenshot } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { captureScreenshot } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { character } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { collectAuraSceneEvidence } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { collectPromptAnimationEvidence } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { compilePromptPlan } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { compositeMetallicRoughnessPixels } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createA3DApp } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createAnimationController } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { createAssetCompatibilityReport } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createAssetViewerWorkflow } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { createCaptionTimingProof } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createExternalParityEnvironmentPipeline } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createGameAppRuntime } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createInteractiveSceneWorkflow } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createProductConfiguratorWorkflow } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { createProductionPrimitiveTextureIntent } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { crowds } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { decals } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { describeProductionSpotShadow } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { editor } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { evaluatePromptAnimationPublishReadiness } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { gameAssetValidation } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { GamePlatformerEvent } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export type { CharacterAssemblyValidationReport } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/assets`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { GLTFLoader } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { inspectAsset } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/assets`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { inspectGLTFAsset } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { listExternalParityEnvironmentTargets } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { loadAsset } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/assets`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { loadRenderableAsset } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { meshVehicleSurface } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { mipChainBytesCoarseToFine } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { navigation } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { normalizeSceneSnapshot } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { normalizeTextureBudgetBytes } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { quaterniusGameReadyFighterValidationContract } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/renderer`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { Renderer } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { resolveProductionRuntimeShadowTuning } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { resolveProductionShadowCasterIndex } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { sky } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { summarizeExternalParityGLTFCorpus } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { unsafeModelUrl } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { upgradeProductionPrimitiveTextures } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { validatePlatformerMotion } from "../agent-api/index.js";
/** @deprecated Use `@aura3d/engine/devtools`. Kept at 4.0.0 — removes in the next minor once its blocking lane's request lands. */
export { validateQuaterniusGameReadyFighterAsset } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { water } from "../agent-api/index.js";
/** @deprecated No replacement — removes next minor. Kept at 4.0.0 once its blocking lane's request lands. */
export { weather } from "../agent-api/index.js";

// ── Lane-facing leaves consumed by shipped tests (prd02/prd03 contract
// impls) — these names live on leaf modules, not the agent-api barrel, so
// "." re-exports them directly. ──────────────────────────────────────────
export {
  collectExposureSection,
  collectPostSection,
  createPrd03PostSurface,
  latestSubmittedPostprocess,
  recordAuthoredPostContext,
  resetAuthoredPostContext,
  resetSubmittedPostprocess
} from "../agent-api/postBridge.js";
export type {
  AuthoredPostContext,
  AuthoredPostSummary,
  SubmittedPostprocessRecord
} from "../agent-api/postBridge.js";
export { createProductionRuntimePostprocess } from "../agent-api/compiler/postprocess.js";
