export type AuraClashEvidenceStatus = "complete" | "implemented" | "needs-visual-qa" | "pending";

export interface AuraClashEvidenceItem {
  id: string;
  label: string;
  status: AuraClashEvidenceStatus;
  proof: string;
  files: string[];
}

export interface AuraClashRouteEvidence {
  path: string;
  purpose: string;
  requiredSignals: string[];
}

export interface AuraClashControlEvidence {
  key: string;
  action: string;
  gameplayEffect: string;
  accessibilityNote: string;
}

export interface AuraClashAssetEvidence {
  name: string;
  typedAsset: string;
  sourcePath: string;
  publicPath: string;
  role: "fighter" | "arena" | "scene";
  provenance: string;
  licenseNote: string;
  thumbnailPath: string;
  bounds: readonly [number, number, number];
  materialSummary: string;
  intendedRouteUsage: string[];
  productionEvidence: string;
  sourceValidationEvidence?: string;
}

export const auraClashAssetEvidence: AuraClashAssetEvidence[] = [
  {
    name: "Mara Volt",
    typedAsset: "assets.auraClashPlayerRig",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/aura-clash-player-rig.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/auraClashPlayerRig.7cb14341.glb",
    role: "fighter",
    provenance: "Quaternius Modular Character Outfits - Fantasy Female_Ranger.gltf body, retargeted to the 65-joint Quaternius Universal Animation Library skeleton by build-animated-fighter-rigs.mjs.",
    licenseNote: "The staged Quaternius package license records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/auraClashPlayerRig.thumb.svg",
    bounds: [1.664, 1.798, 0.377],
    materialSummary: "MI_Ranger and MI_Regular_Female retain the textured layered ranger costume and readable skin/armor separation.",
    intendedRouteUsage: ["/playable/ default player", "/accessibility/ playable variant", "/evidence/ asset proof", "/poster/ combined scene representation"],
    productionEvidence: "The 5,310,952-byte typed GLB is hash-bound as sha256-7cb1434173b7c3d10fd6ee787da6b0c8e0633bd14adb900f83b8b6d9af483d71 and passed the twelve-state playable visual suite.",
    sourceValidationEvidence: "Typed skinned GLB only, no primitive fallback. Nine meshes, two textured materials, 65 ordered skin joints, and twelve embedded clips cover idle, movement, jump, hit, guard, light, heavy, special, and defeat states.",
  },
  {
    name: "Rook Atlas",
    typedAsset: "assets.auraClashRivalRig",
    sourcePath: "apps/aura-clash-showcase/assets/source/fighters/aura-clash-rival-rig.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/auraClashRivalRig.e078e71c.glb",
    role: "fighter",
    provenance: "Quaternius Modular Character Outfits - Fantasy Male_Ranger.gltf body, retargeted to the 65-joint Quaternius Universal Animation Library skeleton by build-animated-fighter-rigs.mjs.",
    licenseNote: "The staged Quaternius package license records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/auraClashRivalRig.thumb.svg",
    bounds: [1.799, 1.869, 0.373],
    materialSummary: "MI_Ranger and MI_Regular_Male retain the textured layered ranger costume and readable skin/armor separation.",
    intendedRouteUsage: ["/playable/ default rival", "/accessibility/ playable variant", "/evidence/ asset proof", "/poster/ combined scene representation"],
    productionEvidence: "The 4,732,432-byte typed GLB is hash-bound as sha256-e078e71c00c4a465891adfd267eec950507ba3b20bc67ef97f91e880a01d66dc and passed the twelve-state playable visual suite.",
    sourceValidationEvidence: "Typed skinned GLB only, no primitive fallback. Nine meshes, two textured materials, 65 ordered skin joints, and ten embedded clips cover idle, movement, jump, hit, guard, light, heavy, special, and defeat states.",
  },
  {
    name: "Neon Downtown Textured Arena",
    typedAsset: "assets.arenaNeonDowntownTextured",
    sourcePath: "apps/aura-clash-showcase/assets/source/arenas/arena-neon-downtown-textured.glb",
    publicPath: "apps/aura-clash-showcase/public/aura-assets/arenaNeonDowntownTextured.312f2320.glb",
    role: "arena",
    provenance: "Quaternius Downtown City MegaKit Standard archive, 42 selected arena pieces, generated by blender-build-aura-clash-assets.py.",
    licenseNote: "Quaternius Downtown City MegaKit package license text records CC0 1.0 Universal / Public Domain Dedication; project policy still credits Quaternius.",
    thumbnailPath: "apps/aura-clash-showcase/public/aura-assets/arenaNeonDowntownTextured.thumb.svg",
    bounds: [43.737, 38.08, 38.435],
    materialSummary: "Nineteen texture-backed asphalt, roof, floor, trim, glass, brick, concrete, dirt, ornament, street-decal, and Aura Clash emissive groups across 81 visible primitives.",
    intendedRouteUsage: ["/playable/ live arena", "/accessibility/ live arena", "/evidence/ arena proof", "/deploy-check/ asset proof"],
    productionEvidence: "The live route binds this typed asset directly; aura.assets.json records its sha256-312f2320 hash, bounds, texture images, materials, and thumbnail URL.",
  },
];

export const auraClashRuntimeMutationEvidenceContract = {
  kind: "aura-clash-runtime-mutation-evidence-contract",
  runtimeExport: "window.__AURA_CLASH_ARENA_PROOF__",
  requiredSignals: [
    "animation.visibleSkinnedGlb is true, with skinnedDrawItems and per-fighter skinningBindings above zero",
    "fighterAssets.player/rival resolve to distinct typed assets.* ids, urls, and hashes",
    "noPrimitiveFighters is true, so neither fighter falls back to primitive stand-ins",
    "player/rival expose position, grounded, action, and activeClip mutated per frame rather than rebuilt",
    "runtime.frameLoop, runtime.input, runtime.deterministicCombat, and runtime.hitWindows are all true",
    "engineCombat reports frame, activeAttacks, events, health, and guard state from the simulation",
    "camera.respondingToCombat, punchIn, and frameWidthUnits differ from restingFrameWidthUnits only while a hit-stop decays",
    "deterministicReplay.stable is true, with finalHash matching repeatedFinalHash across replays",
  ],
  sourceFiles: [
    "apps/aura-clash-showcase/src/main.ts",
    "apps/aura-clash-showcase/src/playable/AuraClashArenaApp.ts",
    "apps/aura-clash-showcase/src/playable/evidence/auraClashArenaProof.ts",
    "apps/aura-clash-showcase/src/playable/combat/AuraClashFighterController.ts",
    "apps/aura-clash-showcase/src/fighters/HitboxSystem.ts",
    "apps/aura-clash-showcase/src/playable/arena/RenderedArenaStage.ts",
  ],
} as const;

export const auraClashRouteEvidence: AuraClashRouteEvidence[] = [
  {
    path: "/playable/",
    purpose: "Hands-on arcade route with a keyboard-driven combat loop, HUD, timer, character select, typed GLB stage, and round result states.",
    requiredSignals: [
      "Player can move with A/D or arrow keys, jump with Space, attack, guard, dash, pause with P/Escape, restart, and trigger a special.",
      "Opponent pressure updates health, guard, meter, and combat log state.",
      "Aura3D scene is composed live from the typed duel stage GLB plus selected fighter GLBs.",
      "Gameplay updates mutate persistent game.runtimeNode fighter handles instead of rebuilding the scene graph for frame/state changes.",
    ],
  },
  {
    path: "/evidence/",
    purpose: "Developer proof route showing asset provenance, typed asset paths, implemented controls, routes, and acceptance gates.",
    requiredSignals: [
      "Quaternius source packs are named with local archive paths and hashes in the provenance file.",
      "Launch asset evidence records every public GLB with license note, thumbnail, bounds, material summary, route usage, and fighter source validation fields.",
      "Typed Aura asset names are visible so developers can see the exact API path.",
      "Route source displays hitbox, guard, miss, and body-separation counts from AuraClashRuntimeEvidence.",
      "Route source displays animation states and kinematic body position/velocity source for both fighters.",
      "Incomplete gates are labeled as requiring visual QA instead of being treated as finished.",
    ],
  },
  {
    path: "/accessibility/",
    purpose: "Accessibility route with reduced motion, reduced flash, and high contrast controls exposed directly in the game UI.",
    requiredSignals: [
      "Reduced motion affects motion-heavy visuals.",
      "Reduced flash suppresses impact flashes.",
      "High contrast raises border, text, and UI contrast.",
    ],
  },
  {
    path: "/deploy-check/",
    purpose: "Deployment-readiness route listing the checks required before this becomes the public flagship showcase.",
    requiredSignals: [
      "Route health, screenshot, accessibility, and deploy smoke tests are scaffolded.",
      "Static route files exist for Vercel-style direct URL loading.",
      "Marketing promotion remains gated on visual QA.",
    ],
  },
  {
    path: "/poster/",
    purpose: "Capture route for high-impact launch screenshots, hero posters, and social cards.",
    requiredSignals: [
      "Poster scenarios are named and mapped to exact capture filenames.",
      "Each scenario defines required visual elements.",
      "Capture output remains pending until browser visual QA is approved.",
    ],
  },
];

export const auraClashControlEvidence: AuraClashControlEvidence[] = [
  {
    key: "A / D / Arrow keys",
    action: "Move",
    gameplayEffect: "Moves the player avatar along the combat lane.",
    accessibilityNote: "No rapid input required for basic movement.",
  },
  {
    key: "Space",
    action: "Jump",
    gameplayEffect: "Adds a vertical burst and resets to idle.",
    accessibilityNote: "Can be ignored without blocking core combat.",
  },
  {
    key: "P / Escape",
    action: "Pause",
    gameplayEffect: "Pauses or resumes the round without resetting combat state.",
    accessibilityNote: "Provides keyboard pause paths that do not conflict with Space jump.",
  },
  {
    key: "Shift",
    action: "Dash",
    gameplayEffect: "Triggers a fast lateral movement state and meter gain.",
    accessibilityNote: "Reduced motion mode softens the dash presentation.",
  },
  {
    key: "Q",
    action: "Guard",
    gameplayEffect: "Reduces incoming pressure while active.",
    accessibilityNote: "Hold behavior is visible in the HUD state chip.",
  },
  {
    key: "J",
    action: "Light attack",
    gameplayEffect: "Fast low-damage pressure with combo growth.",
    accessibilityNote: "Attack feedback is text-backed in the combat log.",
  },
  {
    key: "K",
    action: "Heavy attack",
    gameplayEffect: "Slower higher-damage pressure with stronger hitstun.",
    accessibilityNote: "Combat impact is visible without relying only on color.",
  },
  {
    key: "L",
    action: "Special",
    gameplayEffect: "Consumes meter and fires the character super move.",
    accessibilityNote: "Reduced flash mode suppresses high-energy impact flashes.",
  },
  {
    key: "R",
    action: "Restart",
    gameplayEffect: "Resets timer, fighters, meters, and round result state.",
    accessibilityNote: "Provides a keyboard path to replay.",
  },
];

export const auraClashAnimationStates = [
  "idle",
  "light",
  "heavy",
  "special",
  "guard",
  "dash",
  "jump",
  "hitstun",
  "victory",
  "defeat",
] as const;

export const auraClashEvidence: AuraClashEvidenceItem[] = [
  {
    id: "typed-assets",
    label: "Typed Aura3D assets",
    status: "implemented",
    proof: "The live route consumes current typed Aura assets through assets.auraClashPlayerRig and assets.auraClashRivalRig, and the route proof publishes distinct asset ids, URLs, hashes, and release-readiness status.",
    files: [
      "apps/aura-clash-showcase/src/aura-assets.ts",
      "apps/aura-clash-showcase/public/aura-assets",
      "apps/aura-clash-showcase/src/playable/AuraClashArenaApp.ts",
      "apps/aura-clash-showcase/src/playable/evidence/auraClashArenaProof.ts",
    ],
  },
  {
    id: "quaternius-provenance",
    label: "Quaternius asset provenance",
    status: "implemented",
    proof: "Downloaded Quaternius packs are recorded with local archive path, size, hash, source URL, selected launch use, and per-GLB source evidence for every public launch asset.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/assets/quaternius-asset-provenance.json",
      "apps/aura-clash-showcase/assets/quaternius-selection.json",
      "apps/aura-clash-showcase/assets/quaternius-staged-manifest.json",
    ],
  },
  {
    id: "launch-glb-source-evidence",
    label: "Launch GLB source evidence",
    status: "implemented",
    proof: "Every public launch GLB has source evidence for provenance, license note, thumbnail, bounds, material summary, and intended route usage; playable fighters additionally record typed-GLB delivery, no primitive fallback approval, scale, pivot policy, facing policy, bounds, material readability, and thumbnail evidence.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/aura.assets.json",
      "apps/aura-clash-showcase/scripts/check-production-assets.mjs",
      "apps/aura-clash-showcase/scripts/blender-build-aura-clash-assets.py",
    ],
  },
  {
    id: "gameplay-loop",
    label: "Playable combat loop",
    status: "implemented",
    proof: "The route exposes A/D or arrow-key movement, Space jump, attacks, guard, dash, meter, round timer, AI pressure, restart, P/Escape pause, and result states.",
    files: [
      "apps/aura-clash-showcase/src/playable/AuraClashArenaApp.ts",
      "apps/aura-clash-showcase/src/playable/combat/auraClashMoveData.ts",
      "apps/aura-clash-showcase/src/playable/playable.css",
      "apps/aura-clash-showcase/playable/index.html",
    ],
  },
  {
    id: "runtime-node-mutation",
    label: "Runtime node mutation evidence",
    status: "implemented",
    proof: "The playable route creates typed GLB actors once, mutates their actor roots and animation state every frame, and exports JSON proof through window.__AURA_CLASH_ARENA_PROOF__ without per-frame scene rebuilds or GLB reloads.",
    files: [
      "apps/aura-clash-showcase/src/playable/AuraClashArenaApp.ts",
      "apps/aura-clash-showcase/src/playable/animation/auraClashClipMaps.ts",
      "apps/aura-clash-showcase/src/playable/evidence/auraClashArenaProof.ts",
    ],
  },
  {
    id: "browser-evidence-route-runtime-debug",
    label: "Browser evidence route current proof source",
    status: "implemented",
    proof: "The evidence route declares the current aura-clash-arena-proof/v1 schema, reads window.__AURA_CLASH_ARENA_PROOF__, and links the 1.0.6 readiness/deployed proof artifacts instead of stale deleted-attempt artifacts.",
    files: [
      "apps/aura-clash-showcase/evidence/index.html",
      "apps/aura-clash-showcase/src/playable/evidence/auraClashArenaProof.ts",
      "apps/aura-clash-showcase/launch-evidence/aura-clash-106-readiness.json",
      "apps/aura-clash-showcase/launch-evidence/deployed-106-proof.json",
    ],
  },
  {
    id: "route-surface",
    label: "Showcase routes",
    status: "implemented",
    proof: "Playable, evidence, accessibility, deploy-check, and poster route HTML entry points exist for static hosting.",
    files: [
      "apps/aura-clash-showcase/playable/index.html",
      "apps/aura-clash-showcase/evidence/index.html",
      "apps/aura-clash-showcase/accessibility/index.html",
      "apps/aura-clash-showcase/deploy-check/index.html",
      "apps/aura-clash-showcase/poster/index.html",
    ],
  },
  {
    id: "accessibility-controls",
    label: "Accessibility controls",
    status: "implemented",
    proof: "Reduced motion, reduced flash, and high contrast toggles are available in the game UI; reduced motion also suppresses scene/camera animation where practical.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/styles.css",
      "apps/aura-clash-showcase/accessibility/index.html",
    ],
  },
  {
    id: "test-scaffold",
    label: "Route and capture test scaffold",
    status: "implemented",
    proof: "Playwright specs are scaffolded for route health, playable smoke, accessibility, deploy check, and screenshot capture.",
    files: [
      "apps/aura-clash-showcase/playwright.config.ts",
      "apps/aura-clash-showcase/tests/route-health.spec.ts",
      "apps/aura-clash-showcase/tests/playable-smoke.spec.ts",
      "apps/aura-clash-showcase/tests/accessibility.spec.ts",
      "apps/aura-clash-showcase/tests/deploy-check.spec.ts",
      "apps/aura-clash-showcase/tests/screenshot.spec.ts",
    ],
  },
  {
    id: "visual-qa",
    label: "10/10 visual QA",
    status: "needs-visual-qa",
    proof: "The implementation has not been browser-reviewed or screenshot-approved in this pass.",
    files: [
      "apps/aura-clash-showcase/src/main.ts",
      "apps/aura-clash-showcase/src/styles.css",
      "apps/aura-clash-showcase/tests/screenshot.spec.ts",
    ],
  },
];

export const auraClashAcceptanceGates: AuraClashEvidenceItem[] = [
  {
    id: "asset-integrity",
    label: "Asset integrity",
    status: "implemented",
    proof: "Source GLBs, public GLBs, selected Quaternius files, and typed asset registry files exist in the app structure.",
    files: [
      "apps/aura-clash-showcase/assets/source",
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/public/aura-assets",
      "apps/aura-clash-showcase/src/aura-assets.ts",
    ],
  },
  {
    id: "fighter-source-validation",
    label: "Playable fighter source validation",
    status: "implemented",
    proof: "The source evidence manifest records all six playable fighters as typed GLBs with no approved primitive fallback, plus production gate source, scale, pivot policy, facing policy, bounds, material readability, and thumbnail evidence.",
    files: [
      "apps/aura-clash-showcase/assets/source/aura-clash-launch-asset-evidence.json",
      "apps/aura-clash-showcase/scripts/check-production-assets.mjs",
      "apps/aura-clash-showcase/scripts/blender-build-aura-clash-assets.py",
      "apps/aura-clash-showcase/aura.assets.json",
    ],
  },
  {
    id: "public-api",
    label: "Public Aura3D API usage",
    status: "implemented",
    proof: "The showcase uses public createGameApp, game.combatWorld, createGameAudio, scene, and typed production-runtime GLB actor helpers from @aura3d/engine with typed assets.",
    files: ["apps/aura-clash-showcase/src/playable/AuraClashArenaApp.ts"],
  },
  {
    id: "browser-qa",
    label: "Browser visual approval",
    status: "needs-visual-qa",
    proof: "Requires explicit browser/screenshot review before declaring the flagship showcase complete.",
    files: ["apps/aura-clash-showcase/tests/screenshot.spec.ts"],
  },
  {
    id: "marketing-promotion",
    label: "Marketing promotion",
    status: "pending",
    proof: "Main Aura3D marketing integration should wait until the game route is visually approved.",
    files: ["docs/examples/aura-clash.md"],
  },
];
