import { describe,it,expect } from 'vitest';
import { validateRootGovernorReport } from '../browser/muse3jsparity-301-root-governor-contract';
function fixture(){let q={resolutionScale:1,particleScale:1,lodBias:1,shadowSize:1024};const sample=(quality:typeof q)=>({gpuCompleted:true,frameMs:25,rafPacingMs:30,pixels:500,width:Math.round(960*quality.resolutionScale),height:Math.round(540*quality.resolutionScale),particles:Math.floor(10000*quality.particleScale),draws:[{indexed:false,count:Math.floor(10000*quality.particleScale)*6,instances:1,shadow:false,viewport:[0,0,960,540]},{indexed:true,count:3*(quality.lodBias===1?256:quality.lodBias===1.25?128:quality.lodBias===1.6?64:8),instances:512,shadow:false,viewport:[0,0,960,540]},{indexed:true,count:36,instances:1,shadow:true,viewport:[0,0,quality.shadowSize,quality.shadowSize]}]});const restored=sample(q);const steps:Array<[keyof typeof q,number]>=[['resolutionScale',.85],['resolutionScale',.7],['resolutionScale',.5],['particleScale',.7],['particleScale',.4],['particleScale',.2],['lodBias',1.25],['lodBias',1.6],['lodBias',2],['shadowSize',512],['shadowSize',256]];const rungs=steps.map(([key,value])=>{const before={...q},overload=Array.from({length:8},()=>sample(before));q={...q,[key]:value};return{before,after:{...q},instances:512,changed:[key],overload,adapted:Array.from({length:3},()=>sample(q))};});return{schema:'aura3d.root-governor-301/v1',complete:true,hardware:'test-only observer fixture',entryPoint:'createAuraApp.stepAsync createGameAppRuntime.pollPerformance',budget:{maxFrameTimeMs:16.7,minFps:55},rungs,restored};}
describe('root governor receipt contract',()=>{
 it('accepts a complete raw measurement shape independently of status flag',()=>{const r=fixture();r.complete=false;expect(validateRootGovernorReport(r)).toEqual([]);});
 it('rejects missing adapted frames despite complete true',()=>{const r=fixture();r.rungs[0]!.adapted=[];expect(validateRootGovernorReport(r)).toContain('rung 0: adapted samples');});
 it('rejects metadata changes without native resource changes',()=>{for(const mutation of ['particle','lod','shadow','resolution','completion']){const r=fixture(),f=r.rungs[10]!.adapted[0]!;if(mutation==='particle')f.draws[0]!.count=1;if(mutation==='lod')f.draws[1]!.count=1;if(mutation==='shadow')f.draws[2]!.viewport=[0,0,1024,1024];if(mutation==='resolution')f.width=960;if(mutation==='completion')f.gpuCompleted=false;expect(validateRootGovernorReport(r).length).toBeGreaterThan(0);}});
 it('rejects invented overload, missing restoration and skipped ladder',()=>{const r=fixture();r.rungs[0]!.overload.forEach(f=>f.frameMs=1);delete (r as {restored?:unknown}).restored;r.rungs[0]!.after.resolutionScale=.5;expect(validateRootGovernorReport(r)).toContain('rung 0: no measured overload');expect(validateRootGovernorReport(r)).toContain('restoration missing');expect(validateRootGovernorReport(r)).toContain('rung 0: quality resolutionScale');});
});
