export { EffectComposerThreeCompat } from "./EffectComposer";
export { RenderPassThreeCompat } from "./RenderPass";
export { ShaderPassThreeCompat } from "./ShaderPass";
export { BloomPassThreeCompat } from "./BloomPass";
export { SSAOPassThreeCompat } from "./SSAOPass";
export { TAAPassThreeCompat } from "./TAAPass";
export { FXAAPassThreeCompat } from "./FXAAPass";
export { SMAAPassThreeCompat } from "./SMAAPass";
export { DepthOfFieldPassThreeCompat } from "./DepthOfFieldPass";
export { MotionBlurPassThreeCompat } from "./MotionBlurPass";
export { ColorGradingPassThreeCompat } from "./ColorGradingPass";
export { VignettePassThreeCompat } from "./VignettePass";
export { OutlinePassThreeCompat } from "./OutlinePass";
export { createThreeCompatBaseFrame, createThreeCompatDemoFrame } from "./PostProcessTypes";
export type { ThreeCompatBaseFrameOptions, ThreeCompatPostProcessFrame, ThreeCompatPostProcessPass } from "./PostProcessTypes";
