using System;
using System.IO;
using UnityEngine;

public sealed class ProductVisualParityBaseline : MonoBehaviour
{
    // Consumes product-visual-parity-scene.json from this directory and renders the
    // deterministic V4 product scene. The generated report must be copied to
    // tests/reports/v4-unity-product-visual-baseline.json.
    public TextAsset SceneDescriptor;
    public string ScreenshotPath = "tests/reports/v4-product-visual-parity/unity-product-baseline.png";

    private void Start()
    {
        if (SceneDescriptor == null)
        {
            throw new InvalidOperationException("Assign product-visual-parity-scene.json to SceneDescriptor.");
        }
        BuildScene();
        Camera.main.orthographic = true;
        Camera.main.orthographicSize = 1.15f;
        Camera.main.transform.position = new Vector3(0, 0, -4);
        Camera.main.transform.rotation = Quaternion.identity;
        Directory.CreateDirectory(Path.GetDirectoryName(ScreenshotPath));
        ScreenCapture.CaptureScreenshot(ScreenshotPath);
    }

    private static void BuildScene()
    {
        // Keep this runner intentionally explicit. The scene descriptor is the source
        // of truth; this script is a portable baseline scaffold, not parity evidence
        // until the screenshot/report are generated by a real Unity editor run.
        var body = CreatePart("body", PrimitiveType.Cube, new Vector3(0, -0.04f, 0), new Vector3(1.44f, 0.76f, 0.36f), new Color(0.1f, 0.14f, 0.18f, 1));
        body.GetComponent<Renderer>().material.SetFloat("_Metallic", 0.78f);
        body.GetComponent<Renderer>().material.SetFloat("_Glossiness", 0.76f);
        CreatePart("screen", PrimitiveType.Cube, new Vector3(0, 0.02f, 0.03f), new Vector3(1.04f, 0.48f, 0.06f), new Color(0.08f, 0.32f, 0.52f, 0.82f));
        CreatePart("left-dial", PrimitiveType.Sphere, new Vector3(-0.54f, -0.08f, 0), new Vector3(0.56f, 0.56f, 0.16f), Color.black);
        CreatePart("right-dial", PrimitiveType.Sphere, new Vector3(0.54f, -0.08f, 0), new Vector3(0.56f, 0.56f, 0.16f), Color.black);
        for (var i = 0; i < 14; i++)
        {
            var x = -0.84f + i * 0.13f;
            CreatePart("detail-" + i, PrimitiveType.Cube, new Vector3(x, -0.31f + (i % 3) * 0.2f, 0.08f), new Vector3(0.07f, 0.035f, 0.03f), new Color(0.9f, 0.48f, 0.18f, 1));
        }
        var lightObject = new GameObject("studio-key-light");
        var light = lightObject.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1.1f;
        lightObject.transform.rotation = Quaternion.Euler(35, -35, 0);
    }

    private static GameObject CreatePart(string name, PrimitiveType primitive, Vector3 position, Vector3 scale, Color color)
    {
        var obj = GameObject.CreatePrimitive(primitive);
        obj.name = name;
        obj.transform.position = position;
        obj.transform.localScale = scale;
        var material = new Material(Shader.Find("Standard"));
        material.color = color;
        obj.GetComponent<Renderer>().material = material;
        return obj;
    }
}
